/* * * * * * * * * * * */
/* created by Naom Hod */
/* noam.hod@cern.ch    */
/* noam.com@gmail.com  */
/* on 23/07/2010 11:24 */
/* * * * * * * * * * * */

#include "offlineTree.h"

offlineTree::offlineTree()
{

}

offlineTree::~offlineTree()
{

}

offlineTree::offlineTree(physics* phys, TFile* treeFile)
{
	m_phys = phys;

	m_treeFile = treeFile;

	m_treeFile->cd();

	m_tree = new TTree("offline", "offline");

	m_tree->SetMaxTreeSize(50000000); // 50Mb per file

	setBranches();
}

void offlineTree::setBranches()
{
	// event level
	m_tree->Branch( "isGRL", &isGRL );
		
	m_tree->Branch( "RunNumber", &RunNumber );
	m_tree->Branch( "EventNumber", &EventNumber );
	m_tree->Branch( "timestamp", &timestamp );
	m_tree->Branch( "timestamp_ns", &timestamp_ns );
	m_tree->Branch( "lbn", &lbn );
	m_tree->Branch( "bcid", &bcid );
	m_tree->Branch( "detmask0", &detmask0 );
	m_tree->Branch( "detmask1", &detmask1 );
	m_tree->Branch( "pixelFlags", &pixelFlags );
	m_tree->Branch( "sctFlags", &sctFlags );
	m_tree->Branch( "trtFlags", &trtFlags );
	m_tree->Branch( "larFlags", &larFlags );
	m_tree->Branch( "tileFlags", &tileFlags );
	m_tree->Branch( "muonFlags", &muonFlags );
	m_tree->Branch( "fwdFlags", &fwdFlags );
	m_tree->Branch( "coreFlags", &coreFlags );
	m_tree->Branch( "pixelError", &pixelError );
	m_tree->Branch( "sctError", &sctError );
	m_tree->Branch( "trtError", &trtError );
	m_tree->Branch( "larError", &larError );
	m_tree->Branch( "tileError", &tileError );
	m_tree->Branch( "muonError", &muonError );
	m_tree->Branch( "fwdError", &fwdError );
	m_tree->Branch( "coreError", &coreError );
	m_tree->Branch( "lar_ncellA", &lar_ncellA );
	m_tree->Branch( "lar_ncellC", &lar_ncellC );
	m_tree->Branch( "lar_energyA", &lar_energyA );
	m_tree->Branch( "lar_energyC", &lar_energyC );
	m_tree->Branch( "lar_timeA", &lar_timeA );
	m_tree->Branch( "lar_timeC", &lar_timeC );
	m_tree->Branch( "lar_timeDiff", &lar_timeDiff );
			
	m_tree->Branch( "EF_2mu10", &EF_2mu10 );
	m_tree->Branch( "EF_2mu4", &EF_2mu4 );
	m_tree->Branch( "EF_2mu4_DiMu", &EF_2mu4_DiMu );
	m_tree->Branch( "EF_2mu4_DiMu_SiTrk", &EF_2mu4_DiMu_SiTrk );
	m_tree->Branch( "EF_2mu4_DiMu_noOS", &EF_2mu4_DiMu_noOS );
	m_tree->Branch( "EF_2mu4_DiMu_noOS_passL2", &EF_2mu4_DiMu_noOS_passL2 );
	m_tree->Branch( "EF_2mu4_DiMu_noVtx_noOS", &EF_2mu4_DiMu_noVtx_noOS );
	m_tree->Branch( "EF_2mu4_DiMu_noVtx_noOS_passL2", &EF_2mu4_DiMu_noVtx_noOS_passL2 );
	m_tree->Branch( "EF_2mu4_MSonly", &EF_2mu4_MSonly );
	m_tree->Branch( "EF_2mu6", &EF_2mu6 );
	m_tree->Branch( "EF_2mu6_DiMu", &EF_2mu6_DiMu );
	m_tree->Branch( "EF_2mu6_DiMu_noVtx_noOS", &EF_2mu6_DiMu_noVtx_noOS );
	m_tree->Branch( "EF_L1ItemStreamer_L1_2MU0", &EF_L1ItemStreamer_L1_2MU0 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_2MU0_MU6", &EF_L1ItemStreamer_L1_2MU0_MU6 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_2MU10", &EF_L1ItemStreamer_L1_2MU10 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_2MU6", &EF_L1ItemStreamer_L1_2MU6 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM10", &EF_L1ItemStreamer_L1_EM10 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM10I", &EF_L1ItemStreamer_L1_EM10I );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM14", &EF_L1ItemStreamer_L1_EM14 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM2", &EF_L1ItemStreamer_L1_EM2 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM2_UNPAIRED", &EF_L1ItemStreamer_L1_EM2_UNPAIRED );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM3", &EF_L1ItemStreamer_L1_EM3 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM3_EMPTY", &EF_L1ItemStreamer_L1_EM3_EMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM3_FIRSTEMPTY", &EF_L1ItemStreamer_L1_EM3_FIRSTEMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM3_MV", &EF_L1ItemStreamer_L1_EM3_MV );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM3_UNPAIRED", &EF_L1ItemStreamer_L1_EM3_UNPAIRED );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM4", &EF_L1ItemStreamer_L1_EM4 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM5", &EF_L1ItemStreamer_L1_EM5 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_EM5I", &EF_L1ItemStreamer_L1_EM5I );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0", &EF_L1ItemStreamer_L1_MU0 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_COMM", &EF_L1ItemStreamer_L1_MU0_COMM );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_COMM_EMPTY", &EF_L1ItemStreamer_L1_MU0_COMM_EMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY", &EF_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_EM3", &EF_L1ItemStreamer_L1_MU0_EM3 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_EMPTY", &EF_L1ItemStreamer_L1_MU0_EMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_FIRSTEMPTY", &EF_L1ItemStreamer_L1_MU0_FIRSTEMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_J10", &EF_L1ItemStreamer_L1_MU0_J10 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_J15", &EF_L1ItemStreamer_L1_MU0_J15 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_J5", &EF_L1ItemStreamer_L1_MU0_J5 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_MV", &EF_L1ItemStreamer_L1_MU0_MV );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU0_UNPAIRED", &EF_L1ItemStreamer_L1_MU0_UNPAIRED );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU10", &EF_L1ItemStreamer_L1_MU10 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU10_EMPTY", &EF_L1ItemStreamer_L1_MU10_EMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU15", &EF_L1ItemStreamer_L1_MU15 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU20", &EF_L1ItemStreamer_L1_MU20 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6", &EF_L1ItemStreamer_L1_MU6 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6_EM3", &EF_L1ItemStreamer_L1_MU6_EM3 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6_EMPTY", &EF_L1ItemStreamer_L1_MU6_EMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6_FIRSTEMPTY", &EF_L1ItemStreamer_L1_MU6_FIRSTEMPTY );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6_J5", &EF_L1ItemStreamer_L1_MU6_J5 );
	m_tree->Branch( "EF_L1ItemStreamer_L1_MU6_UNPAIRED", &EF_L1ItemStreamer_L1_MU6_UNPAIRED );
	   
	 m_tree->Branch( "EF_mu0_missingRoi", &EF_mu0_missingRoi );
	m_tree->Branch( "EF_mu0_rpcOnly", &EF_mu0_rpcOnly );
	m_tree->Branch( "EF_mu10", &EF_mu10 );
	m_tree->Branch( "EF_mu10_MG", &EF_mu10_MG );
	m_tree->Branch( "EF_mu10_MSonly", &EF_mu10_MSonly );
	m_tree->Branch( "EF_mu10_MSonly_cosmic", &EF_mu10_MSonly_cosmic );
	m_tree->Branch( "EF_mu10_NoIDTrkCut", &EF_mu10_NoIDTrkCut );
	m_tree->Branch( "EF_mu10_SiTrk", &EF_mu10_SiTrk );
	m_tree->Branch( "EF_mu10_cosmic", &EF_mu10_cosmic );
	m_tree->Branch( "EF_mu10_muCombTag", &EF_mu10_muCombTag );
	m_tree->Branch( "EF_mu10_muCombTag_SiTrk", &EF_mu10_muCombTag_SiTrk );
	m_tree->Branch( "EF_mu10_passHLT", &EF_mu10_passHLT );
	m_tree->Branch( "EF_mu10i_loose", &EF_mu10i_loose );
	m_tree->Branch( "EF_mu13", &EF_mu13 );
	m_tree->Branch( "EF_mu15", &EF_mu15 );
	m_tree->Branch( "EF_mu20", &EF_mu20 );
	m_tree->Branch( "EF_mu20_MSonly", &EF_mu20_MSonly );
	m_tree->Branch( "EF_mu20_passHLT", &EF_mu20_passHLT );
	m_tree->Branch( "EF_mu4", &EF_mu4 );
	m_tree->Branch( "EF_mu4_DiMu", &EF_mu4_DiMu );
	m_tree->Branch( "EF_mu4_DiMu_FS", &EF_mu4_DiMu_FS );
	m_tree->Branch( "EF_mu4_DiMu_FS_noOS", &EF_mu4_DiMu_FS_noOS );
	m_tree->Branch( "EF_mu4_Jpsie5e3", &EF_mu4_Jpsie5e3 );
	m_tree->Branch( "EF_mu4_Jpsie5e3_FS", &EF_mu4_Jpsie5e3_FS );
	m_tree->Branch( "EF_mu4_Jpsie5e3_SiTrk", &EF_mu4_Jpsie5e3_SiTrk );
	m_tree->Branch( "EF_mu4_Jpsie5e3_SiTrk_FS", &EF_mu4_Jpsie5e3_SiTrk_FS );
	m_tree->Branch( "EF_mu4_L2MSonly_EFFS_passL2", &EF_mu4_L2MSonly_EFFS_passL2 );
	m_tree->Branch( "EF_mu4_MG", &EF_mu4_MG );
	m_tree->Branch( "EF_mu4_MSonly", &EF_mu4_MSonly );
	m_tree->Branch( "EF_mu4_MSonly_EFFS_passL2", &EF_mu4_MSonly_EFFS_passL2 );
	m_tree->Branch( "EF_mu4_MSonly_MB2_noL2_EFFS", &EF_mu4_MSonly_MB2_noL2_EFFS );
	m_tree->Branch( "EF_mu4_MSonly_Trk_Jpsi_loose", &EF_mu4_MSonly_Trk_Jpsi_loose );
	m_tree->Branch( "EF_mu4_MSonly_Trk_Upsi_loose_FS", &EF_mu4_MSonly_Trk_Upsi_loose_FS );
	m_tree->Branch( "EF_mu4_MSonly_cosmic", &EF_mu4_MSonly_cosmic );
	m_tree->Branch( "EF_mu4_MSonly_firstempty", &EF_mu4_MSonly_firstempty );
	m_tree->Branch( "EF_mu4_MV", &EF_mu4_MV );
	m_tree->Branch( "EF_mu4_NoIDTrkCut", &EF_mu4_NoIDTrkCut );
	m_tree->Branch( "EF_mu4_SiTrk", &EF_mu4_SiTrk );
	m_tree->Branch( "EF_mu4_Trk_Jpsi_loose", &EF_mu4_Trk_Jpsi_loose );
	m_tree->Branch( "EF_mu4_Trk_Upsi_loose_FS", &EF_mu4_Trk_Upsi_loose_FS );
	m_tree->Branch( "EF_mu4_comm", &EF_mu4_comm );
	m_tree->Branch( "EF_mu4_comm_MSonly", &EF_mu4_comm_MSonly );
	m_tree->Branch( "EF_mu4_comm_MSonly_cosmic", &EF_mu4_comm_MSonly_cosmic );
	m_tree->Branch( "EF_mu4_comm_MSonly_firstempty", &EF_mu4_comm_MSonly_firstempty );
	m_tree->Branch( "EF_mu4_comm_cosmic", &EF_mu4_comm_cosmic );
	m_tree->Branch( "EF_mu4_comm_firstempty", &EF_mu4_comm_firstempty );
	m_tree->Branch( "EF_mu4_cosmic", &EF_mu4_cosmic );
	m_tree->Branch( "EF_mu4_firstempty", &EF_mu4_firstempty );
	m_tree->Branch( "EF_mu4_j10_matched", &EF_mu4_j10_matched );
	m_tree->Branch( "EF_mu4_j20_matched", &EF_mu4_j20_matched );
	m_tree->Branch( "EF_mu4_j5_matched", &EF_mu4_j5_matched );
	m_tree->Branch( "EF_mu4_mu6", &EF_mu4_mu6 );
	m_tree->Branch( "EF_mu4_muCombTag", &EF_mu4_muCombTag );
	m_tree->Branch( "EF_mu4_muCombTag_SiTrk", &EF_mu4_muCombTag_SiTrk );
	m_tree->Branch( "EF_mu4_passHLT", &EF_mu4_passHLT );
	m_tree->Branch( "EF_mu4_tile", &EF_mu4_tile );
	m_tree->Branch( "EF_mu4_tile_SiTrk", &EF_mu4_tile_SiTrk );
	m_tree->Branch( "EF_mu4_trod", &EF_mu4_trod );
	m_tree->Branch( "EF_mu4_trod_SiTrk", &EF_mu4_trod_SiTrk );
	m_tree->Branch( "EF_mu4_unpaired", &EF_mu4_unpaired );
	m_tree->Branch( "EF_mu4mu6_DiMu", &EF_mu4mu6_DiMu );
	m_tree->Branch( "EF_mu6", &EF_mu6 );
	m_tree->Branch( "EF_mu6_DiMu", &EF_mu6_DiMu );
	m_tree->Branch( "EF_mu6_DiMu_FS", &EF_mu6_DiMu_FS );
	m_tree->Branch( "EF_mu6_DiMu_FS_noOS", &EF_mu6_DiMu_FS_noOS );
	m_tree->Branch( "EF_mu6_DsPhiPi", &EF_mu6_DsPhiPi );
	m_tree->Branch( "EF_mu6_Jpsie5e3", &EF_mu6_Jpsie5e3 );
	m_tree->Branch( "EF_mu6_Jpsie5e3_FS", &EF_mu6_Jpsie5e3_FS );
	m_tree->Branch( "EF_mu6_Jpsie5e3_SiTrk", &EF_mu6_Jpsie5e3_SiTrk );
	m_tree->Branch( "EF_mu6_Jpsie5e3_SiTrk_FS", &EF_mu6_Jpsie5e3_SiTrk_FS );
	m_tree->Branch( "EF_mu6_MG", &EF_mu6_MG );
	m_tree->Branch( "EF_mu6_MSonly", &EF_mu6_MSonly );
	m_tree->Branch( "EF_mu6_MSonly_cosmic", &EF_mu6_MSonly_cosmic );
	m_tree->Branch( "EF_mu6_MSonly_firstempty", &EF_mu6_MSonly_firstempty );
	m_tree->Branch( "EF_mu6_MSonly_unpaired", &EF_mu6_MSonly_unpaired );
	m_tree->Branch( "EF_mu6_SiTrk", &EF_mu6_SiTrk );
	m_tree->Branch( "EF_mu6_Trk_Jpsi_loose", &EF_mu6_Trk_Jpsi_loose );
	m_tree->Branch( "EF_mu6_Trk_Jpsi_loose_FS", &EF_mu6_Trk_Jpsi_loose_FS );
	m_tree->Branch( "EF_mu6_Trk_Upsi_loose_FS", &EF_mu6_Trk_Upsi_loose_FS );
	m_tree->Branch( "EF_mu6_cosmic", &EF_mu6_cosmic );
	m_tree->Branch( "EF_mu6_firstempty", &EF_mu6_firstempty );
	m_tree->Branch( "EF_mu6_muCombTag", &EF_mu6_muCombTag );
	m_tree->Branch( "EF_mu6_muCombTag_SiTrk", &EF_mu6_muCombTag_SiTrk );
	m_tree->Branch( "EF_mu6_passHLT", &EF_mu6_passHLT );
	m_tree->Branch( "EF_mu6_unpaired", &EF_mu6_unpaired );
	   
	m_tree->Branch( "L1_2EM2", &L1_2EM2 );
	m_tree->Branch( "L1_2EM3", &L1_2EM3 );
	m_tree->Branch( "L1_2EM4", &L1_2EM4 );
	m_tree->Branch( "L1_2EM5", &L1_2EM5 );
	m_tree->Branch( "L1_2MU0", &L1_2MU0 );
	m_tree->Branch( "L1_2MU0_MU6", &L1_2MU0_MU6 );
	m_tree->Branch( "L1_2MU10", &L1_2MU10 );
	m_tree->Branch( "L1_2MU6", &L1_2MU6 );
	m_tree->Branch( "L1_EM10", &L1_EM10 );
	m_tree->Branch( "L1_EM10I", &L1_EM10I );
	m_tree->Branch( "L1_EM14", &L1_EM14 );
	m_tree->Branch( "L1_EM2", &L1_EM2 );
	m_tree->Branch( "L1_EM2_UNPAIRED", &L1_EM2_UNPAIRED );
	m_tree->Branch( "L1_EM3", &L1_EM3 );
	m_tree->Branch( "L1_EM3_EMPTY", &L1_EM3_EMPTY );
	m_tree->Branch( "L1_EM3_FIRSTEMPTY", &L1_EM3_FIRSTEMPTY );
	m_tree->Branch( "L1_EM3_MV", &L1_EM3_MV );
	m_tree->Branch( "L1_EM3_UNPAIRED", &L1_EM3_UNPAIRED );
	m_tree->Branch( "L1_EM4", &L1_EM4 );
	m_tree->Branch( "L1_EM5", &L1_EM5 );
	m_tree->Branch( "L1_EM5I", &L1_EM5I );
	m_tree->Branch( "L1_MU0", &L1_MU0 );
	m_tree->Branch( "L1_MU0_COMM", &L1_MU0_COMM );
	m_tree->Branch( "L1_MU0_COMM_EMPTY", &L1_MU0_COMM_EMPTY );
	m_tree->Branch( "L1_MU0_COMM_FIRSTEMPTY", &L1_MU0_COMM_FIRSTEMPTY );
	m_tree->Branch( "L1_MU0_EM3", &L1_MU0_EM3 );
	m_tree->Branch( "L1_MU0_EMPTY", &L1_MU0_EMPTY );
	m_tree->Branch( "L1_MU0_FIRSTEMPTY", &L1_MU0_FIRSTEMPTY );
	m_tree->Branch( "L1_MU0_J10", &L1_MU0_J10 );
	m_tree->Branch( "L1_MU0_J15", &L1_MU0_J15 );
	m_tree->Branch( "L1_MU0_J5", &L1_MU0_J5 );
	m_tree->Branch( "L1_MU0_MV", &L1_MU0_MV );
	m_tree->Branch( "L1_MU0_UNPAIRED", &L1_MU0_UNPAIRED );
	m_tree->Branch( "L1_MU10", &L1_MU10 );
	m_tree->Branch( "L1_MU10_EMPTY", &L1_MU10_EMPTY );
	m_tree->Branch( "L1_MU15", &L1_MU15 );
	m_tree->Branch( "L1_MU20", &L1_MU20 );
	m_tree->Branch( "L1_MU6", &L1_MU6 );
	m_tree->Branch( "L1_MU6_EM3", &L1_MU6_EM3 );
	m_tree->Branch( "L1_MU6_EMPTY", &L1_MU6_EMPTY );
	m_tree->Branch( "L1_MU6_FIRSTEMPTY", &L1_MU6_FIRSTEMPTY );
	m_tree->Branch( "L1_MU6_J5", &L1_MU6_J5 );
	m_tree->Branch( "L1_MU6_UNPAIRED", &L1_MU6_UNPAIRED );
	   
	m_tree->Branch( "L2_2mu10", &L2_2mu10 );
	m_tree->Branch( "L2_2mu4", &L2_2mu4 );
	m_tree->Branch( "L2_2mu4_DiMu", &L2_2mu4_DiMu );
	m_tree->Branch( "L2_2mu4_DiMu_SiTrk", &L2_2mu4_DiMu_SiTrk );
	m_tree->Branch( "L2_2mu4_DiMu_noOS", &L2_2mu4_DiMu_noOS );
	m_tree->Branch( "L2_2mu4_DiMu_noOS_passL2", &L2_2mu4_DiMu_noOS_passL2 );
	m_tree->Branch( "L2_2mu4_DiMu_noVtx_noOS", &L2_2mu4_DiMu_noVtx_noOS );
	m_tree->Branch( "L2_2mu4_DiMu_noVtx_noOS_passL2", &L2_2mu4_DiMu_noVtx_noOS_passL2 );
	m_tree->Branch( "L2_2mu4_MSonly", &L2_2mu4_MSonly );
	m_tree->Branch( "L2_2mu6", &L2_2mu6 );
	m_tree->Branch( "L2_2mu6_DiMu", &L2_2mu6_DiMu );
	m_tree->Branch( "L2_2mu6_DiMu_noVtx_noOS", &L2_2mu6_DiMu_noVtx_noOS );
	   
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0", &L2_L1ItemStreamer_L1_MU0 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_COMM", &L2_L1ItemStreamer_L1_MU0_COMM );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_COMM_EMPTY", &L2_L1ItemStreamer_L1_MU0_COMM_EMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY", &L2_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_EM3", &L2_L1ItemStreamer_L1_MU0_EM3 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_EMPTY", &L2_L1ItemStreamer_L1_MU0_EMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_FIRSTEMPTY", &L2_L1ItemStreamer_L1_MU0_FIRSTEMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_J10", &L2_L1ItemStreamer_L1_MU0_J10 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_J15", &L2_L1ItemStreamer_L1_MU0_J15 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_J5", &L2_L1ItemStreamer_L1_MU0_J5 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_MV", &L2_L1ItemStreamer_L1_MU0_MV );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU0_UNPAIRED", &L2_L1ItemStreamer_L1_MU0_UNPAIRED );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU10", &L2_L1ItemStreamer_L1_MU10 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU10_EMPTY", &L2_L1ItemStreamer_L1_MU10_EMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU15", &L2_L1ItemStreamer_L1_MU15 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU20", &L2_L1ItemStreamer_L1_MU20 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6", &L2_L1ItemStreamer_L1_MU6 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6_EM3", &L2_L1ItemStreamer_L1_MU6_EM3 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6_EMPTY", &L2_L1ItemStreamer_L1_MU6_EMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6_FIRSTEMPTY", &L2_L1ItemStreamer_L1_MU6_FIRSTEMPTY );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6_J5", &L2_L1ItemStreamer_L1_MU6_J5 );
	m_tree->Branch( "L2_L1ItemStreamer_L1_MU6_UNPAIRED", &L2_L1ItemStreamer_L1_MU6_UNPAIRED );
	   
	m_tree->Branch( "L2_mu0_missingRoi", &L2_mu0_missingRoi );
	m_tree->Branch( "L2_mu0_rpcOnly", &L2_mu0_rpcOnly );
	m_tree->Branch( "L2_mu10", &L2_mu10 );
	m_tree->Branch( "L2_mu10_MG", &L2_mu10_MG );
	m_tree->Branch( "L2_mu10_MSonly", &L2_mu10_MSonly );
	m_tree->Branch( "L2_mu10_MSonly_cosmic", &L2_mu10_MSonly_cosmic );
	m_tree->Branch( "L2_mu10_NoIDTrkCut", &L2_mu10_NoIDTrkCut );
	m_tree->Branch( "L2_mu10_SiTrk", &L2_mu10_SiTrk );
	m_tree->Branch( "L2_mu10_cosmic", &L2_mu10_cosmic );
	m_tree->Branch( "L2_mu10_muCombTag", &L2_mu10_muCombTag );
	m_tree->Branch( "L2_mu10_muCombTag_SiTrk", &L2_mu10_muCombTag_SiTrk );
	m_tree->Branch( "L2_mu10_passHLT", &L2_mu10_passHLT );
	m_tree->Branch( "L2_mu10i_loose", &L2_mu10i_loose );
	m_tree->Branch( "L2_mu13 ", &L2_mu13 );
	m_tree->Branch( "L2_mu15", &L2_mu15 );
	m_tree->Branch( "L2_mu20", &L2_mu20 );
	m_tree->Branch( "L2_mu20_MSonly", &L2_mu20_MSonly );
	m_tree->Branch( "L2_mu20_passHLT", &L2_mu20_passHLT );
	m_tree->Branch( "L2_mu4", &L2_mu4 );
	m_tree->Branch( "L2_mu4_DiMu", &L2_mu4_DiMu );
	m_tree->Branch( "L2_mu4_DiMu_FS", &L2_mu4_DiMu_FS );
	m_tree->Branch( "L2_mu4_DiMu_FS_noOS", &L2_mu4_DiMu_FS_noOS );
	m_tree->Branch( "L2_mu4_Jpsie5e3", &L2_mu4_Jpsie5e3 );
	m_tree->Branch( "L2_mu4_Jpsie5e3_FS", &L2_mu4_Jpsie5e3_FS );
	m_tree->Branch( "L2_mu4_Jpsie5e3_SiTrk", &L2_mu4_Jpsie5e3_SiTrk );
	m_tree->Branch( "L2_mu4_Jpsie5e3_SiTrk_FS", &L2_mu4_Jpsie5e3_SiTrk_FS );
	m_tree->Branch( "L2_mu4_L2MSonly_EFFS_passL2", &L2_mu4_L2MSonly_EFFS_passL2 );
	m_tree->Branch( "L2_mu4_MG", &L2_mu4_MG );
	m_tree->Branch( "L2_mu4_MSonly", &L2_mu4_MSonly );
	m_tree->Branch( "L2_mu4_MSonly_EFFS_passL2", &L2_mu4_MSonly_EFFS_passL2 );
	m_tree->Branch( "L2_mu4_MSonly_MB2_noL2_EFFS", &L2_mu4_MSonly_MB2_noL2_EFFS );
	m_tree->Branch( "L2_mu4_MSonly_Trk_Jpsi_loose", &L2_mu4_MSonly_Trk_Jpsi_loose );
	m_tree->Branch( "L2_mu4_MSonly_Trk_Upsi_loose_FS", &L2_mu4_MSonly_Trk_Upsi_loose_FS );
	m_tree->Branch( "L2_mu4_MSonly_cosmic", &L2_mu4_MSonly_cosmic );
	m_tree->Branch( "L2_mu4_MSonly_firstempty", &L2_mu4_MSonly_firstempty );
	m_tree->Branch( "L2_mu4_MV", &L2_mu4_MV );
	m_tree->Branch( "L2_mu4_NoIDTrkCut", &L2_mu4_NoIDTrkCut );
	m_tree->Branch( "L2_mu4_SiTrk", &L2_mu4_SiTrk );
	m_tree->Branch( "L2_mu4_Trk_Jpsi_loose", &L2_mu4_Trk_Jpsi_loose );
	m_tree->Branch( "L2_mu4_Trk_Upsi_loose_FS", &L2_mu4_Trk_Upsi_loose_FS );
	m_tree->Branch( "L2_mu4_comm", &L2_mu4_comm );
	m_tree->Branch( "L2_mu4_comm_MSonly", &L2_mu4_comm_MSonly );
	m_tree->Branch( "L2_mu4_comm_MSonly_cosmic", &L2_mu4_comm_MSonly_cosmic );
	m_tree->Branch( "L2_mu4_comm_MSonly_firstempty", &L2_mu4_comm_MSonly_firstempty );
	m_tree->Branch( "L2_mu4_comm_cosmic", &L2_mu4_comm_cosmic );
	m_tree->Branch( "L2_mu4_comm_firstempty", &L2_mu4_comm_firstempty );
	m_tree->Branch( "L2_mu4_cosmic", &L2_mu4_cosmic );
	m_tree->Branch( "L2_mu4_firstempty", &L2_mu4_firstempty );
	m_tree->Branch( "L2_mu4_j10_matched", &L2_mu4_j10_matched );
	m_tree->Branch( "L2_mu4_j20_matched", &L2_mu4_j20_matched );
	m_tree->Branch( "L2_mu4_j5_matched", &L2_mu4_j5_matched );
	m_tree->Branch( "L2_mu4_mu6", &L2_mu4_mu6 );
	m_tree->Branch( "L2_mu4_muCombTag", &L2_mu4_muCombTag );
	m_tree->Branch( "L2_mu4_muCombTag_SiTrk", &L2_mu4_muCombTag_SiTrk );
	m_tree->Branch( "L2_mu4_passHLT", &L2_mu4_passHLT );
	m_tree->Branch( "L2_mu4_tile", &L2_mu4_tile );
	m_tree->Branch( "L2_mu4_tile_SiTrk", &L2_mu4_tile_SiTrk );
	m_tree->Branch( "L2_mu4_trod", &L2_mu4_trod );
	m_tree->Branch( "L2_mu4_trod_SiTrk", &L2_mu4_trod_SiTrk );
	m_tree->Branch( "L2_mu4_unpaired", &L2_mu4_unpaired );
	m_tree->Branch( "L2_mu4mu6_DiMu", &L2_mu4mu6_DiMu );
	m_tree->Branch( "L2_mu6", &L2_mu6 );
	m_tree->Branch( "L2_mu6_DiMu", &L2_mu6_DiMu );
	m_tree->Branch( "L2_mu6_DiMu_FS", &L2_mu6_DiMu_FS );
	m_tree->Branch( "L2_mu6_DiMu_FS_noOS", &L2_mu6_DiMu_FS_noOS );
	m_tree->Branch( "L2_mu6_DsPhiPi", &L2_mu6_DsPhiPi );
	m_tree->Branch( "L2_mu6_Jpsie5e3", &L2_mu6_Jpsie5e3 );
	m_tree->Branch( "L2_mu6_Jpsie5e3_FS", &L2_mu6_Jpsie5e3_FS );
	m_tree->Branch( "L2_mu6_Jpsie5e3_SiTrk", &L2_mu6_Jpsie5e3_SiTrk );
	m_tree->Branch( "L2_mu6_Jpsie5e3_SiTrk_FS", &L2_mu6_Jpsie5e3_SiTrk_FS );
	m_tree->Branch( "L2_mu6_MG", &L2_mu6_MG );
	m_tree->Branch( "L2_mu6_MSonly", &L2_mu6_MSonly );
	m_tree->Branch( "L2_mu6_MSonly_cosmic", &L2_mu6_MSonly_cosmic );
	m_tree->Branch( "L2_mu6_MSonly_firstempty", &L2_mu6_MSonly_firstempty );
	m_tree->Branch( "L2_mu6_MSonly_unpaired", &L2_mu6_MSonly_unpaired );
	m_tree->Branch( "L2_mu6_SiTrk", &L2_mu6_SiTrk );
	m_tree->Branch( "L2_mu6_Trk_Jpsi_loose", &L2_mu6_Trk_Jpsi_loose );
	m_tree->Branch( "L2_mu6_Trk_Jpsi_loose_FS", &L2_mu6_Trk_Jpsi_loose_FS );
	m_tree->Branch( "L2_mu6_Trk_Upsi_loose_FS", &L2_mu6_Trk_Upsi_loose_FS );
	m_tree->Branch( "L2_mu6_cosmic", &L2_mu6_cosmic );
	m_tree->Branch( "L2_mu6_firstempty", &L2_mu6_firstempty );
	m_tree->Branch( "L2_mu6_muCombTag", &L2_mu6_muCombTag );
	m_tree->Branch( "L2_mu6_muCombTag_SiTrk", &L2_mu6_muCombTag_SiTrk );
	m_tree->Branch( "L2_mu6_passHLT", &L2_mu6_passHLT );
	m_tree->Branch( "L2_mu6_unpaired", &L2_mu6_unpaired );
	

	// muon_staco
	mu_staco_E = new vector<float>;
	mu_staco_px = new vector<float>;
	mu_staco_py = new vector<float>;
	mu_staco_pz = new vector<float>;
	mu_staco_m = new vector<float>;
	mu_staco_charge = new vector<float>;
	mu_staco_pt = new vector<float>;
	mu_staco_eta = new vector<float>;
	mu_staco_phi = new vector<float>;
	mu_staco_allauthor = new vector<unsigned short>;
	mu_staco_author = new vector<int>;
	mu_staco_matchchi2 = new vector<float>;
	mu_staco_matchndof = new vector<int>;
	mu_staco_etcone20 = new vector<float>;
	mu_staco_etcone30 = new vector<float>;
	mu_staco_etcone40 = new vector<float>;
	mu_staco_nucone20 = new vector<float>;
	mu_staco_nucone30 = new vector<float>;
	mu_staco_nucone40 = new vector<float>;
	mu_staco_ptcone20 = new vector<float>;
	mu_staco_ptcone30 = new vector<float>;
	mu_staco_ptcone40 = new vector<float>;
	mu_staco_energyLossPar = new vector<float>;
	mu_staco_energyLossErr = new vector<float>;
	mu_staco_bestMatch = new vector<int>;
	mu_staco_isStandAloneMuon = new vector<int>;
	mu_staco_isCombinedMuon = new vector<int>;
	mu_staco_isLowPtReconstructedMuon = new vector<int>;
	mu_staco_d0_exPV = new vector<float>;
	mu_staco_z0_exPV = new vector<float>;
	mu_staco_phi_exPV = new vector<float>;
	mu_staco_theta_exPV = new vector<float>;
	mu_staco_qoverp_exPV = new vector<float>;
	mu_staco_cov_d0_exPV = new vector<float>;
	mu_staco_cov_z0_exPV = new vector<float>;
	mu_staco_cov_phi_exPV = new vector<float>;
	mu_staco_cov_theta_exPV = new vector<float>;
	mu_staco_cov_qoverp_exPV = new vector<float>;
	mu_staco_cov_d0_z0_exPV = new vector<float>;
	mu_staco_cov_d0_phi_exPV = new vector<float>;
	mu_staco_cov_d0_theta_exPV = new vector<float>;
	mu_staco_cov_d0_qoverp_exPV = new vector<float>;
	mu_staco_cov_z0_phi_exPV = new vector<float>;
	mu_staco_cov_z0_theta_exPV = new vector<float>;
	mu_staco_cov_z0_qoverp_exPV = new vector<float>;
	mu_staco_cov_phi_theta_exPV = new vector<float>;
	mu_staco_cov_phi_qoverp_exPV = new vector<float>;
	mu_staco_cov_theta_qoverp_exPV = new vector<float>;
	mu_staco_ms_d0 = new vector<float>;
	mu_staco_ms_z0 = new vector<float>;
	mu_staco_ms_phi = new vector<float>;
	mu_staco_ms_theta = new vector<float>;
	mu_staco_ms_qoverp = new vector<float>;
	mu_staco_id_d0 = new vector<float>;
	mu_staco_id_z0 = new vector<float>;
	mu_staco_id_phi = new vector<float>;
	mu_staco_id_theta = new vector<float>;
	mu_staco_id_qoverp = new vector<float>;
	mu_staco_me_d0 = new vector<float>;
	mu_staco_me_z0 = new vector<float>;
	mu_staco_me_phi = new vector<float>;
	mu_staco_me_theta = new vector<float>;
	mu_staco_me_qoverp = new vector<float>;
	mu_staco_ie_d0 = new vector<float>;
	mu_staco_ie_z0 = new vector<float>;
	mu_staco_ie_phi = new vector<float>;
	mu_staco_ie_theta = new vector<float>;
	mu_staco_ie_qoverp = new vector<float>;
	mu_staco_nBLHits = new vector<int>;
	mu_staco_nPixHits = new vector<int>;
	mu_staco_nSCTHits = new vector<int>;
	mu_staco_nTRTHits = new vector<int>;
	mu_staco_nTRTHighTHits = new vector<int>;
	mu_staco_nBLSharedHits = new vector<int>;
	mu_staco_nPixSharedHits = new vector<int>;
	mu_staco_nPixHoles = new vector<int>;
	mu_staco_nSCTSharedHits = new vector<int>;
	mu_staco_nSCTHoles = new vector<int>;
	mu_staco_nTRTOutliers = new vector<int>;
	mu_staco_nTRTHighTOutliers = new vector<int>;
	mu_staco_nMDTHits = new vector<int>;
	mu_staco_nMDTHoles = new vector<int>;
	mu_staco_nCSCEtaHits = new vector<int>;
	mu_staco_nCSCEtaHoles = new vector<int>;
	mu_staco_nCSCPhiHits = new vector<int>;
	mu_staco_nCSCPhiHoles = new vector<int>;
	mu_staco_nRPCEtaHits = new vector<int>;
	mu_staco_nRPCEtaHoles = new vector<int>;
	mu_staco_nRPCPhiHits = new vector<int>;
	mu_staco_nRPCPhiHoles = new vector<int>;
	mu_staco_nTGCEtaHits = new vector<int>;
	mu_staco_nTGCEtaHoles = new vector<int>;
	mu_staco_nTGCPhiHits = new vector<int>;
	mu_staco_nTGCPhiHoles = new vector<int>;
	mu_staco_nGangedPixels = new vector<int>;
	mu_staco_nOutliersOnTrack = new vector<int>;
	mu_staco_nMDTBIHits = new vector<int>;
	mu_staco_nMDTBMHits = new vector<int>;
	mu_staco_nMDTBOHits = new vector<int>;
	mu_staco_nMDTBEEHits = new vector<int>;
	mu_staco_nMDTBIS78Hits = new vector<int>;
	mu_staco_nMDTEIHits = new vector<int>;
	mu_staco_nMDTEMHits = new vector<int>;
	mu_staco_nMDTEOHits = new vector<int>;
	mu_staco_nMDTEEHits = new vector<int>;
	mu_staco_nRPCLayer1EtaHits = new vector<int>;
	mu_staco_nRPCLayer2EtaHits = new vector<int>;
	mu_staco_nRPCLayer3EtaHits = new vector<int>;
	mu_staco_nRPCLayer1PhiHits = new vector<int>;
	mu_staco_nRPCLayer2PhiHits = new vector<int>;
	mu_staco_nRPCLayer3PhiHits = new vector<int>;
	mu_staco_nTGCLayer1EtaHits = new vector<int>;
	mu_staco_nTGCLayer2EtaHits = new vector<int>;
	mu_staco_nTGCLayer3EtaHits = new vector<int>;
	mu_staco_nTGCLayer4EtaHits = new vector<int>;
	mu_staco_nTGCLayer1PhiHits = new vector<int>;
	mu_staco_nTGCLayer2PhiHits = new vector<int>;
	mu_staco_nTGCLayer3PhiHits = new vector<int>;
	mu_staco_nTGCLayer4PhiHits = new vector<int>;
	mu_staco_barrelSectors = new vector<int>;
	mu_staco_endcapSectors = new vector<int>;
	mu_staco_trackd0 = new vector<float>;
	mu_staco_trackz0 = new vector<float>;
	mu_staco_trackphi = new vector<float>;
	mu_staco_tracktheta = new vector<float>;
	mu_staco_trackqoverp = new vector<float>;
	mu_staco_trackcov_d0 = new vector<float>;
	mu_staco_trackcov_z0 = new vector<float>;
	mu_staco_trackcov_phi = new vector<float>;
	mu_staco_trackcov_theta = new vector<float>;
	mu_staco_trackcov_qoverp = new vector<float>;
	mu_staco_trackcov_d0_z0 = new vector<float>;
	mu_staco_trackcov_d0_phi = new vector<float>;
	mu_staco_trackcov_d0_theta = new vector<float>;
	mu_staco_trackcov_d0_qoverp = new vector<float>;
	mu_staco_trackcov_z0_phi = new vector<float>;
	mu_staco_trackcov_z0_theta = new vector<float>;
	mu_staco_trackcov_z0_qoverp = new vector<float>;
	mu_staco_trackcov_phi_theta = new vector<float>;
	mu_staco_trackcov_phi_qoverp = new vector<float>;
	mu_staco_trackcov_theta_qoverp = new vector<float>;
	mu_staco_trackfitchi2 = new vector<float>;
	mu_staco_trackfitndof = new vector<int>;
	mu_staco_hastrack = new vector<int>;
	mu_staco_EF_dr = new vector<float>;
	mu_staco_EF_cb_eta = new vector<float>;
	mu_staco_EF_cb_phi = new vector<float>;
	mu_staco_EF_cb_pt = new vector<float>;
	mu_staco_EF_ms_eta = new vector<float>;
	mu_staco_EF_ms_phi = new vector<float>;
	mu_staco_EF_ms_pt = new vector<float>;
	mu_staco_EF_me_eta = new vector<float>;
	mu_staco_EF_me_phi = new vector<float>;
	mu_staco_EF_me_pt = new vector<float>;
	mu_staco_EF_matched = new vector<int>;
	mu_staco_L2CB_dr = new vector<float>;
	mu_staco_L2CB_pt = new vector<float>;
	mu_staco_L2CB_eta = new vector<float>;
	mu_staco_L2CB_phi = new vector<float>;
	mu_staco_L2CB_id_pt = new vector<float>;
	mu_staco_L2CB_ms_pt = new vector<float>;
	mu_staco_L2CB_nPixHits = new vector<int>;
	mu_staco_L2CB_nSCTHits = new vector<int>;
	mu_staco_L2CB_nTRTHits = new vector<int>;
	mu_staco_L2CB_nTRTHighTHits = new vector<int>;
	mu_staco_L2CB_matched = new vector<int>;
	mu_staco_L1_dr = new vector<float>;
	mu_staco_L1_pt = new vector<float>;
	mu_staco_L1_eta = new vector<float>;
	mu_staco_L1_phi = new vector<float>;
	mu_staco_L1_thrNumber = new vector<short>;
	mu_staco_L1_RoINumber = new vector<short>;
	mu_staco_L1_sectorAddress = new vector<short>;
	mu_staco_L1_firstCandidate = new vector<int>;
	mu_staco_L1_moreCandInRoI = new vector<int>;
	mu_staco_L1_moreCandInSector = new vector<int>;
	mu_staco_L1_source = new vector<short>;
	mu_staco_L1_hemisphere = new vector<short>;
	mu_staco_L1_matched = new vector<int>;
	
	m_tree->Branch( "mu_staco_n", &mu_staco_n );
	m_tree->Branch( "mu_staco_E", &mu_staco_E);
	m_tree->Branch( "mu_staco_px", &mu_staco_px );
	m_tree->Branch( "mu_staco_py", &mu_staco_py );
	m_tree->Branch( "mu_staco_pz", &mu_staco_pz );
	m_tree->Branch( "mu_staco_m", &mu_staco_m );
	m_tree->Branch( "mu_staco_charge", &mu_staco_charge );
	m_tree->Branch( "mu_staco_pt", &mu_staco_pt );
	m_tree->Branch( "mu_staco_eta", &mu_staco_eta );
	m_tree->Branch( "mu_staco_phi", &mu_staco_phi );
	m_tree->Branch( "mu_staco_allauthor", &mu_staco_allauthor );
	m_tree->Branch( "mu_staco_author", &mu_staco_author );
	m_tree->Branch( "mu_staco_matchchi2", &mu_staco_matchchi2 );
	m_tree->Branch( "mu_staco_matchndof", &mu_staco_matchndof );
	m_tree->Branch( "mu_staco_etcone20", &mu_staco_etcone20 );
	m_tree->Branch( "mu_staco_etcone30", &mu_staco_etcone30 );
	m_tree->Branch( "mu_staco_etcone40", &mu_staco_etcone40 );
	m_tree->Branch( "mu_staco_nucone20", &mu_staco_nucone20 );
	m_tree->Branch( "mu_staco_nucone30", &mu_staco_nucone30 );
	m_tree->Branch( "mu_staco_nucone40", &mu_staco_nucone40 );
	m_tree->Branch( "mu_staco_ptcone20", &mu_staco_ptcone20 );
	m_tree->Branch( "mu_staco_ptcone30", &mu_staco_ptcone30 );
	m_tree->Branch( "mu_staco_ptcone40", &mu_staco_ptcone40 );
	m_tree->Branch( "mu_staco_energyLossPar", &mu_staco_energyLossPar );
	m_tree->Branch( "mu_staco_energyLossErr", &mu_staco_energyLossErr );
	m_tree->Branch( "mu_staco_bestMatch", &mu_staco_bestMatch );
	m_tree->Branch( "mu_staco_isStandAloneMuon", &mu_staco_isStandAloneMuon );
	m_tree->Branch( "mu_staco_isCombinedMuon", &mu_staco_isCombinedMuon );
	m_tree->Branch( "mu_staco_isLowPtReconstructedMuon", &mu_staco_isLowPtReconstructedMuon );
	m_tree->Branch( "mu_staco_d0_exPV", &mu_staco_d0_exPV );
	m_tree->Branch( "mu_staco_z0_exPV", &mu_staco_z0_exPV );
	m_tree->Branch( "mu_staco_phi_exPV", &mu_staco_phi_exPV );
	m_tree->Branch( "mu_staco_theta_exPV", &mu_staco_theta_exPV );
	m_tree->Branch( "mu_staco_qoverp_exPV", &mu_staco_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_d0_exPV", &mu_staco_cov_d0_exPV );
	m_tree->Branch( "mu_staco_cov_z0_exPV", &mu_staco_cov_z0_exPV );
	m_tree->Branch( "mu_staco_cov_phi_exPV", &mu_staco_cov_phi_exPV );
	m_tree->Branch( "mu_staco_cov_theta_exPV", &mu_staco_cov_theta_exPV );
	m_tree->Branch( "mu_staco_cov_qoverp_exPV", &mu_staco_cov_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_d0_z0_exPV", &mu_staco_cov_d0_z0_exPV );
	m_tree->Branch( "mu_staco_cov_d0_phi_exPV", &mu_staco_cov_d0_phi_exPV );
	m_tree->Branch( "mu_staco_cov_d0_theta_exPV", &mu_staco_cov_d0_theta_exPV );
	m_tree->Branch( "mu_staco_cov_d0_qoverp_exPV", &mu_staco_cov_d0_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_z0_phi_exPV", &mu_staco_cov_z0_phi_exPV );
	m_tree->Branch( "mu_staco_cov_z0_theta_exPV", &mu_staco_cov_z0_theta_exPV );
	m_tree->Branch( "mu_staco_cov_z0_qoverp_exPV", &mu_staco_cov_z0_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_phi_theta_exPV", &mu_staco_cov_phi_theta_exPV );
	m_tree->Branch( "mu_staco_cov_phi_qoverp_exPV", &mu_staco_cov_phi_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_theta_qoverp_exPV", &mu_staco_cov_theta_qoverp_exPV );
	m_tree->Branch( "mu_staco_ms_d0", &mu_staco_ms_d0 );
	m_tree->Branch( "mu_staco_ms_z0", &mu_staco_ms_z0 );
	m_tree->Branch( "mu_staco_ms_phi", &mu_staco_ms_phi );
	m_tree->Branch( "mu_staco_ms_theta", &mu_staco_ms_theta );
	m_tree->Branch( "mu_staco_ms_qoverp", &mu_staco_ms_qoverp );
	m_tree->Branch( "mu_staco_id_d0", &mu_staco_id_d0 );
	m_tree->Branch( "mu_staco_id_z0", &mu_staco_id_z0 );
	m_tree->Branch( "mu_staco_id_phi", &mu_staco_id_phi );
	m_tree->Branch( "mu_staco_id_theta", &mu_staco_id_theta );
	m_tree->Branch( "mu_staco_id_qoverp", &mu_staco_id_qoverp );
	m_tree->Branch( "mu_staco_me_d0", &mu_staco_me_d0 );
	m_tree->Branch( "mu_staco_me_z0", &mu_staco_me_z0 );
	m_tree->Branch( "mu_staco_me_phi", &mu_staco_me_phi );
	m_tree->Branch( "mu_staco_me_theta", &mu_staco_me_theta );
	m_tree->Branch( "mu_staco_me_qoverp", &mu_staco_me_qoverp );
	m_tree->Branch( "mu_staco_ie_d0", &mu_staco_ie_d0 );
	m_tree->Branch( "mu_staco_ie_z0", &mu_staco_ie_z0 );
	m_tree->Branch( "mu_staco_ie_phi", &mu_staco_ie_phi );
	m_tree->Branch( "mu_staco_ie_theta", &mu_staco_ie_theta );
	m_tree->Branch( "mu_staco_ie_qoverp", &mu_staco_ie_qoverp );
	m_tree->Branch( "mu_staco_nBLHits", &mu_staco_nBLHits );
	m_tree->Branch( "mu_staco_nPixHits", &mu_staco_nPixHits );
	m_tree->Branch( "mu_staco_nSCTHits", &mu_staco_nSCTHits );
	m_tree->Branch( "mu_staco_nTRTHits", &mu_staco_nTRTHits );
	m_tree->Branch( "mu_staco_nTRTHighTHits", &mu_staco_nTRTHighTHits );
	m_tree->Branch( "mu_staco_nBLSharedHits", &mu_staco_nBLSharedHits );
	m_tree->Branch( "mu_staco_nPixSharedHits", &mu_staco_nPixSharedHits );
	m_tree->Branch( "mu_staco_nPixHoles", &mu_staco_nPixHoles );
	m_tree->Branch( "mu_staco_nSCTSharedHits", &mu_staco_nSCTSharedHits );
	m_tree->Branch( "mu_staco_nSCTHoles", &mu_staco_nSCTHoles );
	m_tree->Branch( "mu_staco_nTRTOutliers", &mu_staco_nTRTOutliers );
	m_tree->Branch( "mu_staco_nTRTHighTOutliers", &mu_staco_nTRTHighTOutliers );
	m_tree->Branch( "mu_staco_nMDTHits", &mu_staco_nMDTHits );
	m_tree->Branch( "mu_staco_nMDTHoles", &mu_staco_nMDTHoles );
	m_tree->Branch( "mu_staco_nCSCEtaHits", &mu_staco_nCSCEtaHits );
	m_tree->Branch( "mu_staco_nCSCEtaHoles", &mu_staco_nCSCEtaHoles );
	m_tree->Branch( "mu_staco_nCSCPhiHits", &mu_staco_nCSCPhiHits );
	m_tree->Branch( "mu_staco_nCSCPhiHoles", &mu_staco_nCSCPhiHoles );
	m_tree->Branch( "mu_staco_nRPCEtaHits", &mu_staco_nRPCEtaHits );
	m_tree->Branch( "mu_staco_nRPCEtaHoles", &mu_staco_nRPCEtaHoles );
	m_tree->Branch( "mu_staco_nRPCPhiHits", &mu_staco_nRPCPhiHits );
	m_tree->Branch( "mu_staco_nRPCPhiHoles", &mu_staco_nRPCPhiHoles );
	m_tree->Branch( "mu_staco_nTGCEtaHits", &mu_staco_nTGCEtaHits );
	m_tree->Branch( "mu_staco_nTGCEtaHoles", &mu_staco_nTGCEtaHoles );
	m_tree->Branch( "mu_staco_nTGCPhiHits", &mu_staco_nTGCPhiHits );
	m_tree->Branch( "mu_staco_nTGCPhiHoles", &mu_staco_nTGCPhiHoles );
	m_tree->Branch( "mu_staco_nGangedPixels", &mu_staco_nGangedPixels );
	m_tree->Branch( "mu_staco_nOutliersOnTrack", &mu_staco_nOutliersOnTrack );
	m_tree->Branch( "mu_staco_nMDTBIHits", &mu_staco_nMDTBIHits );
	m_tree->Branch( "mu_staco_nMDTBMHits", &mu_staco_nMDTBMHits );
	m_tree->Branch( "mu_staco_nMDTBOHits", &mu_staco_nMDTBOHits );
	m_tree->Branch( "mu_staco_nMDTBEEHits", &mu_staco_nMDTBEEHits );
	m_tree->Branch( "mu_staco_nMDTBIS78Hits", &mu_staco_nMDTBIS78Hits );
	m_tree->Branch( "mu_staco_nMDTEIHits", &mu_staco_nMDTEIHits );
	m_tree->Branch( "mu_staco_nMDTEMHits", &mu_staco_nMDTEMHits );
	m_tree->Branch( "mu_staco_nMDTEOHits", &mu_staco_nMDTEOHits );
	m_tree->Branch( "mu_staco_nMDTEEHits", &mu_staco_nMDTEEHits );
	m_tree->Branch( "mu_staco_nRPCLayer1EtaHits", &mu_staco_nRPCLayer1EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer2EtaHits", &mu_staco_nRPCLayer2EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer3EtaHits", &mu_staco_nRPCLayer3EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer1PhiHits", &mu_staco_nRPCLayer1PhiHits );
	m_tree->Branch( "mu_staco_nRPCLayer2PhiHits", &mu_staco_nRPCLayer2PhiHits );
	m_tree->Branch( "mu_staco_nRPCLayer3PhiHits", &mu_staco_nRPCLayer3PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer1EtaHits", &mu_staco_nTGCLayer1EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer2EtaHits", &mu_staco_nTGCLayer2EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer3EtaHits", &mu_staco_nTGCLayer3EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer4EtaHits", &mu_staco_nTGCLayer4EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer1PhiHits", &mu_staco_nTGCLayer1PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer2PhiHits", &mu_staco_nTGCLayer2PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer3PhiHits", &mu_staco_nTGCLayer3PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer4PhiHits", &mu_staco_nTGCLayer4PhiHits );
	m_tree->Branch( "mu_staco_barrelSectors", &mu_staco_barrelSectors );
	m_tree->Branch( "mu_staco_endcapSectors", &mu_staco_endcapSectors );
	m_tree->Branch( "mu_staco_trackd0", &mu_staco_trackd0 );
	m_tree->Branch( "mu_staco_trackz0", &mu_staco_trackz0 );
	m_tree->Branch( "mu_staco_trackphi", &mu_staco_trackphi );
	m_tree->Branch( "mu_staco_tracktheta", &mu_staco_tracktheta );
	m_tree->Branch( "mu_staco_trackqoverp", &mu_staco_trackqoverp );
	m_tree->Branch( "mu_staco_trackcov_d0", &mu_staco_trackcov_d0 );
	m_tree->Branch( "mu_staco_trackcov_z0", &mu_staco_trackcov_z0 );
	m_tree->Branch( "mu_staco_trackcov_phi", &mu_staco_trackcov_phi );
	m_tree->Branch( "mu_staco_trackcov_theta", &mu_staco_trackcov_theta );
	m_tree->Branch( "mu_staco_trackcov_qoverp", &mu_staco_trackcov_qoverp );
	m_tree->Branch( "mu_staco_trackcov_d0_z0", &mu_staco_trackcov_d0_z0 );
	m_tree->Branch( "mu_staco_trackcov_d0_phi", &mu_staco_trackcov_d0_phi );
	m_tree->Branch( "mu_staco_trackcov_d0_theta", &mu_staco_trackcov_d0_theta );
	m_tree->Branch( "mu_staco_trackcov_d0_qoverp", &mu_staco_trackcov_d0_qoverp );
	m_tree->Branch( "mu_staco_trackcov_z0_phi", &mu_staco_trackcov_z0_phi );
	m_tree->Branch( "mu_staco_trackcov_z0_theta", &mu_staco_trackcov_z0_theta );
	m_tree->Branch( "mu_staco_trackcov_z0_qoverp", &mu_staco_trackcov_z0_qoverp );
	m_tree->Branch( "mu_staco_trackcov_phi_theta", &mu_staco_trackcov_phi_theta );
	m_tree->Branch( "mu_staco_trackcov_phi_qoverp", &mu_staco_trackcov_phi_qoverp );
	m_tree->Branch( "mu_staco_trackcov_theta_qoverp", &mu_staco_trackcov_theta_qoverp );
	m_tree->Branch( "mu_staco_trackfitchi2", &mu_staco_trackfitchi2 );
	m_tree->Branch( "mu_staco_trackfitndof", &mu_staco_trackfitndof );
	m_tree->Branch( "mu_staco_hastrack", &mu_staco_hastrack );
	m_tree->Branch( "mu_staco_EF_dr", &mu_staco_EF_dr );
	m_tree->Branch( "mu_staco_EF_cb_eta", &mu_staco_EF_cb_eta );
	m_tree->Branch( "mu_staco_EF_cb_phi", &mu_staco_EF_cb_phi );
	m_tree->Branch( "mu_staco_EF_cb_pt", &mu_staco_EF_cb_pt );
	m_tree->Branch( "mu_staco_EF_ms_eta", &mu_staco_EF_ms_eta );
	m_tree->Branch( "mu_staco_EF_ms_phi", &mu_staco_EF_ms_phi );
	m_tree->Branch( "mu_staco_EF_ms_pt", &mu_staco_EF_ms_pt );
	m_tree->Branch( "mu_staco_EF_me_eta", &mu_staco_EF_me_eta );
	m_tree->Branch( "mu_staco_EF_me_phi", &mu_staco_EF_me_phi );
	m_tree->Branch( "mu_staco_EF_me_pt", &mu_staco_EF_me_pt );
	m_tree->Branch( "mu_staco_EF_matched", &mu_staco_EF_matched );
	m_tree->Branch( "mu_staco_L2CB_dr", &mu_staco_L2CB_dr );
	m_tree->Branch( "mu_staco_L2CB_pt", &mu_staco_L2CB_pt );
	m_tree->Branch( "mu_staco_L2CB_eta", &mu_staco_L2CB_eta );
	m_tree->Branch( "mu_staco_L2CB_phi", &mu_staco_L2CB_phi );
	m_tree->Branch( "mu_staco_L2CB_id_pt", &mu_staco_L2CB_id_pt );
	m_tree->Branch( "mu_staco_L2CB_ms_pt", &mu_staco_L2CB_ms_pt );
	m_tree->Branch( "mu_staco_L2CB_nPixHits", &mu_staco_L2CB_nPixHits );
	m_tree->Branch( "mu_staco_L2CB_nSCTHits", &mu_staco_L2CB_nSCTHits );
	m_tree->Branch( "mu_staco_L2CB_nTRTHits", &mu_staco_L2CB_nTRTHits );
	m_tree->Branch( "mu_staco_L2CB_nTRTHighTHits", &mu_staco_L2CB_nTRTHighTHits );
	m_tree->Branch( "mu_staco_L2CB_matched", &mu_staco_L2CB_matched );
	m_tree->Branch( "mu_staco_L1_dr", &mu_staco_L1_dr );
	m_tree->Branch( "mu_staco_L1_pt", &mu_staco_L1_pt );
	m_tree->Branch( "mu_staco_L1_eta", &mu_staco_L1_eta );
	m_tree->Branch( "mu_staco_L1_phi", &mu_staco_L1_phi );
	m_tree->Branch( "mu_staco_L1_thrNumber", &mu_staco_L1_thrNumber );
	m_tree->Branch( "mu_staco_L1_RoINumber", &mu_staco_L1_RoINumber );
	m_tree->Branch( "mu_staco_L1_sectorAddress", &mu_staco_L1_sectorAddress );
	m_tree->Branch( "mu_staco_L1_firstCandidate", &mu_staco_L1_firstCandidate );
	m_tree->Branch( "mu_staco_L1_moreCandInRoI", &mu_staco_L1_moreCandInRoI );
	m_tree->Branch( "mu_staco_L1_moreCandInSector", &mu_staco_L1_moreCandInSector );
	m_tree->Branch( "mu_staco_L1_source", &mu_staco_L1_source );
	m_tree->Branch( "mu_staco_L1_hemisphere", &mu_staco_L1_hemisphere );
	m_tree->Branch( "mu_staco_L1_matched", &mu_staco_L1_matched );
	
	
	// muon_muid
	mu_muid_E = new vector<float>;
	mu_muid_px = new vector<float>;
	mu_muid_py = new vector<float>;
	mu_muid_pz = new vector<float>;
	mu_muid_m = new vector<float>;
	mu_muid_charge = new vector<float>;
	mu_muid_pt = new vector<float>;
	mu_muid_eta = new vector<float>;
	mu_muid_phi = new vector<float>;
	mu_muid_allauthor = new vector<unsigned short>;
	mu_muid_author = new vector<int>;
	mu_muid_matchchi2 = new vector<float>;
	mu_muid_matchndof = new vector<int>;
	mu_muid_etcone20 = new vector<float>;
	mu_muid_etcone30 = new vector<float>;
	mu_muid_etcone40 = new vector<float>;
	mu_muid_nucone20 = new vector<float>;
	mu_muid_nucone30 = new vector<float>;
	mu_muid_nucone40 = new vector<float>;
	mu_muid_ptcone20 = new vector<float>;
	mu_muid_ptcone30 = new vector<float>;
	mu_muid_ptcone40 = new vector<float>;
	mu_muid_energyLossPar = new vector<float>;
	mu_muid_energyLossErr = new vector<float>;
	mu_muid_bestMatch = new vector<int>;
	mu_muid_isStandAloneMuon = new vector<int>;
	mu_muid_isCombinedMuon = new vector<int>;
	mu_muid_isLowPtReconstructedMuon = new vector<int>;
	mu_muid_d0_exPV = new vector<float>;
	mu_muid_z0_exPV = new vector<float>;
	mu_muid_phi_exPV = new vector<float>;
	mu_muid_theta_exPV = new vector<float>;
	mu_muid_qoverp_exPV = new vector<float>;
	mu_muid_cov_d0_exPV = new vector<float>;
	mu_muid_cov_z0_exPV = new vector<float>;
	mu_muid_cov_phi_exPV = new vector<float>;
	mu_muid_cov_theta_exPV = new vector<float>;
	mu_muid_cov_qoverp_exPV = new vector<float>;
	mu_muid_cov_d0_z0_exPV = new vector<float>;
	mu_muid_cov_d0_phi_exPV = new vector<float>;
	mu_muid_cov_d0_theta_exPV = new vector<float>;
	mu_muid_cov_d0_qoverp_exPV = new vector<float>;
	mu_muid_cov_z0_phi_exPV = new vector<float>;
	mu_muid_cov_z0_theta_exPV = new vector<float>;
	mu_muid_cov_z0_qoverp_exPV = new vector<float>;
	mu_muid_cov_phi_theta_exPV = new vector<float>;
	mu_muid_cov_phi_qoverp_exPV = new vector<float>;
	mu_muid_cov_theta_qoverp_exPV = new vector<float>;
	mu_muid_ms_d0 = new vector<float>;
	mu_muid_ms_z0 = new vector<float>;
	mu_muid_ms_phi = new vector<float>;
	mu_muid_ms_theta = new vector<float>;
	mu_muid_ms_qoverp = new vector<float>;
	mu_muid_id_d0 = new vector<float>;
	mu_muid_id_z0 = new vector<float>;
	mu_muid_id_phi = new vector<float>;
	mu_muid_id_theta = new vector<float>;
	mu_muid_id_qoverp = new vector<float>;
	mu_muid_me_d0 = new vector<float>;
	mu_muid_me_z0 = new vector<float>;
	mu_muid_me_phi = new vector<float>;
	mu_muid_me_theta = new vector<float>;
	mu_muid_me_qoverp = new vector<float>;
	mu_muid_ie_d0 = new vector<float>;
	mu_muid_ie_z0 = new vector<float>;
	mu_muid_ie_phi = new vector<float>;
	mu_muid_ie_theta = new vector<float>;
	mu_muid_ie_qoverp = new vector<float>;
	mu_muid_nBLHits = new vector<int>;
	mu_muid_nPixHits = new vector<int>;
	mu_muid_nSCTHits = new vector<int>;
	mu_muid_nTRTHits = new vector<int>;
	mu_muid_nTRTHighTHits = new vector<int>;
	mu_muid_nBLSharedHits = new vector<int>;
	mu_muid_nPixSharedHits = new vector<int>;
	mu_muid_nPixHoles = new vector<int>;
	mu_muid_nSCTSharedHits = new vector<int>;
	mu_muid_nSCTHoles = new vector<int>;
	mu_muid_nTRTOutliers = new vector<int>;
	mu_muid_nTRTHighTOutliers = new vector<int>;
	mu_muid_nMDTHits = new vector<int>;
	mu_muid_nMDTHoles = new vector<int>;
	mu_muid_nCSCEtaHits = new vector<int>;
	mu_muid_nCSCEtaHoles = new vector<int>;
	mu_muid_nCSCPhiHits = new vector<int>;
	mu_muid_nCSCPhiHoles = new vector<int>;
	mu_muid_nRPCEtaHits = new vector<int>;
	mu_muid_nRPCEtaHoles = new vector<int>;
	mu_muid_nRPCPhiHits = new vector<int>;
	mu_muid_nRPCPhiHoles = new vector<int>;
	mu_muid_nTGCEtaHits = new vector<int>;
	mu_muid_nTGCEtaHoles = new vector<int>;
	mu_muid_nTGCPhiHits = new vector<int>;
	mu_muid_nTGCPhiHoles = new vector<int>;
	mu_muid_nGangedPixels = new vector<int>;
	mu_muid_nOutliersOnTrack = new vector<int>;
	mu_muid_nMDTBIHits = new vector<int>;
	mu_muid_nMDTBMHits = new vector<int>;
	mu_muid_nMDTBOHits = new vector<int>;
	mu_muid_nMDTBEEHits = new vector<int>;
	mu_muid_nMDTBIS78Hits = new vector<int>;
	mu_muid_nMDTEIHits = new vector<int>;
	mu_muid_nMDTEMHits = new vector<int>;
	mu_muid_nMDTEOHits = new vector<int>;
	mu_muid_nMDTEEHits = new vector<int>;
	mu_muid_nRPCLayer1EtaHits = new vector<int>;
	mu_muid_nRPCLayer2EtaHits = new vector<int>;
	mu_muid_nRPCLayer3EtaHits = new vector<int>;
	mu_muid_nRPCLayer1PhiHits = new vector<int>;
	mu_muid_nRPCLayer2PhiHits = new vector<int>;
	mu_muid_nRPCLayer3PhiHits = new vector<int>;
	mu_muid_nTGCLayer1EtaHits = new vector<int>;
	mu_muid_nTGCLayer2EtaHits = new vector<int>;
	mu_muid_nTGCLayer3EtaHits = new vector<int>;
	mu_muid_nTGCLayer4EtaHits = new vector<int>;
	mu_muid_nTGCLayer1PhiHits = new vector<int>;
	mu_muid_nTGCLayer2PhiHits = new vector<int>;
	mu_muid_nTGCLayer3PhiHits = new vector<int>;
	mu_muid_nTGCLayer4PhiHits = new vector<int>;
	mu_muid_barrelSectors = new vector<int>;
	mu_muid_endcapSectors = new vector<int>;
	mu_muid_trackd0 = new vector<float>;
	mu_muid_trackz0 = new vector<float>;
	mu_muid_trackphi = new vector<float>;
	mu_muid_tracktheta = new vector<float>;
	mu_muid_trackqoverp = new vector<float>;
	mu_muid_trackcov_d0 = new vector<float>;
	mu_muid_trackcov_z0 = new vector<float>;
	mu_muid_trackcov_phi = new vector<float>;
	mu_muid_trackcov_theta = new vector<float>;
	mu_muid_trackcov_qoverp = new vector<float>;
	mu_muid_trackcov_d0_z0 = new vector<float>;
	mu_muid_trackcov_d0_phi = new vector<float>;
	mu_muid_trackcov_d0_theta = new vector<float>;
	mu_muid_trackcov_d0_qoverp = new vector<float>;
	mu_muid_trackcov_z0_phi = new vector<float>;
	mu_muid_trackcov_z0_theta = new vector<float>;
	mu_muid_trackcov_z0_qoverp = new vector<float>;
	mu_muid_trackcov_phi_theta = new vector<float>;
	mu_muid_trackcov_phi_qoverp = new vector<float>;
	mu_muid_trackcov_theta_qoverp = new vector<float>;
	mu_muid_trackfitchi2 = new vector<float>;
	mu_muid_trackfitndof = new vector<int>;
	mu_muid_hastrack = new vector<int>;
	mu_muid_EF_dr = new vector<float>;
	mu_muid_EF_cb_eta = new vector<float>;
	mu_muid_EF_cb_phi = new vector<float>;
	mu_muid_EF_cb_pt = new vector<float>;
	mu_muid_EF_ms_eta = new vector<float>;
	mu_muid_EF_ms_phi = new vector<float>;
	mu_muid_EF_ms_pt = new vector<float>;
	mu_muid_EF_me_eta = new vector<float>;
	mu_muid_EF_me_phi = new vector<float>;
	mu_muid_EF_me_pt = new vector<float>;
	mu_muid_EF_matched = new vector<int>;
	mu_muid_L2CB_dr = new vector<float>;
	mu_muid_L2CB_pt = new vector<float>;
	mu_muid_L2CB_eta = new vector<float>;
	mu_muid_L2CB_phi = new vector<float>;
	mu_muid_L2CB_id_pt = new vector<float>;
	mu_muid_L2CB_ms_pt = new vector<float>;
	mu_muid_L2CB_nPixHits = new vector<int>;
	mu_muid_L2CB_nSCTHits = new vector<int>;
	mu_muid_L2CB_nTRTHits = new vector<int>;
	mu_muid_L2CB_nTRTHighTHits = new vector<int>;
	mu_muid_L2CB_matched = new vector<int>;
	mu_muid_L1_dr = new vector<float>;
	mu_muid_L1_pt = new vector<float>;
	mu_muid_L1_eta = new vector<float>;
	mu_muid_L1_phi = new vector<float>;
	mu_muid_L1_thrNumber = new vector<short>;
	mu_muid_L1_RoINumber = new vector<short>;
	mu_muid_L1_sectorAddress = new vector<short>;
	mu_muid_L1_firstCandidate = new vector<int>;
	mu_muid_L1_moreCandInRoI = new vector<int>;
	mu_muid_L1_moreCandInSector = new vector<int>;
	mu_muid_L1_source = new vector<short>;
	mu_muid_L1_hemisphere = new vector<short>;
	mu_muid_L1_matched = new vector<int>;
	
	m_tree->Branch( "mu_muid_n", &mu_muid_n );
	m_tree->Branch( "mu_muid_E", &mu_muid_E);
	m_tree->Branch( "mu_muid_px", &mu_muid_px );
	m_tree->Branch( "mu_muid_py", &mu_muid_py );
	m_tree->Branch( "mu_muid_pz", &mu_muid_pz );
	m_tree->Branch( "mu_muid_m", &mu_muid_m );
	m_tree->Branch( "mu_muid_charge", &mu_muid_charge );
	m_tree->Branch( "mu_muid_pt", &mu_muid_pt );
	m_tree->Branch( "mu_muid_eta", &mu_muid_eta );
	m_tree->Branch( "mu_muid_phi", &mu_muid_phi );
	m_tree->Branch( "mu_muid_allauthor", &mu_muid_allauthor );
	m_tree->Branch( "mu_muid_author", &mu_muid_author );
	m_tree->Branch( "mu_muid_matchchi2", &mu_muid_matchchi2 );
	m_tree->Branch( "mu_muid_matchndof", &mu_muid_matchndof );
	m_tree->Branch( "mu_muid_etcone20", &mu_muid_etcone20 );
	m_tree->Branch( "mu_muid_etcone30", &mu_muid_etcone30 );
	m_tree->Branch( "mu_muid_etcone40", &mu_muid_etcone40 );
	m_tree->Branch( "mu_muid_nucone20", &mu_muid_nucone20 );
	m_tree->Branch( "mu_muid_nucone30", &mu_muid_nucone30 );
	m_tree->Branch( "mu_muid_nucone40", &mu_muid_nucone40 );
	m_tree->Branch( "mu_muid_ptcone20", &mu_muid_ptcone20 );
	m_tree->Branch( "mu_muid_ptcone30", &mu_muid_ptcone30 );
	m_tree->Branch( "mu_muid_ptcone40", &mu_muid_ptcone40 );
	m_tree->Branch( "mu_muid_energyLossPar", &mu_muid_energyLossPar );
	m_tree->Branch( "mu_muid_energyLossErr", &mu_muid_energyLossErr );
	m_tree->Branch( "mu_muid_bestMatch", &mu_muid_bestMatch );
	m_tree->Branch( "mu_muid_isStandAloneMuon", &mu_muid_isStandAloneMuon );
	m_tree->Branch( "mu_muid_isCombinedMuon", &mu_muid_isCombinedMuon );
	m_tree->Branch( "mu_muid_isLowPtReconstructedMuon", &mu_muid_isLowPtReconstructedMuon );
	m_tree->Branch( "mu_muid_d0_exPV", &mu_muid_d0_exPV );
	m_tree->Branch( "mu_muid_z0_exPV", &mu_muid_z0_exPV );
	m_tree->Branch( "mu_muid_phi_exPV", &mu_muid_phi_exPV );
	m_tree->Branch( "mu_muid_theta_exPV", &mu_muid_theta_exPV );
	m_tree->Branch( "mu_muid_qoverp_exPV", &mu_muid_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_d0_exPV", &mu_muid_cov_d0_exPV );
	m_tree->Branch( "mu_muid_cov_z0_exPV", &mu_muid_cov_z0_exPV );
	m_tree->Branch( "mu_muid_cov_phi_exPV", &mu_muid_cov_phi_exPV );
	m_tree->Branch( "mu_muid_cov_theta_exPV", &mu_muid_cov_theta_exPV );
	m_tree->Branch( "mu_muid_cov_qoverp_exPV", &mu_muid_cov_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_d0_z0_exPV", &mu_muid_cov_d0_z0_exPV );
	m_tree->Branch( "mu_muid_cov_d0_phi_exPV", &mu_muid_cov_d0_phi_exPV );
	m_tree->Branch( "mu_muid_cov_d0_theta_exPV", &mu_muid_cov_d0_theta_exPV );
	m_tree->Branch( "mu_muid_cov_d0_qoverp_exPV", &mu_muid_cov_d0_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_z0_phi_exPV", &mu_muid_cov_z0_phi_exPV );
	m_tree->Branch( "mu_muid_cov_z0_theta_exPV", &mu_muid_cov_z0_theta_exPV );
	m_tree->Branch( "mu_muid_cov_z0_qoverp_exPV", &mu_muid_cov_z0_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_phi_theta_exPV", &mu_muid_cov_phi_theta_exPV );
	m_tree->Branch( "mu_muid_cov_phi_qoverp_exPV", &mu_muid_cov_phi_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_theta_qoverp_exPV", &mu_muid_cov_theta_qoverp_exPV );
	m_tree->Branch( "mu_muid_ms_d0", &mu_muid_ms_d0 );
	m_tree->Branch( "mu_muid_ms_z0", &mu_muid_ms_z0 );
	m_tree->Branch( "mu_muid_ms_phi", &mu_muid_ms_phi );
	m_tree->Branch( "mu_muid_ms_theta", &mu_muid_ms_theta );
	m_tree->Branch( "mu_muid_ms_qoverp", &mu_muid_ms_qoverp );
	m_tree->Branch( "mu_muid_id_d0", &mu_muid_id_d0 );
	m_tree->Branch( "mu_muid_id_z0", &mu_muid_id_z0 );
	m_tree->Branch( "mu_muid_id_phi", &mu_muid_id_phi );
	m_tree->Branch( "mu_muid_id_theta", &mu_muid_id_theta );
	m_tree->Branch( "mu_muid_id_qoverp", &mu_muid_id_qoverp );
	m_tree->Branch( "mu_muid_me_d0", &mu_muid_me_d0 );
	m_tree->Branch( "mu_muid_me_z0", &mu_muid_me_z0 );
	m_tree->Branch( "mu_muid_me_phi", &mu_muid_me_phi );
	m_tree->Branch( "mu_muid_me_theta", &mu_muid_me_theta );
	m_tree->Branch( "mu_muid_me_qoverp", &mu_muid_me_qoverp );
	m_tree->Branch( "mu_muid_ie_d0", &mu_muid_ie_d0 );
	m_tree->Branch( "mu_muid_ie_z0", &mu_muid_ie_z0 );
	m_tree->Branch( "mu_muid_ie_phi", &mu_muid_ie_phi );
	m_tree->Branch( "mu_muid_ie_theta", &mu_muid_ie_theta );
	m_tree->Branch( "mu_muid_ie_qoverp", &mu_muid_ie_qoverp );
	m_tree->Branch( "mu_muid_nBLHits", &mu_muid_nBLHits );
	m_tree->Branch( "mu_muid_nPixHits", &mu_muid_nPixHits );
	m_tree->Branch( "mu_muid_nSCTHits", &mu_muid_nSCTHits );
	m_tree->Branch( "mu_muid_nTRTHits", &mu_muid_nTRTHits );
	m_tree->Branch( "mu_muid_nTRTHighTHits", &mu_muid_nTRTHighTHits );
	m_tree->Branch( "mu_muid_nBLSharedHits", &mu_muid_nBLSharedHits );
	m_tree->Branch( "mu_muid_nPixSharedHits", &mu_muid_nPixSharedHits );
	m_tree->Branch( "mu_muid_nPixHoles", &mu_muid_nPixHoles );
	m_tree->Branch( "mu_muid_nSCTSharedHits", &mu_muid_nSCTSharedHits );
	m_tree->Branch( "mu_muid_nSCTHoles", &mu_muid_nSCTHoles );
	m_tree->Branch( "mu_muid_nTRTOutliers", &mu_muid_nTRTOutliers );
	m_tree->Branch( "mu_muid_nTRTHighTOutliers", &mu_muid_nTRTHighTOutliers );
	m_tree->Branch( "mu_muid_nMDTHits", &mu_muid_nMDTHits );
	m_tree->Branch( "mu_muid_nMDTHoles", &mu_muid_nMDTHoles );
	m_tree->Branch( "mu_muid_nCSCEtaHits", &mu_muid_nCSCEtaHits );
	m_tree->Branch( "mu_muid_nCSCEtaHoles", &mu_muid_nCSCEtaHoles );
	m_tree->Branch( "mu_muid_nCSCPhiHits", &mu_muid_nCSCPhiHits );
	m_tree->Branch( "mu_muid_nCSCPhiHoles", &mu_muid_nCSCPhiHoles );
	m_tree->Branch( "mu_muid_nRPCEtaHits", &mu_muid_nRPCEtaHits );
	m_tree->Branch( "mu_muid_nRPCEtaHoles", &mu_muid_nRPCEtaHoles );
	m_tree->Branch( "mu_muid_nRPCPhiHits", &mu_muid_nRPCPhiHits );
	m_tree->Branch( "mu_muid_nRPCPhiHoles", &mu_muid_nRPCPhiHoles );
	m_tree->Branch( "mu_muid_nTGCEtaHits", &mu_muid_nTGCEtaHits );
	m_tree->Branch( "mu_muid_nTGCEtaHoles", &mu_muid_nTGCEtaHoles );
	m_tree->Branch( "mu_muid_nTGCPhiHits", &mu_muid_nTGCPhiHits );
	m_tree->Branch( "mu_muid_nTGCPhiHoles", &mu_muid_nTGCPhiHoles );
	m_tree->Branch( "mu_muid_nGangedPixels", &mu_muid_nGangedPixels );
	m_tree->Branch( "mu_muid_nOutliersOnTrack", &mu_muid_nOutliersOnTrack );
	m_tree->Branch( "mu_muid_nMDTBIHits", &mu_muid_nMDTBIHits );
	m_tree->Branch( "mu_muid_nMDTBMHits", &mu_muid_nMDTBMHits );
	m_tree->Branch( "mu_muid_nMDTBOHits", &mu_muid_nMDTBOHits );
	m_tree->Branch( "mu_muid_nMDTBEEHits", &mu_muid_nMDTBEEHits );
	m_tree->Branch( "mu_muid_nMDTBIS78Hits", &mu_muid_nMDTBIS78Hits );
	m_tree->Branch( "mu_muid_nMDTEIHits", &mu_muid_nMDTEIHits );
	m_tree->Branch( "mu_muid_nMDTEMHits", &mu_muid_nMDTEMHits );
	m_tree->Branch( "mu_muid_nMDTEOHits", &mu_muid_nMDTEOHits );
	m_tree->Branch( "mu_muid_nMDTEEHits", &mu_muid_nMDTEEHits );
	m_tree->Branch( "mu_muid_nRPCLayer1EtaHits", &mu_muid_nRPCLayer1EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer2EtaHits", &mu_muid_nRPCLayer2EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer3EtaHits", &mu_muid_nRPCLayer3EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer1PhiHits", &mu_muid_nRPCLayer1PhiHits );
	m_tree->Branch( "mu_muid_nRPCLayer2PhiHits", &mu_muid_nRPCLayer2PhiHits );
	m_tree->Branch( "mu_muid_nRPCLayer3PhiHits", &mu_muid_nRPCLayer3PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer1EtaHits", &mu_muid_nTGCLayer1EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer2EtaHits", &mu_muid_nTGCLayer2EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer3EtaHits", &mu_muid_nTGCLayer3EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer4EtaHits", &mu_muid_nTGCLayer4EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer1PhiHits", &mu_muid_nTGCLayer1PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer2PhiHits", &mu_muid_nTGCLayer2PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer3PhiHits", &mu_muid_nTGCLayer3PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer4PhiHits", &mu_muid_nTGCLayer4PhiHits );
	m_tree->Branch( "mu_muid_barrelSectors", &mu_muid_barrelSectors );
	m_tree->Branch( "mu_muid_endcapSectors", &mu_muid_endcapSectors );
	m_tree->Branch( "mu_muid_trackd0", &mu_muid_trackd0 );
	m_tree->Branch( "mu_muid_trackz0", &mu_muid_trackz0 );
	m_tree->Branch( "mu_muid_trackphi", &mu_muid_trackphi );
	m_tree->Branch( "mu_muid_tracktheta", &mu_muid_tracktheta );
	m_tree->Branch( "mu_muid_trackqoverp", &mu_muid_trackqoverp );
	m_tree->Branch( "mu_muid_trackcov_d0", &mu_muid_trackcov_d0 );
	m_tree->Branch( "mu_muid_trackcov_z0", &mu_muid_trackcov_z0 );
	m_tree->Branch( "mu_muid_trackcov_phi", &mu_muid_trackcov_phi );
	m_tree->Branch( "mu_muid_trackcov_theta", &mu_muid_trackcov_theta );
	m_tree->Branch( "mu_muid_trackcov_qoverp", &mu_muid_trackcov_qoverp );
	m_tree->Branch( "mu_muid_trackcov_d0_z0", &mu_muid_trackcov_d0_z0 );
	m_tree->Branch( "mu_muid_trackcov_d0_phi", &mu_muid_trackcov_d0_phi );
	m_tree->Branch( "mu_muid_trackcov_d0_theta", &mu_muid_trackcov_d0_theta );
	m_tree->Branch( "mu_muid_trackcov_d0_qoverp", &mu_muid_trackcov_d0_qoverp );
	m_tree->Branch( "mu_muid_trackcov_z0_phi", &mu_muid_trackcov_z0_phi );
	m_tree->Branch( "mu_muid_trackcov_z0_theta", &mu_muid_trackcov_z0_theta );
	m_tree->Branch( "mu_muid_trackcov_z0_qoverp", &mu_muid_trackcov_z0_qoverp );
	m_tree->Branch( "mu_muid_trackcov_phi_theta", &mu_muid_trackcov_phi_theta );
	m_tree->Branch( "mu_muid_trackcov_phi_qoverp", &mu_muid_trackcov_phi_qoverp );
	m_tree->Branch( "mu_muid_trackcov_theta_qoverp", &mu_muid_trackcov_theta_qoverp );
	m_tree->Branch( "mu_muid_trackfitchi2", &mu_muid_trackfitchi2 );
	m_tree->Branch( "mu_muid_trackfitndof", &mu_muid_trackfitndof );
	m_tree->Branch( "mu_muid_hastrack", &mu_muid_hastrack );
	m_tree->Branch( "mu_muid_EF_dr", &mu_muid_EF_dr );
	m_tree->Branch( "mu_muid_EF_cb_eta", &mu_muid_EF_cb_eta );
	m_tree->Branch( "mu_muid_EF_cb_phi", &mu_muid_EF_cb_phi );
	m_tree->Branch( "mu_muid_EF_cb_pt", &mu_muid_EF_cb_pt );
	m_tree->Branch( "mu_muid_EF_ms_eta", &mu_muid_EF_ms_eta );
	m_tree->Branch( "mu_muid_EF_ms_phi", &mu_muid_EF_ms_phi );
	m_tree->Branch( "mu_muid_EF_ms_pt", &mu_muid_EF_ms_pt );
	m_tree->Branch( "mu_muid_EF_me_eta", &mu_muid_EF_me_eta );
	m_tree->Branch( "mu_muid_EF_me_phi", &mu_muid_EF_me_phi );
	m_tree->Branch( "mu_muid_EF_me_pt", &mu_muid_EF_me_pt );
	m_tree->Branch( "mu_muid_EF_matched", &mu_muid_EF_matched );
	m_tree->Branch( "mu_muid_L2CB_dr", &mu_muid_L2CB_dr );
	m_tree->Branch( "mu_muid_L2CB_pt", &mu_muid_L2CB_pt );
	m_tree->Branch( "mu_muid_L2CB_eta", &mu_muid_L2CB_eta );
	m_tree->Branch( "mu_muid_L2CB_phi", &mu_muid_L2CB_phi );
	m_tree->Branch( "mu_muid_L2CB_id_pt", &mu_muid_L2CB_id_pt );
	m_tree->Branch( "mu_muid_L2CB_ms_pt", &mu_muid_L2CB_ms_pt );
	m_tree->Branch( "mu_muid_L2CB_nPixHits", &mu_muid_L2CB_nPixHits );
	m_tree->Branch( "mu_muid_L2CB_nSCTHits", &mu_muid_L2CB_nSCTHits );
	m_tree->Branch( "mu_muid_L2CB_nTRTHits", &mu_muid_L2CB_nTRTHits );
	m_tree->Branch( "mu_muid_L2CB_nTRTHighTHits", &mu_muid_L2CB_nTRTHighTHits );
	m_tree->Branch( "mu_muid_L2CB_matched", &mu_muid_L2CB_matched );
	m_tree->Branch( "mu_muid_L1_dr", &mu_muid_L1_dr );
	m_tree->Branch( "mu_muid_L1_pt", &mu_muid_L1_pt );
	m_tree->Branch( "mu_muid_L1_eta", &mu_muid_L1_eta );
	m_tree->Branch( "mu_muid_L1_phi", &mu_muid_L1_phi );
	m_tree->Branch( "mu_muid_L1_thrNumber", &mu_muid_L1_thrNumber );
	m_tree->Branch( "mu_muid_L1_RoINumber", &mu_muid_L1_RoINumber );
	m_tree->Branch( "mu_muid_L1_sectorAddress", &mu_muid_L1_sectorAddress );
	m_tree->Branch( "mu_muid_L1_firstCandidate", &mu_muid_L1_firstCandidate );
	m_tree->Branch( "mu_muid_L1_moreCandInRoI", &mu_muid_L1_moreCandInRoI );
	m_tree->Branch( "mu_muid_L1_moreCandInSector", &mu_muid_L1_moreCandInSector );
	m_tree->Branch( "mu_muid_L1_source", &mu_muid_L1_source );
	m_tree->Branch( "mu_muid_L1_hemisphere", &mu_muid_L1_hemisphere );
	m_tree->Branch( "mu_muid_L1_matched", &mu_muid_L1_matched );
}

void offlineTree::fill(Bool_t isgrl)
{
	// external
	isGRL     = isgrl;

	// event level
	RunNumber = m_phys->RunNumber;
	EventNumber = m_phys->EventNumber;
	timestamp = m_phys->timestamp;
	timestamp_ns = m_phys->timestamp_ns;
	lbn = m_phys->lbn;
	bcid = m_phys->bcid;
	detmask0 = m_phys->detmask0;
	detmask1 = m_phys->detmask1;
	pixelFlags = m_phys->pixelFlags;
	sctFlags = m_phys->sctFlags;
	trtFlags = m_phys->trtFlags;
	larFlags = m_phys->larFlags;
	tileFlags = m_phys->tileFlags;
	muonFlags = m_phys->muonFlags;
	fwdFlags = m_phys->fwdFlags;
	coreFlags = m_phys->coreFlags;
	pixelError = m_phys->pixelError;
	sctError = m_phys->sctError;
	trtError = m_phys->trtError;
	larError = m_phys->larError;
	tileError = m_phys->tileError;
	muonError = m_phys->muonError;
	fwdError = m_phys->fwdError;
	coreError = m_phys->coreError;
	lar_ncellA = m_phys->lar_ncellA;
	lar_ncellC = m_phys->lar_ncellC;
	lar_energyA = m_phys->lar_energyA;
	lar_energyC = m_phys->lar_energyC;
	lar_timeA = m_phys->lar_timeA;
	lar_timeC = m_phys->lar_timeC;
	lar_timeDiff = m_phys->lar_timeDiff;
		
	EF_2mu10 = m_phys->EF_2mu10;
	EF_2mu4 = m_phys->EF_2mu4;
	EF_2mu4_DiMu = m_phys->EF_2mu4_DiMu;
	EF_2mu4_DiMu_SiTrk = m_phys->EF_2mu4_DiMu_SiTrk;
	EF_2mu4_DiMu_noOS = m_phys->EF_2mu4_DiMu_noOS;
	EF_2mu4_DiMu_noOS_passL2 = m_phys->EF_2mu4_DiMu_noOS_passL2;
	EF_2mu4_DiMu_noVtx_noOS = m_phys->EF_2mu4_DiMu_noVtx_noOS;
	EF_2mu4_DiMu_noVtx_noOS_passL2 = m_phys->EF_2mu4_DiMu_noVtx_noOS_passL2;
	EF_2mu4_MSonly = m_phys->EF_2mu4_MSonly;
	EF_2mu6 = m_phys->EF_2mu6;
	EF_2mu6_DiMu = m_phys->EF_2mu6_DiMu;
	EF_2mu6_DiMu_noVtx_noOS = m_phys->EF_2mu6_DiMu_noVtx_noOS;
	EF_L1ItemStreamer_L1_2MU0 = m_phys->EF_L1ItemStreamer_L1_2MU0;
	EF_L1ItemStreamer_L1_2MU0_MU6 = m_phys->EF_L1ItemStreamer_L1_2MU0_MU6;
	EF_L1ItemStreamer_L1_2MU10 = m_phys->EF_L1ItemStreamer_L1_2MU10;
	EF_L1ItemStreamer_L1_2MU6 = m_phys->EF_L1ItemStreamer_L1_2MU6;
	EF_L1ItemStreamer_L1_EM10 = m_phys->EF_L1ItemStreamer_L1_EM10;
	EF_L1ItemStreamer_L1_EM10I = m_phys->EF_L1ItemStreamer_L1_EM10I;
	EF_L1ItemStreamer_L1_EM14 = m_phys->EF_L1ItemStreamer_L1_EM14;
	EF_L1ItemStreamer_L1_EM2 = m_phys->EF_L1ItemStreamer_L1_EM2;
	EF_L1ItemStreamer_L1_EM2_UNPAIRED = m_phys->EF_L1ItemStreamer_L1_EM2_UNPAIRED;
	EF_L1ItemStreamer_L1_EM3 = m_phys->EF_L1ItemStreamer_L1_EM3;
	EF_L1ItemStreamer_L1_EM3_EMPTY = m_phys->EF_L1ItemStreamer_L1_EM3_EMPTY;
	EF_L1ItemStreamer_L1_EM3_FIRSTEMPTY = m_phys->EF_L1ItemStreamer_L1_EM3_FIRSTEMPTY;
	EF_L1ItemStreamer_L1_EM3_MV = m_phys->EF_L1ItemStreamer_L1_EM3_MV;
	EF_L1ItemStreamer_L1_EM3_UNPAIRED = m_phys->EF_L1ItemStreamer_L1_EM3_UNPAIRED;
	EF_L1ItemStreamer_L1_EM4 = m_phys->EF_L1ItemStreamer_L1_EM4;
	EF_L1ItemStreamer_L1_EM5 = m_phys->EF_L1ItemStreamer_L1_EM5;
	EF_L1ItemStreamer_L1_EM5I = m_phys->EF_L1ItemStreamer_L1_EM5I;
	EF_L1ItemStreamer_L1_MU0 = m_phys->EF_L1ItemStreamer_L1_MU0;
	EF_L1ItemStreamer_L1_MU0_COMM = m_phys->EF_L1ItemStreamer_L1_MU0_COMM;
	EF_L1ItemStreamer_L1_MU0_COMM_EMPTY = m_phys->EF_L1ItemStreamer_L1_MU0_COMM_EMPTY;
	EF_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY = m_phys->EF_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY;
	EF_L1ItemStreamer_L1_MU0_EM3 = m_phys->EF_L1ItemStreamer_L1_MU0_EM3;
	EF_L1ItemStreamer_L1_MU0_EMPTY = m_phys->EF_L1ItemStreamer_L1_MU0_EMPTY;
	EF_L1ItemStreamer_L1_MU0_FIRSTEMPTY = m_phys->EF_L1ItemStreamer_L1_MU0_FIRSTEMPTY;
	EF_L1ItemStreamer_L1_MU0_J10 = m_phys->EF_L1ItemStreamer_L1_MU0_J10;
	EF_L1ItemStreamer_L1_MU0_J15 = m_phys->EF_L1ItemStreamer_L1_MU0_J15;
	EF_L1ItemStreamer_L1_MU0_J5 = m_phys->EF_L1ItemStreamer_L1_MU0_J5;
	EF_L1ItemStreamer_L1_MU0_MV = m_phys->EF_L1ItemStreamer_L1_MU0_MV;
	EF_L1ItemStreamer_L1_MU0_UNPAIRED = m_phys->EF_L1ItemStreamer_L1_MU0_UNPAIRED;
	EF_L1ItemStreamer_L1_MU10 = m_phys->EF_L1ItemStreamer_L1_MU10;
	EF_L1ItemStreamer_L1_MU10_EMPTY = m_phys->EF_L1ItemStreamer_L1_MU10_EMPTY;
	EF_L1ItemStreamer_L1_MU15 = m_phys->EF_L1ItemStreamer_L1_MU15;
	EF_L1ItemStreamer_L1_MU20 = m_phys->EF_L1ItemStreamer_L1_MU20;
	EF_L1ItemStreamer_L1_MU6 = m_phys->EF_L1ItemStreamer_L1_MU6;
	EF_L1ItemStreamer_L1_MU6_EM3 = m_phys->EF_L1ItemStreamer_L1_MU6_EM3;
	EF_L1ItemStreamer_L1_MU6_EMPTY = m_phys->EF_L1ItemStreamer_L1_MU6_EMPTY;
	EF_L1ItemStreamer_L1_MU6_FIRSTEMPTY = m_phys->EF_L1ItemStreamer_L1_MU6_FIRSTEMPTY;
	EF_L1ItemStreamer_L1_MU6_J5 = m_phys->EF_L1ItemStreamer_L1_MU6_J5;
	EF_L1ItemStreamer_L1_MU6_UNPAIRED = m_phys->EF_L1ItemStreamer_L1_MU6_UNPAIRED;
		   
	 EF_mu0_missingRoi = m_phys-> EF_mu0_missingRoi;
	EF_mu0_rpcOnly = m_phys->EF_mu0_rpcOnly;
	EF_mu10 = m_phys->EF_mu10;
	EF_mu10_MG = m_phys->EF_mu10_MG;
	EF_mu10_MSonly = m_phys->EF_mu10_MSonly;
	EF_mu10_MSonly_cosmic = m_phys->EF_mu10_MSonly_cosmic;
	EF_mu10_NoIDTrkCut = m_phys->EF_mu10_NoIDTrkCut;
	EF_mu10_SiTrk = m_phys->EF_mu10_SiTrk;
	EF_mu10_cosmic = m_phys->EF_mu10_cosmic;
	EF_mu10_muCombTag = m_phys->EF_mu10_muCombTag;
	EF_mu10_muCombTag_SiTrk = m_phys->EF_mu10_muCombTag_SiTrk;
	EF_mu10_passHLT = m_phys->EF_mu10_passHLT;
	EF_mu10i_loose = m_phys->EF_mu10i_loose;
	EF_mu13 = m_phys->EF_mu13;
	EF_mu15 = m_phys->EF_mu15;
	EF_mu20 = m_phys->EF_mu20;
	EF_mu20_MSonly = m_phys->EF_mu20_MSonly;
	EF_mu20_passHLT = m_phys->EF_mu20_passHLT;
	EF_mu4 = m_phys->EF_mu4;
	EF_mu4_DiMu = m_phys->EF_mu4_DiMu;
	EF_mu4_DiMu_FS = m_phys->EF_mu4_DiMu_FS;
	EF_mu4_DiMu_FS_noOS = m_phys->EF_mu4_DiMu_FS_noOS;
	EF_mu4_Jpsie5e3 = m_phys->EF_mu4_Jpsie5e3;
	EF_mu4_Jpsie5e3_FS = m_phys->EF_mu4_Jpsie5e3_FS;
	EF_mu4_Jpsie5e3_SiTrk = m_phys->EF_mu4_Jpsie5e3_SiTrk;
	EF_mu4_Jpsie5e3_SiTrk_FS = m_phys->EF_mu4_Jpsie5e3_SiTrk_FS;
	EF_mu4_L2MSonly_EFFS_passL2 = m_phys->EF_mu4_L2MSonly_EFFS_passL2;
	EF_mu4_MG = m_phys->EF_mu4_MG;
	EF_mu4_MSonly = m_phys->EF_mu4_MSonly;
	EF_mu4_MSonly_EFFS_passL2 = m_phys->EF_mu4_MSonly_EFFS_passL2;
	EF_mu4_MSonly_MB2_noL2_EFFS = m_phys->EF_mu4_MSonly_MB2_noL2_EFFS;
	EF_mu4_MSonly_Trk_Jpsi_loose = m_phys->EF_mu4_MSonly_Trk_Jpsi_loose;
	EF_mu4_MSonly_Trk_Upsi_loose_FS = m_phys->EF_mu4_MSonly_Trk_Upsi_loose_FS;
	EF_mu4_MSonly_cosmic = m_phys->EF_mu4_MSonly_cosmic;
	EF_mu4_MSonly_firstempty = m_phys->EF_mu4_MSonly_firstempty;
	EF_mu4_MV = m_phys->EF_mu4_MV;
	EF_mu4_NoIDTrkCut = m_phys->EF_mu4_NoIDTrkCut;
	EF_mu4_SiTrk = m_phys->EF_mu4_SiTrk;
	EF_mu4_Trk_Jpsi_loose = m_phys->EF_mu4_Trk_Jpsi_loose;
	EF_mu4_Trk_Upsi_loose_FS = m_phys->EF_mu4_Trk_Upsi_loose_FS;
	EF_mu4_comm = m_phys->EF_mu4_comm;
	EF_mu4_comm_MSonly = m_phys->EF_mu4_comm_MSonly;
	EF_mu4_comm_MSonly_cosmic = m_phys->EF_mu4_comm_MSonly_cosmic;
	EF_mu4_comm_MSonly_firstempty = m_phys->EF_mu4_comm_MSonly_firstempty;
	EF_mu4_comm_cosmic = m_phys->EF_mu4_comm_cosmic;
	EF_mu4_comm_firstempty = m_phys->EF_mu4_comm_firstempty;
	EF_mu4_cosmic = m_phys->EF_mu4_cosmic;
	EF_mu4_firstempty = m_phys->EF_mu4_firstempty;
	EF_mu4_j10_matched = m_phys->EF_mu4_j10_matched;
	EF_mu4_j20_matched = m_phys->EF_mu4_j20_matched;
	EF_mu4_j5_matched = m_phys->EF_mu4_j5_matched;
	EF_mu4_mu6 = m_phys->EF_mu4_mu6;
	EF_mu4_muCombTag = m_phys->EF_mu4_muCombTag;
	EF_mu4_muCombTag_SiTrk = m_phys->EF_mu4_muCombTag_SiTrk;
	EF_mu4_passHLT = m_phys->EF_mu4_passHLT;
	EF_mu4_tile = m_phys->EF_mu4_tile;
	EF_mu4_tile_SiTrk = m_phys->EF_mu4_tile_SiTrk;
	EF_mu4_trod = m_phys->EF_mu4_trod;
	EF_mu4_trod_SiTrk = m_phys->EF_mu4_trod_SiTrk;
	EF_mu4_unpaired = m_phys->EF_mu4_unpaired;
	EF_mu4mu6_DiMu = m_phys->EF_mu4mu6_DiMu;
	EF_mu6 = m_phys->EF_mu6;
	EF_mu6_DiMu = m_phys->EF_mu6_DiMu;
	EF_mu6_DiMu_FS = m_phys->EF_mu6_DiMu_FS;
	EF_mu6_DiMu_FS_noOS = m_phys->EF_mu6_DiMu_FS_noOS;
	EF_mu6_DsPhiPi = m_phys->EF_mu6_DsPhiPi;
	EF_mu6_Jpsie5e3 = m_phys->EF_mu6_Jpsie5e3;
	EF_mu6_Jpsie5e3_FS = m_phys->EF_mu6_Jpsie5e3_FS;
	EF_mu6_Jpsie5e3_SiTrk = m_phys->EF_mu6_Jpsie5e3_SiTrk;
	EF_mu6_Jpsie5e3_SiTrk_FS = m_phys->EF_mu6_Jpsie5e3_SiTrk_FS;
	EF_mu6_MG = m_phys->EF_mu6_MG;
	EF_mu6_MSonly = m_phys->EF_mu6_MSonly;
	EF_mu6_MSonly_cosmic = m_phys->EF_mu6_MSonly_cosmic;
	EF_mu6_MSonly_firstempty = m_phys->EF_mu6_MSonly_firstempty;
	EF_mu6_MSonly_unpaired = m_phys->EF_mu6_MSonly_unpaired;
	EF_mu6_SiTrk = m_phys->EF_mu6_SiTrk;
	EF_mu6_Trk_Jpsi_loose = m_phys->EF_mu6_Trk_Jpsi_loose;
	EF_mu6_Trk_Jpsi_loose_FS = m_phys->EF_mu6_Trk_Jpsi_loose_FS;
	EF_mu6_Trk_Upsi_loose_FS = m_phys->EF_mu6_Trk_Upsi_loose_FS;
	EF_mu6_cosmic = m_phys->EF_mu6_cosmic;
	EF_mu6_firstempty = m_phys->EF_mu6_firstempty;
	EF_mu6_muCombTag = m_phys->EF_mu6_muCombTag;
	EF_mu6_muCombTag_SiTrk = m_phys->EF_mu6_muCombTag_SiTrk;
	EF_mu6_passHLT = m_phys->EF_mu6_passHLT;
	EF_mu6_unpaired = m_phys->EF_mu6_unpaired;
		   
	L1_2EM2 = m_phys->L1_2EM2;
	L1_2EM3 = m_phys->L1_2EM3;
	L1_2EM4 = m_phys->L1_2EM4;
	L1_2EM5 = m_phys->L1_2EM5;
	L1_2MU0 = m_phys->L1_2MU0;
	L1_2MU0_MU6 = m_phys->L1_2MU0_MU6;
	L1_2MU10 = m_phys->L1_2MU10;
	L1_2MU6 = m_phys->L1_2MU6;
	L1_EM10 = m_phys->L1_EM10;
	L1_EM10I = m_phys->L1_EM10I;
	L1_EM14 = m_phys->L1_EM14;
	L1_EM2 = m_phys->L1_EM2;
	L1_EM2_UNPAIRED = m_phys->L1_EM2_UNPAIRED;
	L1_EM3 = m_phys->L1_EM3;
	L1_EM3_EMPTY = m_phys->L1_EM3_EMPTY;
	L1_EM3_FIRSTEMPTY = m_phys->L1_EM3_FIRSTEMPTY;
	L1_EM3_MV = m_phys->L1_EM3_MV;
	L1_EM3_UNPAIRED = m_phys->L1_EM3_UNPAIRED;
	L1_EM4 = m_phys->L1_EM4;
	L1_EM5 = m_phys->L1_EM5;
	L1_EM5I = m_phys->L1_EM5I;
	L1_MU0 = m_phys->L1_MU0;
	L1_MU0_COMM = m_phys->L1_MU0_COMM;
	L1_MU0_COMM_EMPTY = m_phys->L1_MU0_COMM_EMPTY;
	L1_MU0_COMM_FIRSTEMPTY = m_phys->L1_MU0_COMM_FIRSTEMPTY;
	L1_MU0_EM3 = m_phys->L1_MU0_EM3;
	L1_MU0_EMPTY = m_phys->L1_MU0_EMPTY;
	L1_MU0_FIRSTEMPTY = m_phys->L1_MU0_FIRSTEMPTY;
	L1_MU0_J10 = m_phys->L1_MU0_J10;
	L1_MU0_J15 = m_phys->L1_MU0_J15;
	L1_MU0_J5 = m_phys->L1_MU0_J5;
	L1_MU0_MV = m_phys->L1_MU0_MV;
	L1_MU0_UNPAIRED = m_phys->L1_MU0_UNPAIRED;
	L1_MU10 = m_phys->L1_MU10;
	L1_MU10_EMPTY = m_phys->L1_MU10_EMPTY;
	L1_MU15 = m_phys->L1_MU15;
	L1_MU20 = m_phys->L1_MU20;
	L1_MU6 = m_phys->L1_MU6;
	L1_MU6_EM3 = m_phys->L1_MU6_EM3;
	L1_MU6_EMPTY = m_phys->L1_MU6_EMPTY;
	L1_MU6_FIRSTEMPTY = m_phys->L1_MU6_FIRSTEMPTY;
	L1_MU6_J5 = m_phys->L1_MU6_J5;
	L1_MU6_UNPAIRED = m_phys->L1_MU6_UNPAIRED;
		   
	L2_2mu10 = m_phys->L2_2mu10;
	L2_2mu4 = m_phys->L2_2mu4;
	L2_2mu4_DiMu = m_phys->L2_2mu4_DiMu;
	L2_2mu4_DiMu_SiTrk = m_phys->L2_2mu4_DiMu_SiTrk;
	L2_2mu4_DiMu_noOS = m_phys->L2_2mu4_DiMu_noOS;
	L2_2mu4_DiMu_noOS_passL2 = m_phys->L2_2mu4_DiMu_noOS_passL2;
	L2_2mu4_DiMu_noVtx_noOS = m_phys->L2_2mu4_DiMu_noVtx_noOS;
	L2_2mu4_DiMu_noVtx_noOS_passL2 = m_phys->L2_2mu4_DiMu_noVtx_noOS_passL2;
	L2_2mu4_MSonly = m_phys->L2_2mu4_MSonly;
	L2_2mu6 = m_phys->L2_2mu6;
	L2_2mu6_DiMu = m_phys->L2_2mu6_DiMu;
	L2_2mu6_DiMu_noVtx_noOS = m_phys->L2_2mu6_DiMu_noVtx_noOS;
		   
	L2_L1ItemStreamer_L1_MU0 = m_phys->L2_L1ItemStreamer_L1_MU0;
	L2_L1ItemStreamer_L1_MU0_COMM = m_phys->L2_L1ItemStreamer_L1_MU0_COMM;
	L2_L1ItemStreamer_L1_MU0_COMM_EMPTY = m_phys->L2_L1ItemStreamer_L1_MU0_COMM_EMPTY;
	L2_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY = m_phys->L2_L1ItemStreamer_L1_MU0_COMM_FIRSTEMPTY;
	L2_L1ItemStreamer_L1_MU0_EM3 = m_phys->L2_L1ItemStreamer_L1_MU0_EM3;
	L2_L1ItemStreamer_L1_MU0_EMPTY = m_phys->L2_L1ItemStreamer_L1_MU0_EMPTY;
	L2_L1ItemStreamer_L1_MU0_FIRSTEMPTY = m_phys->L2_L1ItemStreamer_L1_MU0_FIRSTEMPTY;
	L2_L1ItemStreamer_L1_MU0_J10 = m_phys->L2_L1ItemStreamer_L1_MU0_J10;
	L2_L1ItemStreamer_L1_MU0_J15 = m_phys->L2_L1ItemStreamer_L1_MU0_J15;
	L2_L1ItemStreamer_L1_MU0_J5 = m_phys->L2_L1ItemStreamer_L1_MU0_J5;
	L2_L1ItemStreamer_L1_MU0_MV = m_phys->L2_L1ItemStreamer_L1_MU0_MV;
	L2_L1ItemStreamer_L1_MU0_UNPAIRED = m_phys->L2_L1ItemStreamer_L1_MU0_UNPAIRED;
	L2_L1ItemStreamer_L1_MU10 = m_phys->L2_L1ItemStreamer_L1_MU10;
	L2_L1ItemStreamer_L1_MU10_EMPTY = m_phys->L2_L1ItemStreamer_L1_MU10_EMPTY;
	L2_L1ItemStreamer_L1_MU15 = m_phys->L2_L1ItemStreamer_L1_MU15;
	L2_L1ItemStreamer_L1_MU20 = m_phys->L2_L1ItemStreamer_L1_MU20;
	L2_L1ItemStreamer_L1_MU6 = m_phys->L2_L1ItemStreamer_L1_MU6;
	L2_L1ItemStreamer_L1_MU6_EM3 = m_phys->L2_L1ItemStreamer_L1_MU6_EM3;
	L2_L1ItemStreamer_L1_MU6_EMPTY = m_phys->L2_L1ItemStreamer_L1_MU6_EMPTY;
	L2_L1ItemStreamer_L1_MU6_FIRSTEMPTY = m_phys->L2_L1ItemStreamer_L1_MU6_FIRSTEMPTY;
	L2_L1ItemStreamer_L1_MU6_J5 = m_phys->L2_L1ItemStreamer_L1_MU6_J5;
	L2_L1ItemStreamer_L1_MU6_UNPAIRED = m_phys->L2_L1ItemStreamer_L1_MU6_UNPAIRED;
		   
	 L2_mu0_missingRoi = m_phys-> L2_mu0_missingRoi;
	L2_mu0_rpcOnly = m_phys->L2_mu0_rpcOnly;
	L2_mu10 = m_phys->L2_mu10;
	L2_mu10_MG = m_phys->L2_mu10_MG;
	L2_mu10_MSonly = m_phys->L2_mu10_MSonly;
	L2_mu10_MSonly_cosmic = m_phys->L2_mu10_MSonly_cosmic;
	L2_mu10_NoIDTrkCut = m_phys->L2_mu10_NoIDTrkCut;
	L2_mu10_SiTrk = m_phys->L2_mu10_SiTrk;
	L2_mu10_cosmic = m_phys->L2_mu10_cosmic;
	L2_mu10_muCombTag = m_phys->L2_mu10_muCombTag;
	L2_mu10_muCombTag_SiTrk = m_phys->L2_mu10_muCombTag_SiTrk;
	L2_mu10_passHLT = m_phys->L2_mu10_passHLT;
	L2_mu10i_loose = m_phys->L2_mu10i_loose;
	L2_mu13 = m_phys->L2_mu13;
	L2_mu15 = m_phys->L2_mu15;
	L2_mu20 = m_phys->L2_mu20;
	L2_mu20_MSonly = m_phys->L2_mu20_MSonly;
	L2_mu20_passHLT = m_phys->L2_mu20_passHLT;
	L2_mu4 = m_phys->L2_mu4;
	L2_mu4_DiMu = m_phys->L2_mu4_DiMu;
	L2_mu4_DiMu_FS = m_phys->L2_mu4_DiMu_FS;
	L2_mu4_DiMu_FS_noOS = m_phys->L2_mu4_DiMu_FS_noOS;
	L2_mu4_Jpsie5e3 = m_phys->L2_mu4_Jpsie5e3;
	L2_mu4_Jpsie5e3_FS = m_phys->L2_mu4_Jpsie5e3_FS;
	L2_mu4_Jpsie5e3_SiTrk = m_phys->L2_mu4_Jpsie5e3_SiTrk;
	L2_mu4_Jpsie5e3_SiTrk_FS = m_phys->L2_mu4_Jpsie5e3_SiTrk_FS;
	L2_mu4_L2MSonly_EFFS_passL2 = m_phys->L2_mu4_L2MSonly_EFFS_passL2;
	L2_mu4_MG = m_phys->L2_mu4_MG;
	L2_mu4_MSonly = m_phys->L2_mu4_MSonly;
	L2_mu4_MSonly_EFFS_passL2 = m_phys->L2_mu4_MSonly_EFFS_passL2;
	L2_mu4_MSonly_MB2_noL2_EFFS = m_phys->L2_mu4_MSonly_MB2_noL2_EFFS;
	L2_mu4_MSonly_Trk_Jpsi_loose = m_phys->L2_mu4_MSonly_Trk_Jpsi_loose;
	L2_mu4_MSonly_Trk_Upsi_loose_FS = m_phys->L2_mu4_MSonly_Trk_Upsi_loose_FS;
	L2_mu4_MSonly_cosmic = m_phys->L2_mu4_MSonly_cosmic;
	L2_mu4_MSonly_firstempty = m_phys->L2_mu4_MSonly_firstempty;
	L2_mu4_MV = m_phys->L2_mu4_MV;
	L2_mu4_NoIDTrkCut = m_phys->L2_mu4_NoIDTrkCut;
	L2_mu4_SiTrk = m_phys->L2_mu4_SiTrk;
	L2_mu4_Trk_Jpsi_loose = m_phys->L2_mu4_Trk_Jpsi_loose;
	L2_mu4_Trk_Upsi_loose_FS = m_phys->L2_mu4_Trk_Upsi_loose_FS;
	L2_mu4_comm = m_phys->L2_mu4_comm;
	L2_mu4_comm_MSonly = m_phys->L2_mu4_comm_MSonly;
	L2_mu4_comm_MSonly_cosmic = m_phys->L2_mu4_comm_MSonly_cosmic;
	L2_mu4_comm_MSonly_firstempty = m_phys->L2_mu4_comm_MSonly_firstempty;
	L2_mu4_comm_cosmic = m_phys->L2_mu4_comm_cosmic;
	L2_mu4_comm_firstempty = m_phys->L2_mu4_comm_firstempty;
	L2_mu4_cosmic = m_phys->L2_mu4_cosmic;
	L2_mu4_firstempty = m_phys->L2_mu4_firstempty;
	L2_mu4_j10_matched = m_phys->L2_mu4_j10_matched;
	L2_mu4_j20_matched = m_phys->L2_mu4_j20_matched;
	L2_mu4_j5_matched = m_phys->L2_mu4_j5_matched;
	L2_mu4_mu6 = m_phys->L2_mu4_mu6;
	L2_mu4_muCombTag = m_phys->L2_mu4_muCombTag;
	L2_mu4_muCombTag_SiTrk = m_phys->L2_mu4_muCombTag_SiTrk;
	L2_mu4_passHLT = m_phys->L2_mu4_passHLT;
	L2_mu4_tile = m_phys->L2_mu4_tile;
	L2_mu4_tile_SiTrk = m_phys->L2_mu4_tile_SiTrk;
	L2_mu4_trod = m_phys->L2_mu4_trod;
	L2_mu4_trod_SiTrk = m_phys->L2_mu4_trod_SiTrk;
	L2_mu4_unpaired = m_phys->L2_mu4_unpaired;
	L2_mu4mu6_DiMu = m_phys->L2_mu4mu6_DiMu;
	L2_mu6 = m_phys->L2_mu6;
	L2_mu6_DiMu = m_phys->L2_mu6_DiMu;
	L2_mu6_DiMu_FS = m_phys->L2_mu6_DiMu_FS;
	L2_mu6_DiMu_FS_noOS = m_phys->L2_mu6_DiMu_FS_noOS;
	L2_mu6_DsPhiPi = m_phys->L2_mu6_DsPhiPi;
	L2_mu6_Jpsie5e3 = m_phys->L2_mu6_Jpsie5e3;
	L2_mu6_Jpsie5e3_FS = m_phys->L2_mu6_Jpsie5e3_FS;
	L2_mu6_Jpsie5e3_SiTrk = m_phys->L2_mu6_Jpsie5e3_SiTrk;
	L2_mu6_Jpsie5e3_SiTrk_FS = m_phys->L2_mu6_Jpsie5e3_SiTrk_FS;
	L2_mu6_MG = m_phys->L2_mu6_MG;
	L2_mu6_MSonly = m_phys->L2_mu6_MSonly;
	L2_mu6_MSonly_cosmic = m_phys->L2_mu6_MSonly_cosmic;
	L2_mu6_MSonly_firstempty = m_phys->L2_mu6_MSonly_firstempty;
	L2_mu6_MSonly_unpaired = m_phys->L2_mu6_MSonly_unpaired;
	L2_mu6_SiTrk = m_phys->L2_mu6_SiTrk;
	L2_mu6_Trk_Jpsi_loose = m_phys->L2_mu6_Trk_Jpsi_loose;
	L2_mu6_Trk_Jpsi_loose_FS = m_phys->L2_mu6_Trk_Jpsi_loose_FS;
	L2_mu6_Trk_Upsi_loose_FS = m_phys->L2_mu6_Trk_Upsi_loose_FS;
	L2_mu6_cosmic = m_phys->L2_mu6_cosmic;
	L2_mu6_firstempty = m_phys->L2_mu6_firstempty;
	L2_mu6_muCombTag = m_phys->L2_mu6_muCombTag;
	L2_mu6_muCombTag_SiTrk = m_phys->L2_mu6_muCombTag_SiTrk;
	L2_mu6_passHLT = m_phys->L2_mu6_passHLT;
	L2_mu6_unpaired = m_phys->L2_mu6_unpaired;


	
	
	// muon staco
	mu_staco_n = m_phys->mu_staco_n;
	mu_staco_E = m_phys->mu_staco_E;
	mu_staco_px = m_phys->mu_staco_px;
	mu_staco_py = m_phys->mu_staco_py;
	mu_staco_pz = m_phys->mu_staco_pz;
	mu_staco_m = m_phys->mu_staco_m;
	mu_staco_charge = m_phys->mu_staco_charge;
	mu_staco_pt = m_phys->mu_staco_pt;
	mu_staco_eta = m_phys->mu_staco_eta;
	mu_staco_phi = m_phys->mu_staco_phi;
	mu_staco_allauthor = m_phys->mu_staco_allauthor;
	mu_staco_author = m_phys->mu_staco_author;
	mu_staco_matchchi2 = m_phys->mu_staco_matchchi2;
	mu_staco_matchndof = m_phys->mu_staco_matchndof;
	mu_staco_etcone20 = m_phys->mu_staco_etcone20;
	mu_staco_etcone30 = m_phys->mu_staco_etcone30;
	mu_staco_etcone40 = m_phys->mu_staco_etcone40;
	mu_staco_nucone20 = m_phys->mu_staco_nucone20;
	mu_staco_nucone30 = m_phys->mu_staco_nucone30;
	mu_staco_nucone40 = m_phys->mu_staco_nucone40;
	mu_staco_ptcone20 = m_phys->mu_staco_ptcone20;
	mu_staco_ptcone30 = m_phys->mu_staco_ptcone30;
	mu_staco_ptcone40 = m_phys->mu_staco_ptcone40;
	mu_staco_energyLossPar = m_phys->mu_staco_energyLossPar;
	mu_staco_energyLossErr = m_phys->mu_staco_energyLossErr;
	mu_staco_bestMatch = m_phys->mu_staco_bestMatch;
	mu_staco_isStandAloneMuon = m_phys->mu_staco_isStandAloneMuon;
	mu_staco_isCombinedMuon = m_phys->mu_staco_isCombinedMuon;
	mu_staco_isLowPtReconstructedMuon = m_phys->mu_staco_isLowPtReconstructedMuon;
	mu_staco_d0_exPV = m_phys->mu_staco_d0_exPV;
	mu_staco_z0_exPV = m_phys->mu_staco_z0_exPV;
	mu_staco_phi_exPV = m_phys->mu_staco_phi_exPV;
	mu_staco_theta_exPV = m_phys->mu_staco_theta_exPV;
	mu_staco_qoverp_exPV = m_phys->mu_staco_qoverp_exPV;
	mu_staco_cov_d0_exPV = m_phys->mu_staco_cov_d0_exPV;
	mu_staco_cov_z0_exPV = m_phys->mu_staco_cov_z0_exPV;
	mu_staco_cov_phi_exPV = m_phys->mu_staco_cov_phi_exPV;
	mu_staco_cov_theta_exPV = m_phys->mu_staco_cov_theta_exPV;
	mu_staco_cov_qoverp_exPV = m_phys->mu_staco_cov_qoverp_exPV;
	mu_staco_cov_d0_z0_exPV = m_phys->mu_staco_cov_d0_z0_exPV;
	mu_staco_cov_d0_phi_exPV = m_phys->mu_staco_cov_d0_phi_exPV;
	mu_staco_cov_d0_theta_exPV = m_phys->mu_staco_cov_d0_theta_exPV;
	mu_staco_cov_d0_qoverp_exPV = m_phys->mu_staco_cov_d0_qoverp_exPV;
	mu_staco_cov_z0_phi_exPV = m_phys->mu_staco_cov_z0_phi_exPV;
	mu_staco_cov_z0_theta_exPV = m_phys->mu_staco_cov_z0_theta_exPV;
	mu_staco_cov_z0_qoverp_exPV = m_phys->mu_staco_cov_z0_qoverp_exPV;
	mu_staco_cov_phi_theta_exPV = m_phys->mu_staco_cov_phi_theta_exPV;
	mu_staco_cov_phi_qoverp_exPV = m_phys->mu_staco_cov_phi_qoverp_exPV;
	mu_staco_cov_theta_qoverp_exPV = m_phys->mu_staco_cov_theta_qoverp_exPV;
	mu_staco_ms_d0 = m_phys->mu_staco_ms_d0;
	mu_staco_ms_z0 = m_phys->mu_staco_ms_z0;
	mu_staco_ms_phi = m_phys->mu_staco_ms_phi;
	mu_staco_ms_theta = m_phys->mu_staco_ms_theta;
	mu_staco_ms_qoverp = m_phys->mu_staco_ms_qoverp;
	mu_staco_id_d0 = m_phys->mu_staco_id_d0;
	mu_staco_id_z0 = m_phys->mu_staco_id_z0;
	mu_staco_id_phi = m_phys->mu_staco_id_phi;
	mu_staco_id_theta = m_phys->mu_staco_id_theta;
	mu_staco_id_qoverp = m_phys->mu_staco_id_qoverp;
	mu_staco_me_d0 = m_phys->mu_staco_me_d0;
	mu_staco_me_z0 = m_phys->mu_staco_me_z0;
	mu_staco_me_phi = m_phys->mu_staco_me_phi;
	mu_staco_me_theta = m_phys->mu_staco_me_theta;
	mu_staco_me_qoverp = m_phys->mu_staco_me_qoverp;
	mu_staco_ie_d0 = m_phys->mu_staco_ie_d0;
	mu_staco_ie_z0 = m_phys->mu_staco_ie_z0;
	mu_staco_ie_phi = m_phys->mu_staco_ie_phi;
	mu_staco_ie_theta = m_phys->mu_staco_ie_theta;
	mu_staco_ie_qoverp = m_phys->mu_staco_ie_qoverp;
	mu_staco_nBLHits = m_phys->mu_staco_nBLHits;
	mu_staco_nPixHits = m_phys->mu_staco_nPixHits;
	mu_staco_nSCTHits = m_phys->mu_staco_nSCTHits;
	mu_staco_nTRTHits = m_phys->mu_staco_nTRTHits;
	mu_staco_nTRTHighTHits = m_phys->mu_staco_nTRTHighTHits;
	mu_staco_nBLSharedHits = m_phys->mu_staco_nBLSharedHits;
	mu_staco_nPixSharedHits = m_phys->mu_staco_nPixSharedHits;
	mu_staco_nPixHoles = m_phys->mu_staco_nPixHoles;
	mu_staco_nSCTSharedHits = m_phys->mu_staco_nSCTSharedHits;
	mu_staco_nSCTHoles = m_phys->mu_staco_nSCTHoles;
	mu_staco_nTRTOutliers = m_phys->mu_staco_nTRTOutliers;
	mu_staco_nTRTHighTOutliers = m_phys->mu_staco_nTRTHighTOutliers;
	mu_staco_nMDTHits = m_phys->mu_staco_nMDTHits;
	mu_staco_nMDTHoles = m_phys->mu_staco_nMDTHoles;
	mu_staco_nCSCEtaHits = m_phys->mu_staco_nCSCEtaHits;
	mu_staco_nCSCEtaHoles = m_phys->mu_staco_nCSCEtaHoles;
	mu_staco_nCSCPhiHits = m_phys->mu_staco_nCSCPhiHits;
	mu_staco_nCSCPhiHoles = m_phys->mu_staco_nCSCPhiHoles;
	mu_staco_nRPCEtaHits = m_phys->mu_staco_nRPCEtaHits;
	mu_staco_nRPCEtaHoles = m_phys->mu_staco_nRPCEtaHoles;
	mu_staco_nRPCPhiHits = m_phys->mu_staco_nRPCPhiHits;
	mu_staco_nRPCPhiHoles = m_phys->mu_staco_nRPCPhiHoles;
	mu_staco_nTGCEtaHits = m_phys->mu_staco_nTGCEtaHits;
	mu_staco_nTGCEtaHoles = m_phys->mu_staco_nTGCEtaHoles;
	mu_staco_nTGCPhiHits = m_phys->mu_staco_nTGCPhiHits;
	mu_staco_nTGCPhiHoles = m_phys->mu_staco_nTGCPhiHoles;
	mu_staco_nGangedPixels = m_phys->mu_staco_nGangedPixels;
	mu_staco_nOutliersOnTrack = m_phys->mu_staco_nOutliersOnTrack;
	mu_staco_nMDTBIHits = m_phys->mu_staco_nMDTBIHits;
	mu_staco_nMDTBMHits = m_phys->mu_staco_nMDTBMHits;
	mu_staco_nMDTBOHits = m_phys->mu_staco_nMDTBOHits;
	mu_staco_nMDTBEEHits = m_phys->mu_staco_nMDTBEEHits;
	mu_staco_nMDTBIS78Hits = m_phys->mu_staco_nMDTBIS78Hits;
	mu_staco_nMDTEIHits = m_phys->mu_staco_nMDTEIHits;
	mu_staco_nMDTEMHits = m_phys->mu_staco_nMDTEMHits;
	mu_staco_nMDTEOHits = m_phys->mu_staco_nMDTEOHits;
	mu_staco_nMDTEEHits = m_phys->mu_staco_nMDTEEHits;
	mu_staco_nRPCLayer1EtaHits = m_phys->mu_staco_nRPCLayer1EtaHits;
	mu_staco_nRPCLayer2EtaHits = m_phys->mu_staco_nRPCLayer2EtaHits;
	mu_staco_nRPCLayer3EtaHits = m_phys->mu_staco_nRPCLayer3EtaHits;
	mu_staco_nRPCLayer1PhiHits = m_phys->mu_staco_nRPCLayer1PhiHits;
	mu_staco_nRPCLayer2PhiHits = m_phys->mu_staco_nRPCLayer2PhiHits;
	mu_staco_nRPCLayer3PhiHits = m_phys->mu_staco_nRPCLayer3PhiHits;
	mu_staco_nTGCLayer1EtaHits = m_phys->mu_staco_nTGCLayer1EtaHits;
	mu_staco_nTGCLayer2EtaHits = m_phys->mu_staco_nTGCLayer2EtaHits;
	mu_staco_nTGCLayer3EtaHits = m_phys->mu_staco_nTGCLayer3EtaHits;
	mu_staco_nTGCLayer4EtaHits = m_phys->mu_staco_nTGCLayer4EtaHits;
	mu_staco_nTGCLayer1PhiHits = m_phys->mu_staco_nTGCLayer1PhiHits;
	mu_staco_nTGCLayer2PhiHits = m_phys->mu_staco_nTGCLayer2PhiHits;
	mu_staco_nTGCLayer3PhiHits = m_phys->mu_staco_nTGCLayer3PhiHits;
	mu_staco_nTGCLayer4PhiHits = m_phys->mu_staco_nTGCLayer4PhiHits;
	mu_staco_barrelSectors = m_phys->mu_staco_barrelSectors;
	mu_staco_endcapSectors = m_phys->mu_staco_endcapSectors;
	mu_staco_trackd0 = m_phys->mu_staco_trackd0;
	mu_staco_trackz0 = m_phys->mu_staco_trackz0;
	mu_staco_trackphi = m_phys->mu_staco_trackphi;
	mu_staco_tracktheta = m_phys->mu_staco_tracktheta;
	mu_staco_trackqoverp = m_phys->mu_staco_trackqoverp;
	mu_staco_trackcov_d0 = m_phys->mu_staco_trackcov_d0;
	mu_staco_trackcov_z0 = m_phys->mu_staco_trackcov_z0;
	mu_staco_trackcov_phi = m_phys->mu_staco_trackcov_phi;
	mu_staco_trackcov_theta = m_phys->mu_staco_trackcov_theta;
	mu_staco_trackcov_qoverp = m_phys->mu_staco_trackcov_qoverp;
	mu_staco_trackcov_d0_z0 = m_phys->mu_staco_trackcov_d0_z0;
	mu_staco_trackcov_d0_phi = m_phys->mu_staco_trackcov_d0_phi;
	mu_staco_trackcov_d0_theta = m_phys->mu_staco_trackcov_d0_theta;
	mu_staco_trackcov_d0_qoverp = m_phys->mu_staco_trackcov_d0_qoverp;
	mu_staco_trackcov_z0_phi = m_phys->mu_staco_trackcov_z0_phi;
	mu_staco_trackcov_z0_theta = m_phys->mu_staco_trackcov_z0_theta;
	mu_staco_trackcov_z0_qoverp = m_phys->mu_staco_trackcov_z0_qoverp;
	mu_staco_trackcov_phi_theta = m_phys->mu_staco_trackcov_phi_theta;
	mu_staco_trackcov_phi_qoverp = m_phys->mu_staco_trackcov_phi_qoverp;
	mu_staco_trackcov_theta_qoverp = m_phys->mu_staco_trackcov_theta_qoverp;
	mu_staco_trackfitchi2 = m_phys->mu_staco_trackfitchi2;
	mu_staco_trackfitndof = m_phys->mu_staco_trackfitndof;
	mu_staco_hastrack = m_phys->mu_staco_hastrack;
	mu_staco_EF_dr = m_phys->mu_staco_EF_dr;
	mu_staco_EF_cb_eta = m_phys->mu_staco_EF_cb_eta;
	mu_staco_EF_cb_phi = m_phys->mu_staco_EF_cb_phi;
	mu_staco_EF_cb_pt = m_phys->mu_staco_EF_cb_pt;
	mu_staco_EF_ms_eta = m_phys->mu_staco_EF_ms_eta;
	mu_staco_EF_ms_phi = m_phys->mu_staco_EF_ms_phi;
	mu_staco_EF_ms_pt = m_phys->mu_staco_EF_ms_pt;
	mu_staco_EF_me_eta = m_phys->mu_staco_EF_me_eta;
	mu_staco_EF_me_phi = m_phys->mu_staco_EF_me_phi;
	mu_staco_EF_me_pt = m_phys->mu_staco_EF_me_pt;
	mu_staco_EF_matched = m_phys->mu_staco_EF_matched;
	mu_staco_L2CB_dr = m_phys->mu_staco_L2CB_dr;
	mu_staco_L2CB_pt = m_phys->mu_staco_L2CB_pt;
	mu_staco_L2CB_eta = m_phys->mu_staco_L2CB_eta;
	mu_staco_L2CB_phi = m_phys->mu_staco_L2CB_phi;
	mu_staco_L2CB_id_pt = m_phys->mu_staco_L2CB_id_pt;
	mu_staco_L2CB_ms_pt = m_phys->mu_staco_L2CB_ms_pt;
	mu_staco_L2CB_nPixHits = m_phys->mu_staco_L2CB_nPixHits;
	mu_staco_L2CB_nSCTHits = m_phys->mu_staco_L2CB_nSCTHits;
	mu_staco_L2CB_nTRTHits = m_phys->mu_staco_L2CB_nTRTHits;
	mu_staco_L2CB_nTRTHighTHits = m_phys->mu_staco_L2CB_nTRTHighTHits;
	mu_staco_L2CB_matched = m_phys->mu_staco_L2CB_matched;
	mu_staco_L1_dr = m_phys->mu_staco_L1_dr;
	mu_staco_L1_pt = m_phys->mu_staco_L1_pt;
	mu_staco_L1_eta = m_phys->mu_staco_L1_eta;
	mu_staco_L1_phi = m_phys->mu_staco_L1_phi;
	mu_staco_L1_thrNumber = m_phys->mu_staco_L1_thrNumber;
	mu_staco_L1_RoINumber = m_phys->mu_staco_L1_RoINumber;
	mu_staco_L1_sectorAddress = m_phys->mu_staco_L1_sectorAddress;
	mu_staco_L1_firstCandidate = m_phys->mu_staco_L1_firstCandidate;
	mu_staco_L1_moreCandInRoI = m_phys->mu_staco_L1_moreCandInRoI;
	mu_staco_L1_moreCandInSector = m_phys->mu_staco_L1_moreCandInSector;
	mu_staco_L1_source = m_phys->mu_staco_L1_source;
	mu_staco_L1_hemisphere = m_phys->mu_staco_L1_hemisphere;
	mu_staco_L1_matched = m_phys->mu_staco_L1_matched;
	
	
	// muon muid
	mu_muid_n = m_phys->mu_muid_n;
	mu_muid_E = m_phys->mu_muid_E;
	mu_muid_px = m_phys->mu_muid_px;
	mu_muid_py = m_phys->mu_muid_py;
	mu_muid_pz = m_phys->mu_muid_pz;
	mu_muid_m = m_phys->mu_muid_m;
	mu_muid_charge = m_phys->mu_muid_charge;
	mu_muid_pt = m_phys->mu_muid_pt;
	mu_muid_eta = m_phys->mu_muid_eta;
	mu_muid_phi = m_phys->mu_muid_phi;
	mu_muid_allauthor = m_phys->mu_muid_allauthor;
	mu_muid_author = m_phys->mu_muid_author;
	mu_muid_matchchi2 = m_phys->mu_muid_matchchi2;
	mu_muid_matchndof = m_phys->mu_muid_matchndof;
	mu_muid_etcone20 = m_phys->mu_muid_etcone20;
	mu_muid_etcone30 = m_phys->mu_muid_etcone30;
	mu_muid_etcone40 = m_phys->mu_muid_etcone40;
	mu_muid_nucone20 = m_phys->mu_muid_nucone20;
	mu_muid_nucone30 = m_phys->mu_muid_nucone30;
	mu_muid_nucone40 = m_phys->mu_muid_nucone40;
	mu_muid_ptcone20 = m_phys->mu_muid_ptcone20;
	mu_muid_ptcone30 = m_phys->mu_muid_ptcone30;
	mu_muid_ptcone40 = m_phys->mu_muid_ptcone40;
	mu_muid_energyLossPar = m_phys->mu_muid_energyLossPar;
	mu_muid_energyLossErr = m_phys->mu_muid_energyLossErr;
	mu_muid_bestMatch = m_phys->mu_muid_bestMatch;
	mu_muid_isStandAloneMuon = m_phys->mu_muid_isStandAloneMuon;
	mu_muid_isCombinedMuon = m_phys->mu_muid_isCombinedMuon;
	mu_muid_isLowPtReconstructedMuon = m_phys->mu_muid_isLowPtReconstructedMuon;
	mu_muid_d0_exPV = m_phys->mu_muid_d0_exPV;
	mu_muid_z0_exPV = m_phys->mu_muid_z0_exPV;
	mu_muid_phi_exPV = m_phys->mu_muid_phi_exPV;
	mu_muid_theta_exPV = m_phys->mu_muid_theta_exPV;
	mu_muid_qoverp_exPV = m_phys->mu_muid_qoverp_exPV;
	mu_muid_cov_d0_exPV = m_phys->mu_muid_cov_d0_exPV;
	mu_muid_cov_z0_exPV = m_phys->mu_muid_cov_z0_exPV;
	mu_muid_cov_phi_exPV = m_phys->mu_muid_cov_phi_exPV;
	mu_muid_cov_theta_exPV = m_phys->mu_muid_cov_theta_exPV;
	mu_muid_cov_qoverp_exPV = m_phys->mu_muid_cov_qoverp_exPV;
	mu_muid_cov_d0_z0_exPV = m_phys->mu_muid_cov_d0_z0_exPV;
	mu_muid_cov_d0_phi_exPV = m_phys->mu_muid_cov_d0_phi_exPV;
	mu_muid_cov_d0_theta_exPV = m_phys->mu_muid_cov_d0_theta_exPV;
	mu_muid_cov_d0_qoverp_exPV = m_phys->mu_muid_cov_d0_qoverp_exPV;
	mu_muid_cov_z0_phi_exPV = m_phys->mu_muid_cov_z0_phi_exPV;
	mu_muid_cov_z0_theta_exPV = m_phys->mu_muid_cov_z0_theta_exPV;
	mu_muid_cov_z0_qoverp_exPV = m_phys->mu_muid_cov_z0_qoverp_exPV;
	mu_muid_cov_phi_theta_exPV = m_phys->mu_muid_cov_phi_theta_exPV;
	mu_muid_cov_phi_qoverp_exPV = m_phys->mu_muid_cov_phi_qoverp_exPV;
	mu_muid_cov_theta_qoverp_exPV = m_phys->mu_muid_cov_theta_qoverp_exPV;
	mu_muid_ms_d0 = m_phys->mu_muid_ms_d0;
	mu_muid_ms_z0 = m_phys->mu_muid_ms_z0;
	mu_muid_ms_phi = m_phys->mu_muid_ms_phi;
	mu_muid_ms_theta = m_phys->mu_muid_ms_theta;
	mu_muid_ms_qoverp = m_phys->mu_muid_ms_qoverp;
	mu_muid_id_d0 = m_phys->mu_muid_id_d0;
	mu_muid_id_z0 = m_phys->mu_muid_id_z0;
	mu_muid_id_phi = m_phys->mu_muid_id_phi;
	mu_muid_id_theta = m_phys->mu_muid_id_theta;
	mu_muid_id_qoverp = m_phys->mu_muid_id_qoverp;
	mu_muid_me_d0 = m_phys->mu_muid_me_d0;
	mu_muid_me_z0 = m_phys->mu_muid_me_z0;
	mu_muid_me_phi = m_phys->mu_muid_me_phi;
	mu_muid_me_theta = m_phys->mu_muid_me_theta;
	mu_muid_me_qoverp = m_phys->mu_muid_me_qoverp;
	mu_muid_ie_d0 = m_phys->mu_muid_ie_d0;
	mu_muid_ie_z0 = m_phys->mu_muid_ie_z0;
	mu_muid_ie_phi = m_phys->mu_muid_ie_phi;
	mu_muid_ie_theta = m_phys->mu_muid_ie_theta;
	mu_muid_ie_qoverp = m_phys->mu_muid_ie_qoverp;
	mu_muid_nBLHits = m_phys->mu_muid_nBLHits;
	mu_muid_nPixHits = m_phys->mu_muid_nPixHits;
	mu_muid_nSCTHits = m_phys->mu_muid_nSCTHits;
	mu_muid_nTRTHits = m_phys->mu_muid_nTRTHits;
	mu_muid_nTRTHighTHits = m_phys->mu_muid_nTRTHighTHits;
	mu_muid_nBLSharedHits = m_phys->mu_muid_nBLSharedHits;
	mu_muid_nPixSharedHits = m_phys->mu_muid_nPixSharedHits;
	mu_muid_nPixHoles = m_phys->mu_muid_nPixHoles;
	mu_muid_nSCTSharedHits = m_phys->mu_muid_nSCTSharedHits;
	mu_muid_nSCTHoles = m_phys->mu_muid_nSCTHoles;
	mu_muid_nTRTOutliers = m_phys->mu_muid_nTRTOutliers;
	mu_muid_nTRTHighTOutliers = m_phys->mu_muid_nTRTHighTOutliers;
	mu_muid_nMDTHits = m_phys->mu_muid_nMDTHits;
	mu_muid_nMDTHoles = m_phys->mu_muid_nMDTHoles;
	mu_muid_nCSCEtaHits = m_phys->mu_muid_nCSCEtaHits;
	mu_muid_nCSCEtaHoles = m_phys->mu_muid_nCSCEtaHoles;
	mu_muid_nCSCPhiHits = m_phys->mu_muid_nCSCPhiHits;
	mu_muid_nCSCPhiHoles = m_phys->mu_muid_nCSCPhiHoles;
	mu_muid_nRPCEtaHits = m_phys->mu_muid_nRPCEtaHits;
	mu_muid_nRPCEtaHoles = m_phys->mu_muid_nRPCEtaHoles;
	mu_muid_nRPCPhiHits = m_phys->mu_muid_nRPCPhiHits;
	mu_muid_nRPCPhiHoles = m_phys->mu_muid_nRPCPhiHoles;
	mu_muid_nTGCEtaHits = m_phys->mu_muid_nTGCEtaHits;
	mu_muid_nTGCEtaHoles = m_phys->mu_muid_nTGCEtaHoles;
	mu_muid_nTGCPhiHits = m_phys->mu_muid_nTGCPhiHits;
	mu_muid_nTGCPhiHoles = m_phys->mu_muid_nTGCPhiHoles;
	mu_muid_nGangedPixels = m_phys->mu_muid_nGangedPixels;
	mu_muid_nOutliersOnTrack = m_phys->mu_muid_nOutliersOnTrack;
	mu_muid_nMDTBIHits = m_phys->mu_muid_nMDTBIHits;
	mu_muid_nMDTBMHits = m_phys->mu_muid_nMDTBMHits;
	mu_muid_nMDTBOHits = m_phys->mu_muid_nMDTBOHits;
	mu_muid_nMDTBEEHits = m_phys->mu_muid_nMDTBEEHits;
	mu_muid_nMDTBIS78Hits = m_phys->mu_muid_nMDTBIS78Hits;
	mu_muid_nMDTEIHits = m_phys->mu_muid_nMDTEIHits;
	mu_muid_nMDTEMHits = m_phys->mu_muid_nMDTEMHits;
	mu_muid_nMDTEOHits = m_phys->mu_muid_nMDTEOHits;
	mu_muid_nMDTEEHits = m_phys->mu_muid_nMDTEEHits;
	mu_muid_nRPCLayer1EtaHits = m_phys->mu_muid_nRPCLayer1EtaHits;
	mu_muid_nRPCLayer2EtaHits = m_phys->mu_muid_nRPCLayer2EtaHits;
	mu_muid_nRPCLayer3EtaHits = m_phys->mu_muid_nRPCLayer3EtaHits;
	mu_muid_nRPCLayer1PhiHits = m_phys->mu_muid_nRPCLayer1PhiHits;
	mu_muid_nRPCLayer2PhiHits = m_phys->mu_muid_nRPCLayer2PhiHits;
	mu_muid_nRPCLayer3PhiHits = m_phys->mu_muid_nRPCLayer3PhiHits;
	mu_muid_nTGCLayer1EtaHits = m_phys->mu_muid_nTGCLayer1EtaHits;
	mu_muid_nTGCLayer2EtaHits = m_phys->mu_muid_nTGCLayer2EtaHits;
	mu_muid_nTGCLayer3EtaHits = m_phys->mu_muid_nTGCLayer3EtaHits;
	mu_muid_nTGCLayer4EtaHits = m_phys->mu_muid_nTGCLayer4EtaHits;
	mu_muid_nTGCLayer1PhiHits = m_phys->mu_muid_nTGCLayer1PhiHits;
	mu_muid_nTGCLayer2PhiHits = m_phys->mu_muid_nTGCLayer2PhiHits;
	mu_muid_nTGCLayer3PhiHits = m_phys->mu_muid_nTGCLayer3PhiHits;
	mu_muid_nTGCLayer4PhiHits = m_phys->mu_muid_nTGCLayer4PhiHits;
	mu_muid_barrelSectors = m_phys->mu_muid_barrelSectors;
	mu_muid_endcapSectors = m_phys->mu_muid_endcapSectors;
	mu_muid_trackd0 = m_phys->mu_muid_trackd0;
	mu_muid_trackz0 = m_phys->mu_muid_trackz0;
	mu_muid_trackphi = m_phys->mu_muid_trackphi;
	mu_muid_tracktheta = m_phys->mu_muid_tracktheta;
	mu_muid_trackqoverp = m_phys->mu_muid_trackqoverp;
	mu_muid_trackcov_d0 = m_phys->mu_muid_trackcov_d0;
	mu_muid_trackcov_z0 = m_phys->mu_muid_trackcov_z0;
	mu_muid_trackcov_phi = m_phys->mu_muid_trackcov_phi;
	mu_muid_trackcov_theta = m_phys->mu_muid_trackcov_theta;
	mu_muid_trackcov_qoverp = m_phys->mu_muid_trackcov_qoverp;
	mu_muid_trackcov_d0_z0 = m_phys->mu_muid_trackcov_d0_z0;
	mu_muid_trackcov_d0_phi = m_phys->mu_muid_trackcov_d0_phi;
	mu_muid_trackcov_d0_theta = m_phys->mu_muid_trackcov_d0_theta;
	mu_muid_trackcov_d0_qoverp = m_phys->mu_muid_trackcov_d0_qoverp;
	mu_muid_trackcov_z0_phi = m_phys->mu_muid_trackcov_z0_phi;
	mu_muid_trackcov_z0_theta = m_phys->mu_muid_trackcov_z0_theta;
	mu_muid_trackcov_z0_qoverp = m_phys->mu_muid_trackcov_z0_qoverp;
	mu_muid_trackcov_phi_theta = m_phys->mu_muid_trackcov_phi_theta;
	mu_muid_trackcov_phi_qoverp = m_phys->mu_muid_trackcov_phi_qoverp;
	mu_muid_trackcov_theta_qoverp = m_phys->mu_muid_trackcov_theta_qoverp;
	mu_muid_trackfitchi2 = m_phys->mu_muid_trackfitchi2;
	mu_muid_trackfitndof = m_phys->mu_muid_trackfitndof;
	mu_muid_hastrack = m_phys->mu_muid_hastrack;
	mu_muid_EF_dr = m_phys->mu_muid_EF_dr;
	mu_muid_EF_cb_eta = m_phys->mu_muid_EF_cb_eta;
	mu_muid_EF_cb_phi = m_phys->mu_muid_EF_cb_phi;
	mu_muid_EF_cb_pt = m_phys->mu_muid_EF_cb_pt;
	mu_muid_EF_ms_eta = m_phys->mu_muid_EF_ms_eta;
	mu_muid_EF_ms_phi = m_phys->mu_muid_EF_ms_phi;
	mu_muid_EF_ms_pt = m_phys->mu_muid_EF_ms_pt;
	mu_muid_EF_me_eta = m_phys->mu_muid_EF_me_eta;
	mu_muid_EF_me_phi = m_phys->mu_muid_EF_me_phi;
	mu_muid_EF_me_pt = m_phys->mu_muid_EF_me_pt;
	mu_muid_EF_matched = m_phys->mu_muid_EF_matched;
	mu_muid_L2CB_dr = m_phys->mu_muid_L2CB_dr;
	mu_muid_L2CB_pt = m_phys->mu_muid_L2CB_pt;
	mu_muid_L2CB_eta = m_phys->mu_muid_L2CB_eta;
	mu_muid_L2CB_phi = m_phys->mu_muid_L2CB_phi;
	mu_muid_L2CB_id_pt = m_phys->mu_muid_L2CB_id_pt;
	mu_muid_L2CB_ms_pt = m_phys->mu_muid_L2CB_ms_pt;
	mu_muid_L2CB_nPixHits = m_phys->mu_muid_L2CB_nPixHits;
	mu_muid_L2CB_nSCTHits = m_phys->mu_muid_L2CB_nSCTHits;
	mu_muid_L2CB_nTRTHits = m_phys->mu_muid_L2CB_nTRTHits;
	mu_muid_L2CB_nTRTHighTHits = m_phys->mu_muid_L2CB_nTRTHighTHits;
	mu_muid_L2CB_matched = m_phys->mu_muid_L2CB_matched;
	mu_muid_L1_dr = m_phys->mu_muid_L1_dr;
	mu_muid_L1_pt = m_phys->mu_muid_L1_pt;
	mu_muid_L1_eta = m_phys->mu_muid_L1_eta;
	mu_muid_L1_phi = m_phys->mu_muid_L1_phi;
	mu_muid_L1_thrNumber = m_phys->mu_muid_L1_thrNumber;
	mu_muid_L1_RoINumber = m_phys->mu_muid_L1_RoINumber;
	mu_muid_L1_sectorAddress = m_phys->mu_muid_L1_sectorAddress;
	mu_muid_L1_firstCandidate = m_phys->mu_muid_L1_firstCandidate;
	mu_muid_L1_moreCandInRoI = m_phys->mu_muid_L1_moreCandInRoI;
	mu_muid_L1_moreCandInSector = m_phys->mu_muid_L1_moreCandInSector;
	mu_muid_L1_source = m_phys->mu_muid_L1_source;
	mu_muid_L1_hemisphere = m_phys->mu_muid_L1_hemisphere;
	mu_muid_L1_matched = m_phys->mu_muid_L1_matched;

	/*---------------------------*/
	/*---*/ m_tree->Fill(); /*---*/
	/*---------------------------*/
}

void offlineTree::write()
{
	m_treeFile->cd();
	m_tree->Write();
}
