/* * * * * * * * * * * */
/* created by Naom Hod */
/* noam.hod@cern.ch    */
/* noam.com@gmail.com  */
/* on 23/07/2010 11:24 */
/* * * * * * * * * * * */

#include "digestTree.h"

digestTree::digestTree()
{

}

digestTree::~digestTree()
{

}

digestTree::digestTree(offlinePhysics* offPhys, mcOfflinePhysics* mcOffPhys, TFile* treeFile)
{
	m_offPhys   = offPhys;
	m_mcOffPhys = mcOffPhys;

	m_treeFile = treeFile;

	m_treeFile->cd();

	m_tree = new TTree("digest", "digest");

	m_tree->SetMaxTreeSize(100000000); // 100Mb per file
	
	setBranches();
}

TTree* digestTree::getTree()
{
	return m_tree;
}

void digestTree::setBranches()
{	
	// external
	m_tree->Branch( "isGRL",    &isGRL );
	m_tree->Branch( "period",   &period );
	m_tree->Branch( "triggers", &triggers );

	// run variables branches
	m_tree->Branch( "RunNumber",   &RunNumber );
	m_tree->Branch( "lbn",         &lbn );
	m_tree->Branch( "EventNumber", &EventNumber );

	
	// L1 triggers
	m_tree->Branch( "L1_MU0", &L1_MU0 );
	m_tree->Branch( "L1_MU10", &L1_MU10 );
	m_tree->Branch( "L1_MU15", &L1_MU15 );
	m_tree->Branch( "L1_MU20", &L1_MU20 );
	m_tree->Branch( "L1_MU6", &L1_MU6 );
	// EF triggers
	m_tree->Branch( "EF_mu10", &EF_mu10 );
	m_tree->Branch( "EF_mu10_MG", &EF_mu10_MG );
	m_tree->Branch( "EF_mu10_MSonly", &EF_mu10_MSonly );
	m_tree->Branch( "EF_mu10_MSonly_tight", &EF_mu10_MSonly_tight );
	m_tree->Branch( "EF_mu10_NoAlg", &EF_mu10_NoAlg );
	m_tree->Branch( "EF_mu10_tight", &EF_mu10_tight );
	m_tree->Branch( "EF_mu10i_loose", &EF_mu10i_loose );
	m_tree->Branch( "EF_mu13", &EF_mu13 );
	m_tree->Branch( "EF_mu13_MG", &EF_mu13_MG );
	m_tree->Branch( "EF_mu13_MG_tight", &EF_mu13_MG_tight );
	m_tree->Branch( "EF_mu13_tight", &EF_mu13_tight );
	m_tree->Branch( "EF_mu15", &EF_mu15 );
	m_tree->Branch( "EF_mu15_NoAlg", &EF_mu15_NoAlg );
	m_tree->Branch( "EF_mu20", &EF_mu20 );
	m_tree->Branch( "EF_mu20_MSonly", &EF_mu20_MSonly );
	m_tree->Branch( "EF_mu20_NoAlg", &EF_mu20_NoAlg );
	m_tree->Branch( "EF_mu20_slow", &EF_mu20_slow );
	m_tree->Branch( "EF_mu30_MSonly", &EF_mu30_MSonly );
	m_tree->Branch( "EF_mu4", &EF_mu4 );
	m_tree->Branch( "EF_mu40_MSonly", &EF_mu40_MSonly );
	
	// mu_staco
	m_tree->Branch( "mu_staco_n",         &mu_staco_n );
	m_tree->Branch( "mu_staco_px",        &mu_staco_px );
	m_tree->Branch( "mu_staco_py",        &mu_staco_py );
	m_tree->Branch( "mu_staco_pz",        &mu_staco_pz );
	m_tree->Branch( "mu_staco_E",         &mu_staco_E );
	m_tree->Branch( "mu_staco_m",         &mu_staco_m );
	m_tree->Branch( "mu_staco_charge",    &mu_staco_charge );
	m_tree->Branch( "mu_staco_pt",        &mu_staco_pt );
	m_tree->Branch( "mu_staco_ptcone20",  &mu_staco_ptcone20 );
	m_tree->Branch( "mu_staco_ptcone30",  &mu_staco_ptcone30 );
	m_tree->Branch( "mu_staco_ptcone40",  &mu_staco_ptcone40 );
	m_tree->Branch( "mu_staco_eta",       &mu_staco_eta );
	m_tree->Branch( "mu_staco_phi",       &mu_staco_phi );
	m_tree->Branch( "mu_staco_d0_exPV",   &mu_staco_d0_exPV );
	m_tree->Branch( "mu_staco_z0_exPV",   &mu_staco_z0_exPV );
	m_tree->Branch( "mu_staco_allauthor", &mu_staco_allauthor );
	m_tree->Branch( "mu_staco_author",    &mu_staco_author);
	m_tree->Branch( "mu_staco_matchchi2", &mu_staco_matchchi2);
	m_tree->Branch( "mu_staco_matchndof", &mu_staco_matchndof);
	m_tree->Branch( "mu_staco_me_qoverp",       &mu_staco_me_qoverp );
	m_tree->Branch( "mu_staco_id_qoverp",       &mu_staco_id_qoverp );
	m_tree->Branch( "mu_staco_me_theta",        &mu_staco_me_theta );
	m_tree->Branch( "mu_staco_id_theta",        &mu_staco_id_theta );
	m_tree->Branch( "mu_staco_isCombinedMuon",  &mu_staco_isCombinedMuon );
	m_tree->Branch( "mu_staco_nSCTHits",        &mu_staco_nSCTHits );
	m_tree->Branch( "mu_staco_nPixHits",        &mu_staco_nPixHits );
	m_tree->Branch( "mu_staco_nMDTBIHits",        &mu_staco_nMDTBIHits );
	m_tree->Branch( "mu_staco_nMDTBMHits",        &mu_staco_nMDTBMHits );
	m_tree->Branch( "mu_staco_nMDTBOHits",        &mu_staco_nMDTBOHits );
	m_tree->Branch( "mu_staco_nMDTBEEHits",       &mu_staco_nMDTBEEHits );
	m_tree->Branch( "mu_staco_nMDTBIS78Hits",     &mu_staco_nMDTBIS78Hits );
	m_tree->Branch( "mu_staco_nMDTEIHits",        &mu_staco_nMDTEIHits );
	m_tree->Branch( "mu_staco_nMDTEMHits",        &mu_staco_nMDTEMHits );
	m_tree->Branch( "mu_staco_nMDTEOHits",        &mu_staco_nMDTEOHits );
	m_tree->Branch( "mu_staco_nMDTEEHits",        &mu_staco_nMDTEEHits );
	m_tree->Branch( "mu_staco_nRPCLayer1EtaHits", &mu_staco_nRPCLayer1EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer2EtaHits", &mu_staco_nRPCLayer2EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer3EtaHits", &mu_staco_nRPCLayer3EtaHits );
	m_tree->Branch( "mu_staco_nRPCLayer1PhiHits", &mu_staco_nRPCLayer1PhiHits );
	m_tree->Branch( "mu_staco_nRPCLayer2PhiHits", &mu_staco_nRPCLayer2PhiHits );
	m_tree->Branch( "mu_staco_nRPCLayer3PhiHits", &mu_staco_nRPCLayer3PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer1EtaHits", &mu_staco_nTGCLayer1EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer2EtaHits", &mu_staco_nTGCLayer2EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer3EtaHits", &mu_staco_nTGCLayer3EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer4EtaHits", &mu_staco_nTGCLayer4EtaHits );
	m_tree->Branch( "mu_staco_nTGCLayer1PhiHits", &mu_staco_nTGCLayer1PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer2PhiHits", &mu_staco_nTGCLayer2PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer3PhiHits", &mu_staco_nTGCLayer3PhiHits );
	m_tree->Branch( "mu_staco_nTGCLayer4PhiHits", &mu_staco_nTGCLayer4PhiHits );
	
	m_tree->Branch( "mu_staco_etcone20", &mu_staco_etcone20 );
	m_tree->Branch( "mu_staco_etcone30", &mu_staco_etcone30 );
	m_tree->Branch( "mu_staco_etcone40", &mu_staco_etcone40 );
	m_tree->Branch( "mu_staco_nucone20", &mu_staco_nucone20 );
	m_tree->Branch( "mu_staco_nucone30", &mu_staco_nucone30 );
	m_tree->Branch( "mu_staco_nucone40", &mu_staco_nucone40 );
	m_tree->Branch( "mu_staco_energyLossPar", &mu_staco_energyLossPar );
	m_tree->Branch( "mu_staco_energyLossErr", &mu_staco_energyLossErr );
	m_tree->Branch( "mu_staco_bestMatch", &mu_staco_bestMatch );
	m_tree->Branch( "mu_staco_isStandAloneMuon", &mu_staco_isStandAloneMuon );
	m_tree->Branch( "mu_staco_isLowPtReconstructedMuon", &mu_staco_isLowPtReconstructedMuon );
	m_tree->Branch( "mu_staco_loose", &mu_staco_loose );
	m_tree->Branch( "mu_staco_medium", &mu_staco_medium );
	m_tree->Branch( "mu_staco_tight", &mu_staco_tight );
	m_tree->Branch( "mu_staco_phi_exPV", &mu_staco_phi_exPV );
	m_tree->Branch( "mu_staco_theta_exPV", &mu_staco_theta_exPV );
	m_tree->Branch( "mu_staco_qoverp_exPV", &mu_staco_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_d0_exPV", &mu_staco_cov_d0_exPV );
	m_tree->Branch( "mu_staco_cov_z0_exPV", &mu_staco_cov_z0_exPV );
	m_tree->Branch( "mu_staco_cov_phi_exPV", &mu_staco_cov_phi_exPV );
	m_tree->Branch( "mu_staco_cov_theta_exPV", &mu_staco_cov_theta_exPV );
	m_tree->Branch( "mu_staco_cov_qoverp_exPV", &mu_staco_cov_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_d0_z0_exPV", &mu_staco_cov_d0_z0_exPV );
	m_tree->Branch( "mu_staco_cov_d0_phi_exPV", &mu_staco_cov_d0_phi_exPV );
	m_tree->Branch( "mu_staco_cov_d0_theta_exPV", &mu_staco_cov_d0_theta_exPV );
	m_tree->Branch( "mu_staco_cov_d0_qoverp_exPV", &mu_staco_cov_d0_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_z0_phi_exPV", &mu_staco_cov_z0_phi_exPV );
	m_tree->Branch( "mu_staco_cov_z0_theta_exPV", &mu_staco_cov_z0_theta_exPV );
	m_tree->Branch( "mu_staco_cov_z0_qoverp_exPV", &mu_staco_cov_z0_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_phi_theta_exPV", &mu_staco_cov_phi_theta_exPV );
	m_tree->Branch( "mu_staco_cov_phi_qoverp_exPV", &mu_staco_cov_phi_qoverp_exPV );
	m_tree->Branch( "mu_staco_cov_theta_qoverp_exPV", &mu_staco_cov_theta_qoverp_exPV );
	m_tree->Branch( "mu_staco_ms_d0", &mu_staco_ms_d0 );
	m_tree->Branch( "mu_staco_ms_z0", &mu_staco_ms_z0 );
	m_tree->Branch( "mu_staco_ms_phi", &mu_staco_ms_phi );
	m_tree->Branch( "mu_staco_ms_theta", &mu_staco_ms_theta );
	m_tree->Branch( "mu_staco_ms_qoverp", &mu_staco_ms_qoverp );
	m_tree->Branch( "mu_staco_id_d0", &mu_staco_id_d0 );
	m_tree->Branch( "mu_staco_id_z0", &mu_staco_id_z0 );
	m_tree->Branch( "mu_staco_id_phi", &mu_staco_id_phi );
	m_tree->Branch( "mu_staco_me_d0", &mu_staco_me_d0 );
	m_tree->Branch( "mu_staco_me_z0", &mu_staco_me_z0 );
	m_tree->Branch( "mu_staco_me_phi", &mu_staco_me_phi );
	m_tree->Branch( "mu_staco_ie_d0", &mu_staco_ie_d0 );
	m_tree->Branch( "mu_staco_ie_z0", &mu_staco_ie_z0 );
	m_tree->Branch( "mu_staco_ie_phi", &mu_staco_ie_phi );
	m_tree->Branch( "mu_staco_ie_theta", &mu_staco_ie_theta );
	m_tree->Branch( "mu_staco_ie_qoverp", &mu_staco_ie_qoverp );
	m_tree->Branch( "mu_staco_nBLHits", &mu_staco_nBLHits );
	m_tree->Branch( "mu_staco_nTRTHighTHits", &mu_staco_nTRTHighTHits );
	m_tree->Branch( "mu_staco_nBLSharedHits", &mu_staco_nBLSharedHits );
	m_tree->Branch( "mu_staco_nPixSharedHits", &mu_staco_nPixSharedHits );
	m_tree->Branch( "mu_staco_nPixHoles", &mu_staco_nPixHoles );
	m_tree->Branch( "mu_staco_nSCTSharedHits", &mu_staco_nSCTSharedHits );
	m_tree->Branch( "mu_staco_nSCTHoles", &mu_staco_nSCTHoles );
	m_tree->Branch( "mu_staco_nTRTOutliers", &mu_staco_nTRTOutliers );
	m_tree->Branch( "mu_staco_nTRTHighTOutliers", &mu_staco_nTRTHighTOutliers );
	m_tree->Branch( "mu_staco_nMDTHits", &mu_staco_nMDTHits );
	m_tree->Branch( "mu_staco_nMDTHoles", &mu_staco_nMDTHoles );
	m_tree->Branch( "mu_staco_nCSCEtaHits", &mu_staco_nCSCEtaHits );
	m_tree->Branch( "mu_staco_nCSCEtaHoles", &mu_staco_nCSCEtaHoles );
	m_tree->Branch( "mu_staco_nCSCPhiHits", &mu_staco_nCSCPhiHits );
	m_tree->Branch( "mu_staco_nCSCPhiHoles", &mu_staco_nCSCPhiHoles );
	m_tree->Branch( "mu_staco_nRPCEtaHits", &mu_staco_nRPCEtaHits );
	m_tree->Branch( "mu_staco_nRPCEtaHoles", &mu_staco_nRPCEtaHoles );
	m_tree->Branch( "mu_staco_nRPCPhiHits", &mu_staco_nRPCPhiHits );
	m_tree->Branch( "mu_staco_nRPCPhiHoles", &mu_staco_nRPCPhiHoles );
	m_tree->Branch( "mu_staco_nTGCEtaHits", &mu_staco_nTGCEtaHits );
	m_tree->Branch( "mu_staco_nTGCEtaHoles", &mu_staco_nTGCEtaHoles );
	m_tree->Branch( "mu_staco_nTGCPhiHits", &mu_staco_nTGCPhiHits );
	m_tree->Branch( "mu_staco_nTGCPhiHoles", &mu_staco_nTGCPhiHoles );
	m_tree->Branch( "mu_staco_nGangedPixels", &mu_staco_nGangedPixels );
	m_tree->Branch( "mu_staco_nOutliersOnTrack", &mu_staco_nOutliersOnTrack );
	m_tree->Branch( "mu_staco_barrelSectors", &mu_staco_barrelSectors );
	m_tree->Branch( "mu_staco_endcapSectors", &mu_staco_endcapSectors );
	m_tree->Branch( "mu_staco_trackd0", &mu_staco_trackd0 );
	m_tree->Branch( "mu_staco_trackz0", &mu_staco_trackz0 );
	m_tree->Branch( "mu_staco_trackphi", &mu_staco_trackphi );
	m_tree->Branch( "mu_staco_tracktheta", &mu_staco_tracktheta );
	m_tree->Branch( "mu_staco_trackqoverp", &mu_staco_trackqoverp );
	m_tree->Branch( "mu_staco_trackcov_d0", &mu_staco_trackcov_d0 );
	m_tree->Branch( "mu_staco_trackcov_z0", &mu_staco_trackcov_z0 );
	m_tree->Branch( "mu_staco_trackcov_phi", &mu_staco_trackcov_phi );
	m_tree->Branch( "mu_staco_trackcov_theta", &mu_staco_trackcov_theta );
	m_tree->Branch( "mu_staco_trackcov_qoverp", &mu_staco_trackcov_qoverp );
	m_tree->Branch( "mu_staco_trackcov_d0_z0", &mu_staco_trackcov_d0_z0 );
	m_tree->Branch( "mu_staco_trackcov_d0_phi", &mu_staco_trackcov_d0_phi );
	m_tree->Branch( "mu_staco_trackcov_d0_theta", &mu_staco_trackcov_d0_theta );
	m_tree->Branch( "mu_staco_trackcov_d0_qoverp", &mu_staco_trackcov_d0_qoverp );
	m_tree->Branch( "mu_staco_trackcov_z0_phi", &mu_staco_trackcov_z0_phi );
	m_tree->Branch( "mu_staco_trackcov_z0_theta", &mu_staco_trackcov_z0_theta );
	m_tree->Branch( "mu_staco_trackcov_z0_qoverp", &mu_staco_trackcov_z0_qoverp );
	m_tree->Branch( "mu_staco_trackcov_phi_theta", &mu_staco_trackcov_phi_theta );
	m_tree->Branch( "mu_staco_trackcov_phi_qoverp", &mu_staco_trackcov_phi_qoverp );
	m_tree->Branch( "mu_staco_trackcov_theta_qoverp", &mu_staco_trackcov_theta_qoverp );
	m_tree->Branch( "mu_staco_trackfitchi2", &mu_staco_trackfitchi2 );
	m_tree->Branch( "mu_staco_trackfitndof", &mu_staco_trackfitndof );
	m_tree->Branch( "mu_staco_hastrack", &mu_staco_hastrack );
	m_tree->Branch( "mu_staco_EF_dr", &mu_staco_EF_dr );
	m_tree->Branch( "mu_staco_EF_cb_eta", &mu_staco_EF_cb_eta );
	m_tree->Branch( "mu_staco_EF_cb_phi", &mu_staco_EF_cb_phi );
	m_tree->Branch( "mu_staco_EF_cb_pt", &mu_staco_EF_cb_pt );
	m_tree->Branch( "mu_staco_EF_ms_eta", &mu_staco_EF_ms_eta );
	m_tree->Branch( "mu_staco_EF_ms_phi", &mu_staco_EF_ms_phi );
	m_tree->Branch( "mu_staco_EF_ms_pt", &mu_staco_EF_ms_pt );
	m_tree->Branch( "mu_staco_EF_me_eta", &mu_staco_EF_me_eta );
	m_tree->Branch( "mu_staco_EF_me_phi", &mu_staco_EF_me_phi );
	m_tree->Branch( "mu_staco_EF_me_pt", &mu_staco_EF_me_pt );
	m_tree->Branch( "mu_staco_EF_matched", &mu_staco_EF_matched );
	m_tree->Branch( "mu_staco_L2CB_dr", &mu_staco_L2CB_dr );
	m_tree->Branch( "mu_staco_L2CB_pt", &mu_staco_L2CB_pt );
	m_tree->Branch( "mu_staco_L2CB_eta", &mu_staco_L2CB_eta );
	m_tree->Branch( "mu_staco_L2CB_phi", &mu_staco_L2CB_phi );
	m_tree->Branch( "mu_staco_L2CB_id_pt", &mu_staco_L2CB_id_pt );
	m_tree->Branch( "mu_staco_L2CB_ms_pt", &mu_staco_L2CB_ms_pt );
	m_tree->Branch( "mu_staco_L2CB_nPixHits", &mu_staco_L2CB_nPixHits );
	m_tree->Branch( "mu_staco_L2CB_nSCTHits", &mu_staco_L2CB_nSCTHits );
	m_tree->Branch( "mu_staco_L2CB_nTRTHits", &mu_staco_L2CB_nTRTHits );
	m_tree->Branch( "mu_staco_L2CB_nTRTHighTHits", &mu_staco_L2CB_nTRTHighTHits );
	m_tree->Branch( "mu_staco_L2CB_matched", &mu_staco_L2CB_matched );
	m_tree->Branch( "mu_staco_L1_dr", &mu_staco_L1_dr );
	m_tree->Branch( "mu_staco_L1_pt", &mu_staco_L1_pt );
	m_tree->Branch( "mu_staco_L1_eta", &mu_staco_L1_eta );
	m_tree->Branch( "mu_staco_L1_phi", &mu_staco_L1_phi );
	m_tree->Branch( "mu_staco_L1_thrNumber", &mu_staco_L1_thrNumber );
	m_tree->Branch( "mu_staco_L1_RoINumber", &mu_staco_L1_RoINumber );
	m_tree->Branch( "mu_staco_L1_sectorAddress", &mu_staco_L1_sectorAddress );
	m_tree->Branch( "mu_staco_L1_firstCandidate", &mu_staco_L1_firstCandidate );
	m_tree->Branch( "mu_staco_L1_moreCandInRoI", &mu_staco_L1_moreCandInRoI );
	m_tree->Branch( "mu_staco_L1_moreCandInSector", &mu_staco_L1_moreCandInSector );
	m_tree->Branch( "mu_staco_L1_source", &mu_staco_L1_source );
	m_tree->Branch( "mu_staco_L1_hemisphere", &mu_staco_L1_hemisphere );
	m_tree->Branch( "mu_staco_L1_matched", &mu_staco_L1_matched );
	
	// mu_muid
	m_tree->Branch( "mu_muid_n",         &mu_muid_n );
	m_tree->Branch( "mu_muid_px",        &mu_muid_px );
	m_tree->Branch( "mu_muid_py",        &mu_muid_py );
	m_tree->Branch( "mu_muid_pz",        &mu_muid_pz );
	m_tree->Branch( "mu_muid_E",         &mu_muid_E );
	m_tree->Branch( "mu_muid_m",         &mu_muid_m );
	m_tree->Branch( "mu_muid_charge",    &mu_muid_charge );
	m_tree->Branch( "mu_muid_pt",        &mu_muid_pt );
	m_tree->Branch( "mu_muid_ptcone20",  &mu_muid_ptcone20 );
	m_tree->Branch( "mu_muid_ptcone30",  &mu_muid_ptcone30 );
	m_tree->Branch( "mu_muid_ptcone40",  &mu_muid_ptcone40 );
	m_tree->Branch( "mu_muid_eta",       &mu_muid_eta );
	m_tree->Branch( "mu_muid_phi",       &mu_muid_phi );
	m_tree->Branch( "mu_muid_d0_exPV",   &mu_muid_d0_exPV );
	m_tree->Branch( "mu_muid_z0_exPV",   &mu_muid_z0_exPV );
	m_tree->Branch( "mu_muid_allauthor", &mu_muid_allauthor );
	m_tree->Branch( "mu_muid_author",    &mu_muid_author);
	m_tree->Branch( "mu_muid_matchchi2", &mu_staco_matchchi2);
	m_tree->Branch( "mu_muid_matchndof", &mu_staco_matchndof);
	m_tree->Branch( "mu_muid_me_qoverp",       &mu_muid_me_qoverp );
	m_tree->Branch( "mu_muid_id_qoverp",       &mu_muid_id_qoverp );
	m_tree->Branch( "mu_muid_me_theta",        &mu_muid_me_theta );
	m_tree->Branch( "mu_muid_id_theta",        &mu_muid_id_theta );
	m_tree->Branch( "mu_muid_isCombinedMuon",  &mu_muid_isCombinedMuon );
	m_tree->Branch( "mu_muid_nSCTHits",        &mu_muid_nSCTHits );
	m_tree->Branch( "mu_muid_nPixHits",        &mu_muid_nPixHits );
	m_tree->Branch( "mu_muid_nMDTBIHits",        &mu_muid_nMDTBIHits );
	m_tree->Branch( "mu_muid_nMDTBMHits",        &mu_muid_nMDTBMHits );
	m_tree->Branch( "mu_muid_nMDTBOHits",        &mu_muid_nMDTBOHits );
	m_tree->Branch( "mu_muid_nMDTBEEHits",       &mu_muid_nMDTBEEHits );
	m_tree->Branch( "mu_muid_nMDTBIS78Hits",     &mu_muid_nMDTBIS78Hits );
	m_tree->Branch( "mu_muid_nMDTEIHits",        &mu_muid_nMDTEIHits );
	m_tree->Branch( "mu_muid_nMDTEMHits",        &mu_muid_nMDTEMHits );
	m_tree->Branch( "mu_muid_nMDTEOHits",        &mu_muid_nMDTEOHits );
	m_tree->Branch( "mu_muid_nMDTEEHits",        &mu_muid_nMDTEEHits );
	m_tree->Branch( "mu_muid_nRPCLayer1EtaHits", &mu_muid_nRPCLayer1EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer2EtaHits", &mu_muid_nRPCLayer2EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer3EtaHits", &mu_muid_nRPCLayer3EtaHits );
	m_tree->Branch( "mu_muid_nRPCLayer1PhiHits", &mu_muid_nRPCLayer1PhiHits );
	m_tree->Branch( "mu_muid_nRPCLayer2PhiHits", &mu_muid_nRPCLayer2PhiHits );
	m_tree->Branch( "mu_muid_nRPCLayer3PhiHits", &mu_muid_nRPCLayer3PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer1EtaHits", &mu_muid_nTGCLayer1EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer2EtaHits", &mu_muid_nTGCLayer2EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer3EtaHits", &mu_muid_nTGCLayer3EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer4EtaHits", &mu_muid_nTGCLayer4EtaHits );
	m_tree->Branch( "mu_muid_nTGCLayer1PhiHits", &mu_muid_nTGCLayer1PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer2PhiHits", &mu_muid_nTGCLayer2PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer3PhiHits", &mu_muid_nTGCLayer3PhiHits );
	m_tree->Branch( "mu_muid_nTGCLayer4PhiHits", &mu_muid_nTGCLayer4PhiHits );
	
	m_tree->Branch( "mu_muid_etcone20", &mu_muid_etcone20 );
	m_tree->Branch( "mu_muid_etcone30", &mu_muid_etcone30 );
	m_tree->Branch( "mu_muid_etcone40", &mu_muid_etcone40 );
	m_tree->Branch( "mu_muid_nucone20", &mu_muid_nucone20 );
	m_tree->Branch( "mu_muid_nucone30", &mu_muid_nucone30 );
	m_tree->Branch( "mu_muid_nucone40", &mu_muid_nucone40 );
	m_tree->Branch( "mu_muid_energyLossPar", &mu_muid_energyLossPar );
	m_tree->Branch( "mu_muid_energyLossErr", &mu_muid_energyLossErr );
	m_tree->Branch( "mu_muid_bestMatch", &mu_muid_bestMatch );
	m_tree->Branch( "mu_muid_isStandAloneMuon", &mu_muid_isStandAloneMuon );
	m_tree->Branch( "mu_muid_isLowPtReconstructedMuon", &mu_muid_isLowPtReconstructedMuon );
	m_tree->Branch( "mu_muid_loose", &mu_muid_loose );
	m_tree->Branch( "mu_muid_medium", &mu_muid_medium );
	m_tree->Branch( "mu_muid_tight", &mu_muid_tight );
	m_tree->Branch( "mu_muid_phi_exPV", &mu_muid_phi_exPV );
	m_tree->Branch( "mu_muid_theta_exPV", &mu_muid_theta_exPV );
	m_tree->Branch( "mu_muid_qoverp_exPV", &mu_muid_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_d0_exPV", &mu_muid_cov_d0_exPV );
	m_tree->Branch( "mu_muid_cov_z0_exPV", &mu_muid_cov_z0_exPV );
	m_tree->Branch( "mu_muid_cov_phi_exPV", &mu_muid_cov_phi_exPV );
	m_tree->Branch( "mu_muid_cov_theta_exPV", &mu_muid_cov_theta_exPV );
	m_tree->Branch( "mu_muid_cov_qoverp_exPV", &mu_muid_cov_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_d0_z0_exPV", &mu_muid_cov_d0_z0_exPV );
	m_tree->Branch( "mu_muid_cov_d0_phi_exPV", &mu_muid_cov_d0_phi_exPV );
	m_tree->Branch( "mu_muid_cov_d0_theta_exPV", &mu_muid_cov_d0_theta_exPV );
	m_tree->Branch( "mu_muid_cov_d0_qoverp_exPV", &mu_muid_cov_d0_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_z0_phi_exPV", &mu_muid_cov_z0_phi_exPV );
	m_tree->Branch( "mu_muid_cov_z0_theta_exPV", &mu_muid_cov_z0_theta_exPV );
	m_tree->Branch( "mu_muid_cov_z0_qoverp_exPV", &mu_muid_cov_z0_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_phi_theta_exPV", &mu_muid_cov_phi_theta_exPV );
	m_tree->Branch( "mu_muid_cov_phi_qoverp_exPV", &mu_muid_cov_phi_qoverp_exPV );
	m_tree->Branch( "mu_muid_cov_theta_qoverp_exPV", &mu_muid_cov_theta_qoverp_exPV );
	m_tree->Branch( "mu_muid_ms_d0", &mu_muid_ms_d0 );
	m_tree->Branch( "mu_muid_ms_z0", &mu_muid_ms_z0 );
	m_tree->Branch( "mu_muid_ms_phi", &mu_muid_ms_phi );
	m_tree->Branch( "mu_muid_ms_theta", &mu_muid_ms_theta );
	m_tree->Branch( "mu_muid_ms_qoverp", &mu_muid_ms_qoverp );
	m_tree->Branch( "mu_muid_id_d0", &mu_muid_id_d0 );
	m_tree->Branch( "mu_muid_id_z0", &mu_muid_id_z0 );
	m_tree->Branch( "mu_muid_id_phi", &mu_muid_id_phi );
	m_tree->Branch( "mu_muid_me_d0", &mu_muid_me_d0 );
	m_tree->Branch( "mu_muid_me_z0", &mu_muid_me_z0 );
	m_tree->Branch( "mu_muid_me_phi", &mu_muid_me_phi );
	m_tree->Branch( "mu_muid_ie_d0", &mu_muid_ie_d0 );
	m_tree->Branch( "mu_muid_ie_z0", &mu_muid_ie_z0 );
	m_tree->Branch( "mu_muid_ie_phi", &mu_muid_ie_phi );
	m_tree->Branch( "mu_muid_ie_theta", &mu_muid_ie_theta );
	m_tree->Branch( "mu_muid_ie_qoverp", &mu_muid_ie_qoverp );
	m_tree->Branch( "mu_muid_nBLHits", &mu_muid_nBLHits );
	m_tree->Branch( "mu_muid_nTRTHighTHits", &mu_muid_nTRTHighTHits );
	m_tree->Branch( "mu_muid_nBLSharedHits", &mu_muid_nBLSharedHits );
	m_tree->Branch( "mu_muid_nPixSharedHits", &mu_muid_nPixSharedHits );
	m_tree->Branch( "mu_muid_nPixHoles", &mu_muid_nPixHoles );
	m_tree->Branch( "mu_muid_nSCTSharedHits", &mu_muid_nSCTSharedHits );
	m_tree->Branch( "mu_muid_nSCTHoles", &mu_muid_nSCTHoles );
	m_tree->Branch( "mu_muid_nTRTOutliers", &mu_muid_nTRTOutliers );
	m_tree->Branch( "mu_muid_nTRTHighTOutliers", &mu_muid_nTRTHighTOutliers );
	m_tree->Branch( "mu_muid_nMDTHits", &mu_muid_nMDTHits );
	m_tree->Branch( "mu_muid_nMDTHoles", &mu_muid_nMDTHoles );
	m_tree->Branch( "mu_muid_nCSCEtaHits", &mu_muid_nCSCEtaHits );
	m_tree->Branch( "mu_muid_nCSCEtaHoles", &mu_muid_nCSCEtaHoles );
	m_tree->Branch( "mu_muid_nCSCPhiHits", &mu_muid_nCSCPhiHits );
	m_tree->Branch( "mu_muid_nCSCPhiHoles", &mu_muid_nCSCPhiHoles );
	m_tree->Branch( "mu_muid_nRPCEtaHits", &mu_muid_nRPCEtaHits );
	m_tree->Branch( "mu_muid_nRPCEtaHoles", &mu_muid_nRPCEtaHoles );
	m_tree->Branch( "mu_muid_nRPCPhiHits", &mu_muid_nRPCPhiHits );
	m_tree->Branch( "mu_muid_nRPCPhiHoles", &mu_muid_nRPCPhiHoles );
	m_tree->Branch( "mu_muid_nTGCEtaHits", &mu_muid_nTGCEtaHits );
	m_tree->Branch( "mu_muid_nTGCEtaHoles", &mu_muid_nTGCEtaHoles );
	m_tree->Branch( "mu_muid_nTGCPhiHits", &mu_muid_nTGCPhiHits );
	m_tree->Branch( "mu_muid_nTGCPhiHoles", &mu_muid_nTGCPhiHoles );
	m_tree->Branch( "mu_muid_nGangedPixels", &mu_muid_nGangedPixels );
	m_tree->Branch( "mu_muid_nOutliersOnTrack", &mu_muid_nOutliersOnTrack );
	m_tree->Branch( "mu_muid_barrelSectors", &mu_muid_barrelSectors );
	m_tree->Branch( "mu_muid_endcapSectors", &mu_muid_endcapSectors );
	m_tree->Branch( "mu_muid_trackd0", &mu_muid_trackd0 );
	m_tree->Branch( "mu_muid_trackz0", &mu_muid_trackz0 );
	m_tree->Branch( "mu_muid_trackphi", &mu_muid_trackphi );
	m_tree->Branch( "mu_muid_tracktheta", &mu_muid_tracktheta );
	m_tree->Branch( "mu_muid_trackqoverp", &mu_muid_trackqoverp );
	m_tree->Branch( "mu_muid_trackcov_d0", &mu_muid_trackcov_d0 );
	m_tree->Branch( "mu_muid_trackcov_z0", &mu_muid_trackcov_z0 );
	m_tree->Branch( "mu_muid_trackcov_phi", &mu_muid_trackcov_phi );
	m_tree->Branch( "mu_muid_trackcov_theta", &mu_muid_trackcov_theta );
	m_tree->Branch( "mu_muid_trackcov_qoverp", &mu_muid_trackcov_qoverp );
	m_tree->Branch( "mu_muid_trackcov_d0_z0", &mu_muid_trackcov_d0_z0 );
	m_tree->Branch( "mu_muid_trackcov_d0_phi", &mu_muid_trackcov_d0_phi );
	m_tree->Branch( "mu_muid_trackcov_d0_theta", &mu_muid_trackcov_d0_theta );
	m_tree->Branch( "mu_muid_trackcov_d0_qoverp", &mu_muid_trackcov_d0_qoverp );
	m_tree->Branch( "mu_muid_trackcov_z0_phi", &mu_muid_trackcov_z0_phi );
	m_tree->Branch( "mu_muid_trackcov_z0_theta", &mu_muid_trackcov_z0_theta );
	m_tree->Branch( "mu_muid_trackcov_z0_qoverp", &mu_muid_trackcov_z0_qoverp );
	m_tree->Branch( "mu_muid_trackcov_phi_theta", &mu_muid_trackcov_phi_theta );
	m_tree->Branch( "mu_muid_trackcov_phi_qoverp", &mu_muid_trackcov_phi_qoverp );
	m_tree->Branch( "mu_muid_trackcov_theta_qoverp", &mu_muid_trackcov_theta_qoverp );
	m_tree->Branch( "mu_muid_trackfitchi2", &mu_muid_trackfitchi2 );
	m_tree->Branch( "mu_muid_trackfitndof", &mu_muid_trackfitndof );
	m_tree->Branch( "mu_muid_hastrack", &mu_muid_hastrack );
	m_tree->Branch( "mu_muid_EF_dr", &mu_muid_EF_dr );
	m_tree->Branch( "mu_muid_EF_cb_eta", &mu_muid_EF_cb_eta );
	m_tree->Branch( "mu_muid_EF_cb_phi", &mu_muid_EF_cb_phi );
	m_tree->Branch( "mu_muid_EF_cb_pt", &mu_muid_EF_cb_pt );
	m_tree->Branch( "mu_muid_EF_ms_eta", &mu_muid_EF_ms_eta );
	m_tree->Branch( "mu_muid_EF_ms_phi", &mu_muid_EF_ms_phi );
	m_tree->Branch( "mu_muid_EF_ms_pt", &mu_muid_EF_ms_pt );
	m_tree->Branch( "mu_muid_EF_me_eta", &mu_muid_EF_me_eta );
	m_tree->Branch( "mu_muid_EF_me_phi", &mu_muid_EF_me_phi );
	m_tree->Branch( "mu_muid_EF_me_pt", &mu_muid_EF_me_pt );
	m_tree->Branch( "mu_muid_EF_matched", &mu_muid_EF_matched );
	m_tree->Branch( "mu_muid_L2CB_dr", &mu_muid_L2CB_dr );
	m_tree->Branch( "mu_muid_L2CB_pt", &mu_muid_L2CB_pt );
	m_tree->Branch( "mu_muid_L2CB_eta", &mu_muid_L2CB_eta );
	m_tree->Branch( "mu_muid_L2CB_phi", &mu_muid_L2CB_phi );
	m_tree->Branch( "mu_muid_L2CB_id_pt", &mu_muid_L2CB_id_pt );
	m_tree->Branch( "mu_muid_L2CB_ms_pt", &mu_muid_L2CB_ms_pt );
	m_tree->Branch( "mu_muid_L2CB_nPixHits", &mu_muid_L2CB_nPixHits );
	m_tree->Branch( "mu_muid_L2CB_nSCTHits", &mu_muid_L2CB_nSCTHits );
	m_tree->Branch( "mu_muid_L2CB_nTRTHits", &mu_muid_L2CB_nTRTHits );
	m_tree->Branch( "mu_muid_L2CB_nTRTHighTHits", &mu_muid_L2CB_nTRTHighTHits );
	m_tree->Branch( "mu_muid_L2CB_matched", &mu_muid_L2CB_matched );
	m_tree->Branch( "mu_muid_L1_dr", &mu_muid_L1_dr );
	m_tree->Branch( "mu_muid_L1_pt", &mu_muid_L1_pt );
	m_tree->Branch( "mu_muid_L1_eta", &mu_muid_L1_eta );
	m_tree->Branch( "mu_muid_L1_phi", &mu_muid_L1_phi );
	m_tree->Branch( "mu_muid_L1_thrNumber", &mu_muid_L1_thrNumber );
	m_tree->Branch( "mu_muid_L1_RoINumber", &mu_muid_L1_RoINumber );
	m_tree->Branch( "mu_muid_L1_sectorAddress", &mu_muid_L1_sectorAddress );
	m_tree->Branch( "mu_muid_L1_firstCandidate", &mu_muid_L1_firstCandidate );
	m_tree->Branch( "mu_muid_L1_moreCandInRoI", &mu_muid_L1_moreCandInRoI );
	m_tree->Branch( "mu_muid_L1_moreCandInSector", &mu_muid_L1_moreCandInSector );
	m_tree->Branch( "mu_muid_L1_source", &mu_muid_L1_source );
	m_tree->Branch( "mu_muid_L1_hemisphere", &mu_muid_L1_hemisphere );
	m_tree->Branch( "mu_muid_L1_matched", &mu_muid_L1_matched );
	
	// vertex branches
	m_tree->Branch( "vxp_n",       &vxp_n );
	m_tree->Branch( "vxp_nTracks", &vxp_nTracks );
	m_tree->Branch( "vxp_type",    &vxp_type );
	m_tree->Branch( "vxp_z",       &vxp_z );
	m_tree->Branch( "vxp_z_err",   &vxp_z_err );	
}

void digestTree::fill(int GRL)
{
	isGRL = GRL;
	
	if(m_mcOffPhys==NULL  &&  m_offPhys!=NULL)
	{
		// external
		//period   = m_offPhys->period;
		period = "NOAM ???";
		triggers = m_offPhys->triggers;
	
		// fill run branches
		RunNumber   = m_offPhys->RunNumber;
		lbn         = m_offPhys->lbn;
		EventNumber = m_offPhys->EventNumber;
		
		// L1 triggers
		L1_MU0 = m_offPhys->L1_MU0;
		L1_MU10 = m_offPhys->L1_MU10;
		L1_MU15 = m_offPhys->L1_MU15;
		L1_MU20 = m_offPhys->L1_MU20;
		L1_MU6 = m_offPhys->L1_MU6; 
		
		// EF triggers
		EF_mu10 = m_offPhys->EF_mu10;
		EF_mu10_MG = m_offPhys->EF_mu10_MG;
		EF_mu10_MSonly = m_offPhys->EF_mu10_MSonly;
		EF_mu10_MSonly_tight = m_offPhys->EF_mu10_MSonly_tight;
		EF_mu10_NoAlg = m_offPhys->EF_mu10_NoAlg;
		EF_mu10_tight = m_offPhys->EF_mu10_tight;
		EF_mu10i_loose = m_offPhys->EF_mu10i_loose;
		EF_mu13 = m_offPhys->EF_mu13;
		EF_mu13_MG = m_offPhys->EF_mu13_MG;
		EF_mu13_MG_tight = m_offPhys->EF_mu13_MG_tight;
		EF_mu13_tight = m_offPhys->EF_mu13_tight;
		EF_mu15 = m_offPhys->EF_mu15;
		EF_mu15_NoAlg = m_offPhys->EF_mu15_NoAlg;
		EF_mu20 = m_offPhys->EF_mu20;
		EF_mu20_MSonly = m_offPhys->EF_mu20_MSonly;
		EF_mu20_NoAlg = m_offPhys->EF_mu20_NoAlg;
		EF_mu20_slow = m_offPhys->EF_mu20_slow;
		EF_mu30_MSonly = m_offPhys->EF_mu30_MSonly;
		EF_mu4 = m_offPhys->EF_mu4;
		EF_mu40_MSonly = m_offPhys->EF_mu40_MSonly;
		
		// staco
		mu_staco_n        = m_offPhys->mu_staco_n;
		mu_staco_px       = m_offPhys->mu_staco_px;
		mu_staco_py       = m_offPhys->mu_staco_py;
		mu_staco_pz       = m_offPhys->mu_staco_pz;
		mu_staco_E        = m_offPhys->mu_staco_E;
		mu_staco_m        = m_offPhys->mu_staco_m;
		mu_staco_charge   = m_offPhys->mu_staco_charge;
		mu_staco_pt       = m_offPhys->mu_staco_pt;
		mu_staco_ptcone20 = m_offPhys->mu_staco_ptcone20;
		mu_staco_ptcone30 = m_offPhys->mu_staco_ptcone30;
		mu_staco_ptcone40 = m_offPhys->mu_staco_ptcone40;
		mu_staco_eta      = m_offPhys->mu_staco_eta;
		mu_staco_phi      = m_offPhys->mu_staco_phi;
		mu_staco_d0_exPV  = m_offPhys->mu_staco_d0_exPV;
		mu_staco_z0_exPV  = m_offPhys->mu_staco_z0_exPV;
		mu_staco_allauthor= m_offPhys->mu_staco_allauthor;
		mu_staco_author   = m_offPhys->mu_staco_author;
		mu_staco_matchchi2   = m_offPhys->mu_staco_matchchi2;
		mu_staco_matchndof   = m_offPhys->mu_staco_matchndof;
		mu_staco_me_qoverp = m_offPhys->mu_staco_me_qoverp;
		mu_staco_id_qoverp = m_offPhys->mu_staco_id_qoverp;
		mu_staco_me_theta  = m_offPhys->mu_staco_me_theta;
		mu_staco_id_theta  = m_offPhys->mu_staco_id_theta;
		mu_staco_isCombinedMuon = m_offPhys->mu_staco_isCombinedMuon;
		mu_staco_nSCTHits = m_offPhys->mu_staco_nSCTHits;
		mu_staco_nPixHits = m_offPhys->mu_staco_nPixHits;
		
		mu_staco_nMDTBIHits =      m_offPhys->mu_staco_nMDTBIHits;
		mu_staco_nMDTBMHits =      m_offPhys->mu_staco_nMDTBMHits;
		mu_staco_nMDTBOHits =      m_offPhys->mu_staco_nMDTBOHits;
		mu_staco_nMDTBEEHits =     m_offPhys->mu_staco_nMDTBEEHits;
		mu_staco_nMDTBIS78Hits =   m_offPhys->mu_staco_nMDTBIS78Hits;
		mu_staco_nMDTEIHits    =   m_offPhys->mu_staco_nMDTEIHits;
		mu_staco_nMDTEMHits    =   m_offPhys->mu_staco_nMDTEMHits;
		mu_staco_nMDTEOHits    =   m_offPhys->mu_staco_nMDTEOHits;
		mu_staco_nMDTEEHits    =   m_offPhys->mu_staco_nMDTEEHits;
		mu_staco_nRPCLayer1EtaHits = m_offPhys->mu_staco_nRPCLayer1EtaHits;
		mu_staco_nRPCLayer2EtaHits = m_offPhys->mu_staco_nRPCLayer2EtaHits;
		mu_staco_nRPCLayer3EtaHits = m_offPhys->mu_staco_nRPCLayer3EtaHits;
		mu_staco_nRPCLayer1PhiHits = m_offPhys->mu_staco_nRPCLayer1PhiHits;
		mu_staco_nRPCLayer2PhiHits = m_offPhys->mu_staco_nRPCLayer2PhiHits;
		mu_staco_nRPCLayer3PhiHits = m_offPhys->mu_staco_nRPCLayer3PhiHits;
		mu_staco_nTGCLayer1EtaHits = m_offPhys->mu_staco_nTGCLayer1EtaHits;
		mu_staco_nTGCLayer2EtaHits = m_offPhys->mu_staco_nTGCLayer2EtaHits;
		mu_staco_nTGCLayer3EtaHits = m_offPhys->mu_staco_nTGCLayer3EtaHits;
		mu_staco_nTGCLayer4EtaHits = m_offPhys->mu_staco_nTGCLayer4EtaHits;
		mu_staco_nTGCLayer1PhiHits = m_offPhys->mu_staco_nTGCLayer1PhiHits;
		mu_staco_nTGCLayer2PhiHits = m_offPhys->mu_staco_nTGCLayer2PhiHits;
		mu_staco_nTGCLayer3PhiHits = m_offPhys->mu_staco_nTGCLayer3PhiHits;
		mu_staco_nTGCLayer4PhiHits = m_offPhys->mu_staco_nTGCLayer4PhiHits;
		
		mu_staco_etcone20 = m_offPhys->mu_staco_etcone20;
		mu_staco_etcone30 = m_offPhys->mu_staco_etcone30;
		mu_staco_etcone40 = m_offPhys->mu_staco_etcone40;
		mu_staco_nucone20 = m_offPhys->mu_staco_nucone20;
		mu_staco_nucone30 = m_offPhys->mu_staco_nucone30;
		mu_staco_nucone40 = m_offPhys->mu_staco_nucone40;
		mu_staco_energyLossPar = m_offPhys->mu_staco_energyLossPar;
		mu_staco_energyLossErr = m_offPhys->mu_staco_energyLossErr;
		mu_staco_bestMatch = m_offPhys->mu_staco_bestMatch;
		mu_staco_isStandAloneMuon = m_offPhys->mu_staco_isStandAloneMuon;
		mu_staco_isLowPtReconstructedMuon = m_offPhys->mu_staco_isLowPtReconstructedMuon;
		mu_staco_loose = m_offPhys->mu_staco_loose;
		mu_staco_medium = m_offPhys->mu_staco_medium;
		mu_staco_tight = m_offPhys->mu_staco_tight;
		mu_staco_phi_exPV = m_offPhys->mu_staco_phi_exPV;
		mu_staco_theta_exPV = m_offPhys->mu_staco_theta_exPV;
		mu_staco_qoverp_exPV = m_offPhys->mu_staco_qoverp_exPV;
		mu_staco_cov_d0_exPV = m_offPhys->mu_staco_cov_d0_exPV;
		mu_staco_cov_z0_exPV = m_offPhys->mu_staco_cov_z0_exPV;
		mu_staco_cov_phi_exPV = m_offPhys->mu_staco_cov_phi_exPV;
		mu_staco_cov_theta_exPV = m_offPhys->mu_staco_cov_theta_exPV;
		mu_staco_cov_qoverp_exPV = m_offPhys->mu_staco_cov_qoverp_exPV;
		mu_staco_cov_d0_z0_exPV = m_offPhys->mu_staco_cov_d0_z0_exPV;
		mu_staco_cov_d0_phi_exPV = m_offPhys->mu_staco_cov_d0_phi_exPV;
		mu_staco_cov_d0_theta_exPV = m_offPhys->mu_staco_cov_d0_theta_exPV;
		mu_staco_cov_d0_qoverp_exPV = m_offPhys->mu_staco_cov_d0_qoverp_exPV;
		mu_staco_cov_z0_phi_exPV = m_offPhys->mu_staco_cov_z0_phi_exPV;
		mu_staco_cov_z0_theta_exPV = m_offPhys->mu_staco_cov_z0_theta_exPV;
		mu_staco_cov_z0_qoverp_exPV = m_offPhys->mu_staco_cov_z0_qoverp_exPV;
		mu_staco_cov_phi_theta_exPV = m_offPhys->mu_staco_cov_phi_theta_exPV;
		mu_staco_cov_phi_qoverp_exPV = m_offPhys->mu_staco_cov_phi_qoverp_exPV;
		mu_staco_cov_theta_qoverp_exPV = m_offPhys->mu_staco_cov_theta_qoverp_exPV;
		mu_staco_ms_d0 = m_offPhys->mu_staco_ms_d0;
		mu_staco_ms_z0 = m_offPhys->mu_staco_ms_z0;
		mu_staco_ms_phi = m_offPhys->mu_staco_ms_phi;
		mu_staco_ms_theta = m_offPhys->mu_staco_ms_theta;
		mu_staco_ms_qoverp = m_offPhys->mu_staco_ms_qoverp;
		mu_staco_id_d0 = m_offPhys->mu_staco_id_d0;
		mu_staco_id_z0 = m_offPhys->mu_staco_id_z0;
		mu_staco_id_phi = m_offPhys->mu_staco_id_phi;
		mu_staco_me_d0 = m_offPhys->mu_staco_me_d0;
		mu_staco_me_z0 = m_offPhys->mu_staco_me_z0;
		mu_staco_me_phi = m_offPhys->mu_staco_me_phi;
		mu_staco_ie_d0 = m_offPhys->mu_staco_ie_d0;
		mu_staco_ie_z0 = m_offPhys->mu_staco_ie_z0;
		mu_staco_ie_phi = m_offPhys->mu_staco_ie_phi;
		mu_staco_ie_theta = m_offPhys->mu_staco_ie_theta;
		mu_staco_ie_qoverp = m_offPhys->mu_staco_ie_qoverp;
		mu_staco_nBLHits = m_offPhys->mu_staco_nBLHits;
		mu_staco_nTRTHighTHits = m_offPhys->mu_staco_nTRTHighTHits;
		mu_staco_nBLSharedHits = m_offPhys->mu_staco_nBLSharedHits;
		mu_staco_nPixSharedHits = m_offPhys->mu_staco_nPixSharedHits;
		mu_staco_nPixHoles = m_offPhys->mu_staco_nPixHoles;
		mu_staco_nSCTSharedHits = m_offPhys->mu_staco_nSCTSharedHits;
		mu_staco_nSCTHoles = m_offPhys->mu_staco_nSCTHoles;
		mu_staco_nTRTOutliers = m_offPhys->mu_staco_nTRTOutliers;
		mu_staco_nTRTHighTOutliers = m_offPhys->mu_staco_nTRTHighTOutliers;
		mu_staco_nMDTHits = m_offPhys->mu_staco_nMDTHits;
		mu_staco_nMDTHoles = m_offPhys->mu_staco_nMDTHoles;
		mu_staco_nCSCEtaHits = m_offPhys->mu_staco_nCSCEtaHits;
		mu_staco_nCSCEtaHoles = m_offPhys->mu_staco_nCSCEtaHoles;
		mu_staco_nCSCPhiHits = m_offPhys->mu_staco_nCSCPhiHits;
		mu_staco_nCSCPhiHoles = m_offPhys->mu_staco_nCSCPhiHoles;
		mu_staco_nRPCEtaHits = m_offPhys->mu_staco_nRPCEtaHits;
		mu_staco_nRPCEtaHoles = m_offPhys->mu_staco_nRPCEtaHoles;
		mu_staco_nRPCPhiHits = m_offPhys->mu_staco_nRPCPhiHits;
		mu_staco_nRPCPhiHoles = m_offPhys->mu_staco_nRPCPhiHoles;
		mu_staco_nTGCEtaHits = m_offPhys->mu_staco_nTGCEtaHits;
		mu_staco_nTGCEtaHoles = m_offPhys->mu_staco_nTGCEtaHoles;
		mu_staco_nTGCPhiHits = m_offPhys->mu_staco_nTGCPhiHits;
		mu_staco_nTGCPhiHoles = m_offPhys->mu_staco_nTGCPhiHoles;
		mu_staco_nGangedPixels = m_offPhys->mu_staco_nGangedPixels;
		mu_staco_nOutliersOnTrack = m_offPhys->mu_staco_nOutliersOnTrack;
		mu_staco_barrelSectors = m_offPhys->mu_staco_barrelSectors;
		mu_staco_endcapSectors = m_offPhys->mu_staco_endcapSectors;
		mu_staco_trackd0 = m_offPhys->mu_staco_trackd0;
		mu_staco_trackz0 = m_offPhys->mu_staco_trackz0;
		mu_staco_trackphi = m_offPhys->mu_staco_trackphi;
		mu_staco_tracktheta = m_offPhys->mu_staco_tracktheta;
		mu_staco_trackqoverp = m_offPhys->mu_staco_trackqoverp;
		mu_staco_trackcov_d0 = m_offPhys->mu_staco_trackcov_d0;
		mu_staco_trackcov_z0 = m_offPhys->mu_staco_trackcov_z0;
		mu_staco_trackcov_phi = m_offPhys->mu_staco_trackcov_phi;
		mu_staco_trackcov_theta = m_offPhys->mu_staco_trackcov_theta;
		mu_staco_trackcov_qoverp = m_offPhys->mu_staco_trackcov_qoverp;
		mu_staco_trackcov_d0_z0 = m_offPhys->mu_staco_trackcov_d0_z0;
		mu_staco_trackcov_d0_phi = m_offPhys->mu_staco_trackcov_d0_phi;
		mu_staco_trackcov_d0_theta = m_offPhys->mu_staco_trackcov_d0_theta;
		mu_staco_trackcov_d0_qoverp = m_offPhys->mu_staco_trackcov_d0_qoverp;
		mu_staco_trackcov_z0_phi = m_offPhys->mu_staco_trackcov_z0_phi;
		mu_staco_trackcov_z0_theta = m_offPhys->mu_staco_trackcov_z0_theta;
		mu_staco_trackcov_z0_qoverp = m_offPhys->mu_staco_trackcov_z0_qoverp;
		mu_staco_trackcov_phi_theta = m_offPhys->mu_staco_trackcov_phi_theta;
		mu_staco_trackcov_phi_qoverp = m_offPhys->mu_staco_trackcov_phi_qoverp;
		mu_staco_trackcov_theta_qoverp = m_offPhys->mu_staco_trackcov_theta_qoverp;
		mu_staco_trackfitchi2 = m_offPhys->mu_staco_trackfitchi2;
		mu_staco_trackfitndof = m_offPhys->mu_staco_trackfitndof;
		mu_staco_hastrack = m_offPhys->mu_staco_hastrack;
		mu_staco_EF_dr = m_offPhys->mu_staco_EF_dr;
		mu_staco_EF_cb_eta = m_offPhys->mu_staco_EF_cb_eta;
		mu_staco_EF_cb_phi = m_offPhys->mu_staco_EF_cb_phi;
		mu_staco_EF_cb_pt = m_offPhys->mu_staco_EF_cb_pt;
		mu_staco_EF_ms_eta = m_offPhys->mu_staco_EF_ms_eta;
		mu_staco_EF_ms_phi = m_offPhys->mu_staco_EF_ms_phi;
		mu_staco_EF_ms_pt = m_offPhys->mu_staco_EF_ms_pt;
		mu_staco_EF_me_eta = m_offPhys->mu_staco_EF_me_eta;
		mu_staco_EF_me_phi = m_offPhys->mu_staco_EF_me_phi;
		mu_staco_EF_me_pt = m_offPhys->mu_staco_EF_me_pt;
		mu_staco_EF_matched = m_offPhys->mu_staco_EF_matched;
		mu_staco_L2CB_dr = m_offPhys->mu_staco_L2CB_dr;
		mu_staco_L2CB_pt = m_offPhys->mu_staco_L2CB_pt;
		mu_staco_L2CB_eta = m_offPhys->mu_staco_L2CB_eta;
		mu_staco_L2CB_phi = m_offPhys->mu_staco_L2CB_phi;
		mu_staco_L2CB_id_pt = m_offPhys->mu_staco_L2CB_id_pt;
		mu_staco_L2CB_ms_pt = m_offPhys->mu_staco_L2CB_ms_pt;
		mu_staco_L2CB_nPixHits = m_offPhys->mu_staco_L2CB_nPixHits;
		mu_staco_L2CB_nSCTHits = m_offPhys->mu_staco_L2CB_nSCTHits;
		mu_staco_L2CB_nTRTHits = m_offPhys->mu_staco_L2CB_nTRTHits;
		mu_staco_L2CB_nTRTHighTHits = m_offPhys->mu_staco_L2CB_nTRTHighTHits;
		mu_staco_L2CB_matched = m_offPhys->mu_staco_L2CB_matched;
		mu_staco_L1_dr = m_offPhys->mu_staco_L1_dr;
		mu_staco_L1_pt = m_offPhys->mu_staco_L1_pt;
		mu_staco_L1_eta = m_offPhys->mu_staco_L1_eta;
		mu_staco_L1_phi = m_offPhys->mu_staco_L1_phi;
		mu_staco_L1_thrNumber = m_offPhys->mu_staco_L1_thrNumber;
		mu_staco_L1_RoINumber = m_offPhys->mu_staco_L1_RoINumber;
		mu_staco_L1_sectorAddress = m_offPhys->mu_staco_L1_sectorAddress;
		mu_staco_L1_firstCandidate = m_offPhys->mu_staco_L1_firstCandidate;
		mu_staco_L1_moreCandInRoI = m_offPhys->mu_staco_L1_moreCandInRoI;
		mu_staco_L1_moreCandInSector = m_offPhys->mu_staco_L1_moreCandInSector;
		mu_staco_L1_source = m_offPhys->mu_staco_L1_source;
		mu_staco_L1_hemisphere = m_offPhys->mu_staco_L1_hemisphere;
		mu_staco_L1_matched = m_offPhys->mu_staco_L1_matched;
		
		// muid
		mu_muid_n        = m_offPhys->mu_muid_n;
		mu_muid_px       = m_offPhys->mu_muid_px;
		mu_muid_py       = m_offPhys->mu_muid_py;
		mu_muid_pz       = m_offPhys->mu_muid_pz;
		mu_muid_E        = m_offPhys->mu_muid_E;
		mu_muid_m        = m_offPhys->mu_muid_m;
		mu_muid_charge   = m_offPhys->mu_muid_charge;
		mu_muid_pt       = m_offPhys->mu_muid_pt;
		mu_muid_ptcone20 = m_offPhys->mu_muid_ptcone20;
		mu_muid_ptcone30 = m_offPhys->mu_muid_ptcone30;
		mu_muid_ptcone40 = m_offPhys->mu_muid_ptcone40;
		mu_muid_eta      = m_offPhys->mu_muid_eta;
		mu_muid_phi      = m_offPhys->mu_muid_phi;
		mu_muid_d0_exPV  = m_offPhys->mu_muid_d0_exPV;
		mu_muid_z0_exPV  = m_offPhys->mu_muid_z0_exPV;
		mu_muid_allauthor= m_offPhys->mu_muid_allauthor;
		mu_muid_author   = m_offPhys->mu_muid_author;
		mu_muid_matchchi2 = m_offPhys->mu_muid_matchchi2;
		mu_muid_matchndof = m_offPhys->mu_muid_matchndof;
		mu_muid_me_qoverp = m_offPhys->mu_muid_me_qoverp;
		mu_muid_id_qoverp = m_offPhys->mu_muid_id_qoverp;
		mu_muid_me_theta = m_offPhys->mu_muid_me_theta;
		mu_muid_id_theta = m_offPhys->mu_muid_id_theta;
		mu_muid_isCombinedMuon = m_offPhys->mu_muid_isCombinedMuon;
		mu_muid_nSCTHits = m_offPhys->mu_muid_nSCTHits;
		mu_muid_nPixHits = m_offPhys->mu_muid_nPixHits;
		mu_muid_nMDTBIHits =      m_offPhys->mu_muid_nMDTBIHits;
		mu_muid_nMDTBMHits =      m_offPhys->mu_muid_nMDTBMHits;
		mu_muid_nMDTBOHits =      m_offPhys->mu_muid_nMDTBOHits;
		mu_muid_nMDTBEEHits =     m_offPhys->mu_muid_nMDTBEEHits;
		mu_muid_nMDTBIS78Hits =   m_offPhys->mu_muid_nMDTBIS78Hits;
		mu_muid_nMDTEIHits =      m_offPhys->mu_muid_nMDTEIHits;
		mu_muid_nMDTEMHits =      m_offPhys->mu_muid_nMDTEMHits;
		mu_muid_nMDTEOHits =      m_offPhys->mu_muid_nMDTEOHits;
		mu_muid_nMDTEEHits =      m_offPhys->mu_muid_nMDTEEHits;
		
		mu_muid_nRPCLayer1EtaHits = m_offPhys->mu_muid_nRPCLayer1EtaHits;
		mu_muid_nRPCLayer2EtaHits = m_offPhys->mu_muid_nRPCLayer2EtaHits;
		mu_muid_nRPCLayer3EtaHits = m_offPhys->mu_muid_nRPCLayer3EtaHits;
		mu_muid_nRPCLayer1PhiHits = m_offPhys->mu_muid_nRPCLayer1PhiHits;
		mu_muid_nRPCLayer2PhiHits = m_offPhys->mu_muid_nRPCLayer2PhiHits;
		mu_muid_nRPCLayer3PhiHits = m_offPhys->mu_muid_nRPCLayer3PhiHits;
		mu_muid_nTGCLayer1EtaHits = m_offPhys->mu_muid_nTGCLayer1EtaHits;
		mu_muid_nTGCLayer2EtaHits = m_offPhys->mu_muid_nTGCLayer2EtaHits;
		mu_muid_nTGCLayer3EtaHits = m_offPhys->mu_muid_nTGCLayer3EtaHits;
		mu_muid_nTGCLayer4EtaHits = m_offPhys->mu_muid_nTGCLayer4EtaHits;
		mu_muid_nTGCLayer1PhiHits = m_offPhys->mu_muid_nTGCLayer1PhiHits;
		mu_muid_nTGCLayer2PhiHits = m_offPhys->mu_muid_nTGCLayer2PhiHits;
		mu_muid_nTGCLayer3PhiHits = m_offPhys->mu_muid_nTGCLayer3PhiHits;
		mu_muid_nTGCLayer4PhiHits = m_offPhys->mu_muid_nTGCLayer4PhiHits;
		
		mu_muid_etcone20 = m_offPhys->mu_muid_etcone20;
		mu_muid_etcone30 = m_offPhys->mu_muid_etcone30;
		mu_muid_etcone40 = m_offPhys->mu_muid_etcone40;
		mu_muid_nucone20 = m_offPhys->mu_muid_nucone20;
		mu_muid_nucone30 = m_offPhys->mu_muid_nucone30;
		mu_muid_nucone40 = m_offPhys->mu_muid_nucone40;
		mu_muid_energyLossPar = m_offPhys->mu_muid_energyLossPar;
		mu_muid_energyLossErr = m_offPhys->mu_muid_energyLossErr;
		mu_muid_bestMatch = m_offPhys->mu_muid_bestMatch;
		mu_muid_isStandAloneMuon = m_offPhys->mu_muid_isStandAloneMuon;
		mu_muid_isLowPtReconstructedMuon = m_offPhys->mu_muid_isLowPtReconstructedMuon;
		mu_muid_loose = m_offPhys->mu_muid_loose;
		mu_muid_medium = m_offPhys->mu_muid_medium;
		mu_muid_tight = m_offPhys->mu_muid_tight;
		mu_muid_phi_exPV = m_offPhys->mu_muid_phi_exPV;
		mu_muid_theta_exPV = m_offPhys->mu_muid_theta_exPV;
		mu_muid_qoverp_exPV = m_offPhys->mu_muid_qoverp_exPV;
		mu_muid_cov_d0_exPV = m_offPhys->mu_muid_cov_d0_exPV;
		mu_muid_cov_z0_exPV = m_offPhys->mu_muid_cov_z0_exPV;
		mu_muid_cov_phi_exPV = m_offPhys->mu_muid_cov_phi_exPV;
		mu_muid_cov_theta_exPV = m_offPhys->mu_muid_cov_theta_exPV;
		mu_muid_cov_qoverp_exPV = m_offPhys->mu_muid_cov_qoverp_exPV;
		mu_muid_cov_d0_z0_exPV = m_offPhys->mu_muid_cov_d0_z0_exPV;
		mu_muid_cov_d0_phi_exPV = m_offPhys->mu_muid_cov_d0_phi_exPV;
		mu_muid_cov_d0_theta_exPV = m_offPhys->mu_muid_cov_d0_theta_exPV;
		mu_muid_cov_d0_qoverp_exPV = m_offPhys->mu_muid_cov_d0_qoverp_exPV;
		mu_muid_cov_z0_phi_exPV = m_offPhys->mu_muid_cov_z0_phi_exPV;
		mu_muid_cov_z0_theta_exPV = m_offPhys->mu_muid_cov_z0_theta_exPV;
		mu_muid_cov_z0_qoverp_exPV = m_offPhys->mu_muid_cov_z0_qoverp_exPV;
		mu_muid_cov_phi_theta_exPV = m_offPhys->mu_muid_cov_phi_theta_exPV;
		mu_muid_cov_phi_qoverp_exPV = m_offPhys->mu_muid_cov_phi_qoverp_exPV;
		mu_muid_cov_theta_qoverp_exPV = m_offPhys->mu_muid_cov_theta_qoverp_exPV;
		mu_muid_ms_d0 = m_offPhys->mu_muid_ms_d0;
		mu_muid_ms_z0 = m_offPhys->mu_muid_ms_z0;
		mu_muid_ms_phi = m_offPhys->mu_muid_ms_phi;
		mu_muid_ms_theta = m_offPhys->mu_muid_ms_theta;
		mu_muid_ms_qoverp = m_offPhys->mu_muid_ms_qoverp;
		mu_muid_id_d0 = m_offPhys->mu_muid_id_d0;
		mu_muid_id_z0 = m_offPhys->mu_muid_id_z0;
		mu_muid_id_phi = m_offPhys->mu_muid_id_phi;
		mu_muid_me_d0 = m_offPhys->mu_muid_me_d0;
		mu_muid_me_z0 = m_offPhys->mu_muid_me_z0;
		mu_muid_me_phi = m_offPhys->mu_muid_me_phi;
		mu_muid_ie_d0 = m_offPhys->mu_muid_ie_d0;
		mu_muid_ie_z0 = m_offPhys->mu_muid_ie_z0;
		mu_muid_ie_phi = m_offPhys->mu_muid_ie_phi;
		mu_muid_ie_theta = m_offPhys->mu_muid_ie_theta;
		mu_muid_ie_qoverp = m_offPhys->mu_muid_ie_qoverp;
		mu_muid_nBLHits = m_offPhys->mu_muid_nBLHits;
		mu_muid_nTRTHighTHits = m_offPhys->mu_muid_nTRTHighTHits;
		mu_muid_nBLSharedHits = m_offPhys->mu_muid_nBLSharedHits;
		mu_muid_nPixSharedHits = m_offPhys->mu_muid_nPixSharedHits;
		mu_muid_nPixHoles = m_offPhys->mu_muid_nPixHoles;
		mu_muid_nSCTSharedHits = m_offPhys->mu_muid_nSCTSharedHits;
		mu_muid_nSCTHoles = m_offPhys->mu_muid_nSCTHoles;
		mu_muid_nTRTOutliers = m_offPhys->mu_muid_nTRTOutliers;
		mu_muid_nTRTHighTOutliers = m_offPhys->mu_muid_nTRTHighTOutliers;
		mu_muid_nMDTHits = m_offPhys->mu_muid_nMDTHits;
		mu_muid_nMDTHoles = m_offPhys->mu_muid_nMDTHoles;
		mu_muid_nCSCEtaHits = m_offPhys->mu_muid_nCSCEtaHits;
		mu_muid_nCSCEtaHoles = m_offPhys->mu_muid_nCSCEtaHoles;
		mu_muid_nCSCPhiHits = m_offPhys->mu_muid_nCSCPhiHits;
		mu_muid_nCSCPhiHoles = m_offPhys->mu_muid_nCSCPhiHoles;
		mu_muid_nRPCEtaHits = m_offPhys->mu_muid_nRPCEtaHits;
		mu_muid_nRPCEtaHoles = m_offPhys->mu_muid_nRPCEtaHoles;
		mu_muid_nRPCPhiHits = m_offPhys->mu_muid_nRPCPhiHits;
		mu_muid_nRPCPhiHoles = m_offPhys->mu_muid_nRPCPhiHoles;
		mu_muid_nTGCEtaHits = m_offPhys->mu_muid_nTGCEtaHits;
		mu_muid_nTGCEtaHoles = m_offPhys->mu_muid_nTGCEtaHoles;
		mu_muid_nTGCPhiHits = m_offPhys->mu_muid_nTGCPhiHits;
		mu_muid_nTGCPhiHoles = m_offPhys->mu_muid_nTGCPhiHoles;
		mu_muid_nGangedPixels = m_offPhys->mu_muid_nGangedPixels;
		mu_muid_nOutliersOnTrack = m_offPhys->mu_muid_nOutliersOnTrack;
		mu_muid_barrelSectors = m_offPhys->mu_muid_barrelSectors;
		mu_muid_endcapSectors = m_offPhys->mu_muid_endcapSectors;
		mu_muid_trackd0 = m_offPhys->mu_muid_trackd0;
		mu_muid_trackz0 = m_offPhys->mu_muid_trackz0;
		mu_muid_trackphi = m_offPhys->mu_muid_trackphi;
		mu_muid_tracktheta = m_offPhys->mu_muid_tracktheta;
		mu_muid_trackqoverp = m_offPhys->mu_muid_trackqoverp;
		mu_muid_trackcov_d0 = m_offPhys->mu_muid_trackcov_d0;
		mu_muid_trackcov_z0 = m_offPhys->mu_muid_trackcov_z0;
		mu_muid_trackcov_phi = m_offPhys->mu_muid_trackcov_phi;
		mu_muid_trackcov_theta = m_offPhys->mu_muid_trackcov_theta;
		mu_muid_trackcov_qoverp = m_offPhys->mu_muid_trackcov_qoverp;
		mu_muid_trackcov_d0_z0 = m_offPhys->mu_muid_trackcov_d0_z0;
		mu_muid_trackcov_d0_phi = m_offPhys->mu_muid_trackcov_d0_phi;
		mu_muid_trackcov_d0_theta = m_offPhys->mu_muid_trackcov_d0_theta;
		mu_muid_trackcov_d0_qoverp = m_offPhys->mu_muid_trackcov_d0_qoverp;
		mu_muid_trackcov_z0_phi = m_offPhys->mu_muid_trackcov_z0_phi;
		mu_muid_trackcov_z0_theta = m_offPhys->mu_muid_trackcov_z0_theta;
		mu_muid_trackcov_z0_qoverp = m_offPhys->mu_muid_trackcov_z0_qoverp;
		mu_muid_trackcov_phi_theta = m_offPhys->mu_muid_trackcov_phi_theta;
		mu_muid_trackcov_phi_qoverp = m_offPhys->mu_muid_trackcov_phi_qoverp;
		mu_muid_trackcov_theta_qoverp = m_offPhys->mu_muid_trackcov_theta_qoverp;
		mu_muid_trackfitchi2 = m_offPhys->mu_muid_trackfitchi2;
		mu_muid_trackfitndof = m_offPhys->mu_muid_trackfitndof;
		mu_muid_hastrack = m_offPhys->mu_muid_hastrack;
		mu_muid_EF_dr = m_offPhys->mu_muid_EF_dr;
		mu_muid_EF_cb_eta = m_offPhys->mu_muid_EF_cb_eta;
		mu_muid_EF_cb_phi = m_offPhys->mu_muid_EF_cb_phi;
		mu_muid_EF_cb_pt = m_offPhys->mu_muid_EF_cb_pt;
		mu_muid_EF_ms_eta = m_offPhys->mu_muid_EF_ms_eta;
		mu_muid_EF_ms_phi = m_offPhys->mu_muid_EF_ms_phi;
		mu_muid_EF_ms_pt = m_offPhys->mu_muid_EF_ms_pt;
		mu_muid_EF_me_eta = m_offPhys->mu_muid_EF_me_eta;
		mu_muid_EF_me_phi = m_offPhys->mu_muid_EF_me_phi;
		mu_muid_EF_me_pt = m_offPhys->mu_muid_EF_me_pt;
		mu_muid_EF_matched = m_offPhys->mu_muid_EF_matched;
		mu_muid_L2CB_dr = m_offPhys->mu_muid_L2CB_dr;
		mu_muid_L2CB_pt = m_offPhys->mu_muid_L2CB_pt;
		mu_muid_L2CB_eta = m_offPhys->mu_muid_L2CB_eta;
		mu_muid_L2CB_phi = m_offPhys->mu_muid_L2CB_phi;
		mu_muid_L2CB_id_pt = m_offPhys->mu_muid_L2CB_id_pt;
		mu_muid_L2CB_ms_pt = m_offPhys->mu_muid_L2CB_ms_pt;
		mu_muid_L2CB_nPixHits = m_offPhys->mu_muid_L2CB_nPixHits;
		mu_muid_L2CB_nSCTHits = m_offPhys->mu_muid_L2CB_nSCTHits;
		mu_muid_L2CB_nTRTHits = m_offPhys->mu_muid_L2CB_nTRTHits;
		mu_muid_L2CB_nTRTHighTHits = m_offPhys->mu_muid_L2CB_nTRTHighTHits;
		mu_muid_L2CB_matched = m_offPhys->mu_muid_L2CB_matched;
		mu_muid_L1_dr = m_offPhys->mu_muid_L1_dr;
		mu_muid_L1_pt = m_offPhys->mu_muid_L1_pt;
		mu_muid_L1_eta = m_offPhys->mu_muid_L1_eta;
		mu_muid_L1_phi = m_offPhys->mu_muid_L1_phi;
		mu_muid_L1_thrNumber = m_offPhys->mu_muid_L1_thrNumber;
		mu_muid_L1_RoINumber = m_offPhys->mu_muid_L1_RoINumber;
		mu_muid_L1_sectorAddress = m_offPhys->mu_muid_L1_sectorAddress;
		mu_muid_L1_firstCandidate = m_offPhys->mu_muid_L1_firstCandidate;
		mu_muid_L1_moreCandInRoI = m_offPhys->mu_muid_L1_moreCandInRoI;
		mu_muid_L1_moreCandInSector = m_offPhys->mu_muid_L1_moreCandInSector;
		mu_muid_L1_source = m_offPhys->mu_muid_L1_source;
		mu_muid_L1_hemisphere = m_offPhys->mu_muid_L1_hemisphere;
		mu_muid_L1_matched = m_offPhys->mu_muid_L1_matched;
		
		// vertex
		vxp_n       = m_offPhys->vxp_n;
		vxp_nTracks = m_offPhys->vxp_nTracks;
		vxp_type    = m_offPhys->vxp_type;
		vxp_z       = m_offPhys->vxp_z;
		vxp_z_err   = m_offPhys->vxp_z_err;
	}
	else
	{
		// external
		//period   = m_mcOffPhys->period;
		period = "NOAM ???";
		triggers = m_mcOffPhys->triggers;
	
		// fill run branches
		RunNumber   = m_mcOffPhys->RunNumber;
		lbn         = m_mcOffPhys->lbn;
		EventNumber = m_mcOffPhys->EventNumber;
		
		// L1 triggers
		L1_MU0 = m_mcOffPhys->L1_MU0;
		L1_MU10 = m_mcOffPhys->L1_MU10;
		L1_MU15 = m_mcOffPhys->L1_MU15;
		L1_MU20 = m_mcOffPhys->L1_MU20;
		L1_MU6 = m_mcOffPhys->L1_MU6;
		
		///////////////////////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////
		/*
		// EF triggers
		EF_mu10 = m_mcOffPhys->EF_mu10;
		EF_mu10_MG = m_mcOffPhys->EF_mu10_MG;
		EF_mu10_MSonly = m_mcOffPhys->EF_mu10_MSonly;
		EF_mu10_MSonly_tight = m_mcOffPhys->EF_mu10_MSonly_tight;
		EF_mu10_NoAlg = m_mcOffPhys->EF_mu10_NoAlg;
		EF_mu10_tight = m_mcOffPhys->EF_mu10_tight;
		EF_mu10i_loose = m_mcOffPhys->EF_mu10i_loose;
		EF_mu13 = m_mcOffPhys->EF_mu13;
		EF_mu13_MG = m_mcOffPhys->EF_mu13_MG;
		EF_mu13_MG_tight = m_mcOffPhys->EF_mu13_MG_tight;
		EF_mu13_tight = m_mcOffPhys->EF_mu13_tight;
		EF_mu15 = m_mcOffPhys->EF_mu15;
		EF_mu15_NoAlg = m_mcOffPhys->EF_mu15_NoAlg;
		EF_mu20 = m_mcOffPhys->EF_mu20;
		EF_mu20_MSonly = m_mcOffPhys->EF_mu20_MSonly;
		EF_mu20_NoAlg = m_mcOffPhys->EF_mu20_NoAlg;
		EF_mu20_slow = m_mcOffPhys->EF_mu20_slow;
		EF_mu30_MSonly = m_mcOffPhys->EF_mu30_MSonly;
		EF_mu4 = m_mcOffPhys->EF_mu4;
		EF_mu40_MSonly = m_mcOffPhys->EF_mu40_MSonly;
		*/
		EF_mu10 = 0;
		EF_mu10_MG = 0;
		EF_mu10_MSonly = 0;
		EF_mu10_MSonly_tight = 0;
		EF_mu10_NoAlg = 0;
		EF_mu10_tight = 0;
		EF_mu10i_loose = 0;
		EF_mu13 = 0;
		EF_mu13_MG = 0;
		EF_mu13_MG_tight = 0;
		EF_mu13_tight = 0;
		EF_mu15 = 0;
		EF_mu15_NoAlg = 0;
		EF_mu20 = 0;
		EF_mu20_MSonly = 0;
		EF_mu20_NoAlg = 0;
		EF_mu20_slow = 0;
		EF_mu30_MSonly = 0;
		EF_mu4 = 0;
		EF_mu40_MSonly = 0;
		///////////////////////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////////////////////
		
		// staco
		mu_staco_n        = m_mcOffPhys->mu_staco_n;
		mu_staco_px       = m_mcOffPhys->mu_staco_px;
		mu_staco_py       = m_mcOffPhys->mu_staco_py;
		mu_staco_pz       = m_mcOffPhys->mu_staco_pz;
		mu_staco_E        = m_mcOffPhys->mu_staco_E;
		mu_staco_m        = m_mcOffPhys->mu_staco_m;
		mu_staco_charge   = m_mcOffPhys->mu_staco_charge;
		mu_staco_pt       = m_mcOffPhys->mu_staco_pt;
		mu_staco_ptcone20 = m_mcOffPhys->mu_staco_ptcone20;
		mu_staco_ptcone30 = m_mcOffPhys->mu_staco_ptcone30;
		mu_staco_ptcone40 = m_mcOffPhys->mu_staco_ptcone40;
		mu_staco_eta      = m_mcOffPhys->mu_staco_eta;
		mu_staco_phi      = m_mcOffPhys->mu_staco_phi;
		mu_staco_d0_exPV  = m_mcOffPhys->mu_staco_d0_exPV;
		mu_staco_z0_exPV  = m_mcOffPhys->mu_staco_z0_exPV;
		mu_staco_allauthor= m_mcOffPhys->mu_staco_allauthor;
		mu_staco_author   = m_mcOffPhys->mu_staco_author;
		mu_staco_matchchi2   = m_mcOffPhys->mu_staco_matchchi2;
		mu_staco_matchndof   = m_mcOffPhys->mu_staco_matchndof;
		mu_staco_me_qoverp= m_mcOffPhys->mu_staco_me_qoverp;
		mu_staco_id_qoverp= m_mcOffPhys->mu_staco_id_qoverp;
		mu_staco_me_theta = m_mcOffPhys->mu_staco_me_theta;
		mu_staco_id_theta = m_mcOffPhys->mu_staco_id_theta;
		mu_staco_isCombinedMuon = m_mcOffPhys->mu_staco_isCombinedMuon;
		mu_staco_nSCTHits = m_mcOffPhys->mu_staco_nSCTHits;
		mu_staco_nPixHits = m_mcOffPhys->mu_staco_nPixHits;
		
		mu_staco_nMDTBIHits =    m_mcOffPhys->mu_staco_nMDTBIHits;
		mu_staco_nMDTBMHits =    m_mcOffPhys->mu_staco_nMDTBMHits;
		mu_staco_nMDTBOHits =    m_mcOffPhys->mu_staco_nMDTBOHits;
		mu_staco_nMDTBEEHits =   m_mcOffPhys->mu_staco_nMDTBEEHits;
		mu_staco_nMDTBIS78Hits = m_mcOffPhys->mu_staco_nMDTBIS78Hits;
		mu_staco_nMDTEIHits =    m_mcOffPhys->mu_staco_nMDTEIHits;
		mu_staco_nMDTEMHits =    m_mcOffPhys->mu_staco_nMDTEMHits;
		mu_staco_nMDTEOHits =    m_mcOffPhys->mu_staco_nMDTEOHits;
		mu_staco_nMDTEEHits =    m_mcOffPhys->mu_staco_nMDTEEHits;
		mu_staco_nRPCLayer1EtaHits = m_mcOffPhys->mu_staco_nRPCLayer1EtaHits;
		mu_staco_nRPCLayer2EtaHits = m_mcOffPhys->mu_staco_nRPCLayer2EtaHits;
		mu_staco_nRPCLayer3EtaHits = m_mcOffPhys->mu_staco_nRPCLayer3EtaHits;
		mu_staco_nRPCLayer1PhiHits = m_mcOffPhys->mu_staco_nRPCLayer1PhiHits;
		mu_staco_nRPCLayer2PhiHits = m_mcOffPhys->mu_staco_nRPCLayer2PhiHits;
		mu_staco_nRPCLayer3PhiHits = m_mcOffPhys->mu_staco_nRPCLayer3PhiHits;
		mu_staco_nTGCLayer1EtaHits = m_mcOffPhys->mu_staco_nTGCLayer1EtaHits;
		mu_staco_nTGCLayer2EtaHits = m_mcOffPhys->mu_staco_nTGCLayer2EtaHits;
		mu_staco_nTGCLayer3EtaHits = m_mcOffPhys->mu_staco_nTGCLayer3EtaHits;
		mu_staco_nTGCLayer4EtaHits = m_mcOffPhys->mu_staco_nTGCLayer4EtaHits;
		mu_staco_nTGCLayer1PhiHits = m_mcOffPhys->mu_staco_nTGCLayer1PhiHits;
		mu_staco_nTGCLayer2PhiHits = m_mcOffPhys->mu_staco_nTGCLayer2PhiHits;
		mu_staco_nTGCLayer3PhiHits = m_mcOffPhys->mu_staco_nTGCLayer3PhiHits;
		mu_staco_nTGCLayer4PhiHits = m_mcOffPhys->mu_staco_nTGCLayer4PhiHits;
		
		mu_staco_etcone20 = m_mcOffPhys->mu_staco_etcone20;
		mu_staco_etcone30 = m_mcOffPhys->mu_staco_etcone30;
		mu_staco_etcone40 = m_mcOffPhys->mu_staco_etcone40;
		mu_staco_nucone20 = m_mcOffPhys->mu_staco_nucone20;
		mu_staco_nucone30 = m_mcOffPhys->mu_staco_nucone30;
		mu_staco_nucone40 = m_mcOffPhys->mu_staco_nucone40;
		mu_staco_energyLossPar = m_mcOffPhys->mu_staco_energyLossPar;
		mu_staco_energyLossErr = m_mcOffPhys->mu_staco_energyLossErr;
		mu_staco_bestMatch = m_mcOffPhys->mu_staco_bestMatch;
		mu_staco_isStandAloneMuon = m_mcOffPhys->mu_staco_isStandAloneMuon;
		mu_staco_isLowPtReconstructedMuon = m_mcOffPhys->mu_staco_isLowPtReconstructedMuon;
		mu_staco_loose = m_mcOffPhys->mu_staco_loose;
		mu_staco_medium = m_mcOffPhys->mu_staco_medium;
		mu_staco_tight = m_mcOffPhys->mu_staco_tight;
		mu_staco_phi_exPV = m_mcOffPhys->mu_staco_phi_exPV;
		mu_staco_theta_exPV = m_mcOffPhys->mu_staco_theta_exPV;
		mu_staco_qoverp_exPV = m_mcOffPhys->mu_staco_qoverp_exPV;
		mu_staco_cov_d0_exPV = m_mcOffPhys->mu_staco_cov_d0_exPV;
		mu_staco_cov_z0_exPV = m_mcOffPhys->mu_staco_cov_z0_exPV;
		mu_staco_cov_phi_exPV = m_mcOffPhys->mu_staco_cov_phi_exPV;
		mu_staco_cov_theta_exPV = m_mcOffPhys->mu_staco_cov_theta_exPV;
		mu_staco_cov_qoverp_exPV = m_mcOffPhys->mu_staco_cov_qoverp_exPV;
		mu_staco_cov_d0_z0_exPV = m_mcOffPhys->mu_staco_cov_d0_z0_exPV;
		mu_staco_cov_d0_phi_exPV = m_mcOffPhys->mu_staco_cov_d0_phi_exPV;
		mu_staco_cov_d0_theta_exPV = m_mcOffPhys->mu_staco_cov_d0_theta_exPV;
		mu_staco_cov_d0_qoverp_exPV = m_mcOffPhys->mu_staco_cov_d0_qoverp_exPV;
		mu_staco_cov_z0_phi_exPV = m_mcOffPhys->mu_staco_cov_z0_phi_exPV;
		mu_staco_cov_z0_theta_exPV = m_mcOffPhys->mu_staco_cov_z0_theta_exPV;
		mu_staco_cov_z0_qoverp_exPV = m_mcOffPhys->mu_staco_cov_z0_qoverp_exPV;
		mu_staco_cov_phi_theta_exPV = m_mcOffPhys->mu_staco_cov_phi_theta_exPV;
		mu_staco_cov_phi_qoverp_exPV = m_mcOffPhys->mu_staco_cov_phi_qoverp_exPV;
		mu_staco_cov_theta_qoverp_exPV = m_mcOffPhys->mu_staco_cov_theta_qoverp_exPV;
		mu_staco_ms_d0 = m_mcOffPhys->mu_staco_ms_d0;
		mu_staco_ms_z0 = m_mcOffPhys->mu_staco_ms_z0;
		mu_staco_ms_phi = m_mcOffPhys->mu_staco_ms_phi;
		mu_staco_ms_theta = m_mcOffPhys->mu_staco_ms_theta;
		mu_staco_ms_qoverp = m_mcOffPhys->mu_staco_ms_qoverp;
		mu_staco_id_d0 = m_mcOffPhys->mu_staco_id_d0;
		mu_staco_id_z0 = m_mcOffPhys->mu_staco_id_z0;
		mu_staco_id_phi = m_mcOffPhys->mu_staco_id_phi;
		mu_staco_me_d0 = m_mcOffPhys->mu_staco_me_d0;
		mu_staco_me_z0 = m_mcOffPhys->mu_staco_me_z0;
		mu_staco_me_phi = m_mcOffPhys->mu_staco_me_phi;
		mu_staco_ie_d0 = m_mcOffPhys->mu_staco_ie_d0;
		mu_staco_ie_z0 = m_mcOffPhys->mu_staco_ie_z0;
		mu_staco_ie_phi = m_mcOffPhys->mu_staco_ie_phi;
		mu_staco_ie_theta = m_mcOffPhys->mu_staco_ie_theta;
		mu_staco_ie_qoverp = m_mcOffPhys->mu_staco_ie_qoverp;
		mu_staco_nBLHits = m_mcOffPhys->mu_staco_nBLHits;
		mu_staco_nTRTHighTHits = m_mcOffPhys->mu_staco_nTRTHighTHits;
		mu_staco_nBLSharedHits = m_mcOffPhys->mu_staco_nBLSharedHits;
		mu_staco_nPixSharedHits = m_mcOffPhys->mu_staco_nPixSharedHits;
		mu_staco_nPixHoles = m_mcOffPhys->mu_staco_nPixHoles;
		mu_staco_nSCTSharedHits = m_mcOffPhys->mu_staco_nSCTSharedHits;
		mu_staco_nSCTHoles = m_mcOffPhys->mu_staco_nSCTHoles;
		mu_staco_nTRTOutliers = m_mcOffPhys->mu_staco_nTRTOutliers;
		mu_staco_nTRTHighTOutliers = m_mcOffPhys->mu_staco_nTRTHighTOutliers;
		mu_staco_nMDTHits = m_mcOffPhys->mu_staco_nMDTHits;
		mu_staco_nMDTHoles = m_mcOffPhys->mu_staco_nMDTHoles;
		mu_staco_nCSCEtaHits = m_mcOffPhys->mu_staco_nCSCEtaHits;
		mu_staco_nCSCEtaHoles = m_mcOffPhys->mu_staco_nCSCEtaHoles;
		mu_staco_nCSCPhiHits = m_mcOffPhys->mu_staco_nCSCPhiHits;
		mu_staco_nCSCPhiHoles = m_mcOffPhys->mu_staco_nCSCPhiHoles;
		mu_staco_nRPCEtaHits = m_mcOffPhys->mu_staco_nRPCEtaHits;
		mu_staco_nRPCEtaHoles = m_mcOffPhys->mu_staco_nRPCEtaHoles;
		mu_staco_nRPCPhiHits = m_mcOffPhys->mu_staco_nRPCPhiHits;
		mu_staco_nRPCPhiHoles = m_mcOffPhys->mu_staco_nRPCPhiHoles;
		mu_staco_nTGCEtaHits = m_mcOffPhys->mu_staco_nTGCEtaHits;
		mu_staco_nTGCEtaHoles = m_mcOffPhys->mu_staco_nTGCEtaHoles;
		mu_staco_nTGCPhiHits = m_mcOffPhys->mu_staco_nTGCPhiHits;
		mu_staco_nTGCPhiHoles = m_mcOffPhys->mu_staco_nTGCPhiHoles;
		mu_staco_nGangedPixels = m_mcOffPhys->mu_staco_nGangedPixels;
		mu_staco_nOutliersOnTrack = m_mcOffPhys->mu_staco_nOutliersOnTrack;
		mu_staco_barrelSectors = m_mcOffPhys->mu_staco_barrelSectors;
		mu_staco_endcapSectors = m_mcOffPhys->mu_staco_endcapSectors;
		mu_staco_trackd0 = m_mcOffPhys->mu_staco_trackd0;
		mu_staco_trackz0 = m_mcOffPhys->mu_staco_trackz0;
		mu_staco_trackphi = m_mcOffPhys->mu_staco_trackphi;
		mu_staco_tracktheta = m_mcOffPhys->mu_staco_tracktheta;
		mu_staco_trackqoverp = m_mcOffPhys->mu_staco_trackqoverp;
		mu_staco_trackcov_d0 = m_mcOffPhys->mu_staco_trackcov_d0;
		mu_staco_trackcov_z0 = m_mcOffPhys->mu_staco_trackcov_z0;
		mu_staco_trackcov_phi = m_mcOffPhys->mu_staco_trackcov_phi;
		mu_staco_trackcov_theta = m_mcOffPhys->mu_staco_trackcov_theta;
		mu_staco_trackcov_qoverp = m_mcOffPhys->mu_staco_trackcov_qoverp;
		mu_staco_trackcov_d0_z0 = m_mcOffPhys->mu_staco_trackcov_d0_z0;
		mu_staco_trackcov_d0_phi = m_mcOffPhys->mu_staco_trackcov_d0_phi;
		mu_staco_trackcov_d0_theta = m_mcOffPhys->mu_staco_trackcov_d0_theta;
		mu_staco_trackcov_d0_qoverp = m_mcOffPhys->mu_staco_trackcov_d0_qoverp;
		mu_staco_trackcov_z0_phi = m_mcOffPhys->mu_staco_trackcov_z0_phi;
		mu_staco_trackcov_z0_theta = m_mcOffPhys->mu_staco_trackcov_z0_theta;
		mu_staco_trackcov_z0_qoverp = m_mcOffPhys->mu_staco_trackcov_z0_qoverp;
		mu_staco_trackcov_phi_theta = m_mcOffPhys->mu_staco_trackcov_phi_theta;
		mu_staco_trackcov_phi_qoverp = m_mcOffPhys->mu_staco_trackcov_phi_qoverp;
		mu_staco_trackcov_theta_qoverp = m_mcOffPhys->mu_staco_trackcov_theta_qoverp;
		mu_staco_trackfitchi2 = m_mcOffPhys->mu_staco_trackfitchi2;
		mu_staco_trackfitndof = m_mcOffPhys->mu_staco_trackfitndof;
		mu_staco_hastrack = m_mcOffPhys->mu_staco_hastrack;
		mu_staco_EF_dr = m_mcOffPhys->mu_staco_EF_dr;
		mu_staco_EF_cb_eta = m_mcOffPhys->mu_staco_EF_cb_eta;
		mu_staco_EF_cb_phi = m_mcOffPhys->mu_staco_EF_cb_phi;
		mu_staco_EF_cb_pt = m_mcOffPhys->mu_staco_EF_cb_pt;
		mu_staco_EF_ms_eta = m_mcOffPhys->mu_staco_EF_ms_eta;
		mu_staco_EF_ms_phi = m_mcOffPhys->mu_staco_EF_ms_phi;
		mu_staco_EF_ms_pt = m_mcOffPhys->mu_staco_EF_ms_pt;
		mu_staco_EF_me_eta = m_mcOffPhys->mu_staco_EF_me_eta;
		mu_staco_EF_me_phi = m_mcOffPhys->mu_staco_EF_me_phi;
		mu_staco_EF_me_pt = m_mcOffPhys->mu_staco_EF_me_pt;
		mu_staco_EF_matched = m_mcOffPhys->mu_staco_EF_matched;
		mu_staco_L2CB_dr = m_mcOffPhys->mu_staco_L2CB_dr;
		mu_staco_L2CB_pt = m_mcOffPhys->mu_staco_L2CB_pt;
		mu_staco_L2CB_eta = m_mcOffPhys->mu_staco_L2CB_eta;
		mu_staco_L2CB_phi = m_mcOffPhys->mu_staco_L2CB_phi;
		mu_staco_L2CB_id_pt = m_mcOffPhys->mu_staco_L2CB_id_pt;
		mu_staco_L2CB_ms_pt = m_mcOffPhys->mu_staco_L2CB_ms_pt;
		mu_staco_L2CB_nPixHits = m_mcOffPhys->mu_staco_L2CB_nPixHits;
		mu_staco_L2CB_nSCTHits = m_mcOffPhys->mu_staco_L2CB_nSCTHits;
		mu_staco_L2CB_nTRTHits = m_mcOffPhys->mu_staco_L2CB_nTRTHits;
		mu_staco_L2CB_nTRTHighTHits = m_mcOffPhys->mu_staco_L2CB_nTRTHighTHits;
		mu_staco_L2CB_matched = m_mcOffPhys->mu_staco_L2CB_matched;
		mu_staco_L1_dr = m_mcOffPhys->mu_staco_L1_dr;
		mu_staco_L1_pt = m_mcOffPhys->mu_staco_L1_pt;
		mu_staco_L1_eta = m_mcOffPhys->mu_staco_L1_eta;
		mu_staco_L1_phi = m_mcOffPhys->mu_staco_L1_phi;
		mu_staco_L1_thrNumber = m_mcOffPhys->mu_staco_L1_thrNumber;
		mu_staco_L1_RoINumber = m_mcOffPhys->mu_staco_L1_RoINumber;
		mu_staco_L1_sectorAddress = m_mcOffPhys->mu_staco_L1_sectorAddress;
		mu_staco_L1_firstCandidate = m_mcOffPhys->mu_staco_L1_firstCandidate;
		mu_staco_L1_moreCandInRoI = m_mcOffPhys->mu_staco_L1_moreCandInRoI;
		mu_staco_L1_moreCandInSector = m_mcOffPhys->mu_staco_L1_moreCandInSector;
		mu_staco_L1_source = m_mcOffPhys->mu_staco_L1_source;
		mu_staco_L1_hemisphere = m_mcOffPhys->mu_staco_L1_hemisphere;
		mu_staco_L1_matched = m_mcOffPhys->mu_staco_L1_matched;
		
		
		// muid
		mu_muid_n        = m_mcOffPhys->mu_muid_n;
		mu_muid_px       = m_mcOffPhys->mu_muid_px;
		mu_muid_py       = m_mcOffPhys->mu_muid_py;
		mu_muid_pz       = m_mcOffPhys->mu_muid_pz;
		mu_muid_E        = m_mcOffPhys->mu_muid_E;
		mu_muid_m        = m_mcOffPhys->mu_muid_m;
		mu_muid_charge   = m_mcOffPhys->mu_muid_charge;
		mu_muid_pt       = m_mcOffPhys->mu_muid_pt;
		mu_muid_ptcone20 = m_mcOffPhys->mu_muid_ptcone20;
		mu_muid_ptcone30 = m_mcOffPhys->mu_muid_ptcone30;
		mu_muid_ptcone40 = m_mcOffPhys->mu_muid_ptcone40;
		mu_muid_eta      = m_mcOffPhys->mu_muid_eta;
		mu_muid_phi      = m_mcOffPhys->mu_muid_phi;
		mu_muid_d0_exPV  = m_mcOffPhys->mu_muid_d0_exPV;
		mu_muid_z0_exPV  = m_mcOffPhys->mu_muid_z0_exPV;
		mu_muid_allauthor= m_mcOffPhys->mu_muid_allauthor;
		mu_muid_author   = m_mcOffPhys->mu_muid_author;
		mu_muid_matchchi2 = m_mcOffPhys->mu_muid_matchchi2;
		mu_muid_matchndof = m_mcOffPhys->mu_muid_matchndof;
		mu_muid_me_qoverp = m_mcOffPhys->mu_muid_me_qoverp;
		mu_muid_id_qoverp = m_mcOffPhys->mu_muid_id_qoverp;
		mu_muid_me_theta = m_mcOffPhys->mu_muid_me_theta;
		mu_muid_id_theta = m_mcOffPhys->mu_muid_id_theta;
		mu_muid_isCombinedMuon = m_mcOffPhys->mu_muid_isCombinedMuon;
		mu_muid_nSCTHits = m_mcOffPhys->mu_muid_nSCTHits;
		mu_muid_nPixHits = m_mcOffPhys->mu_muid_nPixHits;
		mu_muid_nMDTBIHits =      m_mcOffPhys->mu_muid_nMDTBIHits;
		mu_muid_nMDTBMHits =      m_mcOffPhys->mu_muid_nMDTBMHits;
		mu_muid_nMDTBOHits =      m_mcOffPhys->mu_muid_nMDTBOHits;
		mu_muid_nMDTBEEHits =     m_mcOffPhys->mu_muid_nMDTBEEHits;
		mu_muid_nMDTBIS78Hits =   m_mcOffPhys->mu_muid_nMDTBIS78Hits;
		mu_muid_nMDTEIHits =      m_mcOffPhys->mu_muid_nMDTEIHits;
		mu_muid_nMDTEMHits =      m_mcOffPhys->mu_muid_nMDTEMHits;
		mu_muid_nMDTEOHits =      m_mcOffPhys->mu_muid_nMDTEOHits;
		mu_muid_nMDTEEHits =      m_mcOffPhys->mu_muid_nMDTEEHits;
		
		mu_muid_nRPCLayer1EtaHits = m_mcOffPhys->mu_muid_nRPCLayer1EtaHits;
		mu_muid_nRPCLayer2EtaHits = m_mcOffPhys->mu_muid_nRPCLayer2EtaHits;
		mu_muid_nRPCLayer3EtaHits = m_mcOffPhys->mu_muid_nRPCLayer3EtaHits;
		mu_muid_nRPCLayer1PhiHits = m_mcOffPhys->mu_muid_nRPCLayer1PhiHits;
		mu_muid_nRPCLayer2PhiHits = m_mcOffPhys->mu_muid_nRPCLayer2PhiHits;
		mu_muid_nRPCLayer3PhiHits = m_mcOffPhys->mu_muid_nRPCLayer3PhiHits;
		mu_muid_nTGCLayer1EtaHits = m_mcOffPhys->mu_muid_nTGCLayer1EtaHits;
		mu_muid_nTGCLayer2EtaHits = m_mcOffPhys->mu_muid_nTGCLayer2EtaHits;
		mu_muid_nTGCLayer3EtaHits = m_mcOffPhys->mu_muid_nTGCLayer3EtaHits;
		mu_muid_nTGCLayer4EtaHits = m_mcOffPhys->mu_muid_nTGCLayer4EtaHits;
		mu_muid_nTGCLayer1PhiHits = m_mcOffPhys->mu_muid_nTGCLayer1PhiHits;
		mu_muid_nTGCLayer2PhiHits = m_mcOffPhys->mu_muid_nTGCLayer2PhiHits;
		mu_muid_nTGCLayer3PhiHits = m_mcOffPhys->mu_muid_nTGCLayer3PhiHits;
		mu_muid_nTGCLayer4PhiHits = m_mcOffPhys->mu_muid_nTGCLayer4PhiHits;
		
		mu_muid_etcone20 = m_mcOffPhys->mu_muid_etcone20;
		mu_muid_etcone30 = m_mcOffPhys->mu_muid_etcone30;
		mu_muid_etcone40 = m_mcOffPhys->mu_muid_etcone40;
		mu_muid_nucone20 = m_mcOffPhys->mu_muid_nucone20;
		mu_muid_nucone30 = m_mcOffPhys->mu_muid_nucone30;
		mu_muid_nucone40 = m_mcOffPhys->mu_muid_nucone40;
		mu_muid_energyLossPar = m_mcOffPhys->mu_muid_energyLossPar;
		mu_muid_energyLossErr = m_mcOffPhys->mu_muid_energyLossErr;
		mu_muid_bestMatch = m_mcOffPhys->mu_muid_bestMatch;
		mu_muid_isStandAloneMuon = m_mcOffPhys->mu_muid_isStandAloneMuon;
		mu_muid_isLowPtReconstructedMuon = m_mcOffPhys->mu_muid_isLowPtReconstructedMuon;
		mu_muid_loose = m_mcOffPhys->mu_muid_loose;
		mu_muid_medium = m_mcOffPhys->mu_muid_medium;
		mu_muid_tight = m_mcOffPhys->mu_muid_tight;
		mu_muid_phi_exPV = m_mcOffPhys->mu_muid_phi_exPV;
		mu_muid_theta_exPV = m_mcOffPhys->mu_muid_theta_exPV;
		mu_muid_qoverp_exPV = m_mcOffPhys->mu_muid_qoverp_exPV;
		mu_muid_cov_d0_exPV = m_mcOffPhys->mu_muid_cov_d0_exPV;
		mu_muid_cov_z0_exPV = m_mcOffPhys->mu_muid_cov_z0_exPV;
		mu_muid_cov_phi_exPV = m_mcOffPhys->mu_muid_cov_phi_exPV;
		mu_muid_cov_theta_exPV = m_mcOffPhys->mu_muid_cov_theta_exPV;
		mu_muid_cov_qoverp_exPV = m_mcOffPhys->mu_muid_cov_qoverp_exPV;
		mu_muid_cov_d0_z0_exPV = m_mcOffPhys->mu_muid_cov_d0_z0_exPV;
		mu_muid_cov_d0_phi_exPV = m_mcOffPhys->mu_muid_cov_d0_phi_exPV;
		mu_muid_cov_d0_theta_exPV = m_mcOffPhys->mu_muid_cov_d0_theta_exPV;
		mu_muid_cov_d0_qoverp_exPV = m_mcOffPhys->mu_muid_cov_d0_qoverp_exPV;
		mu_muid_cov_z0_phi_exPV = m_mcOffPhys->mu_muid_cov_z0_phi_exPV;
		mu_muid_cov_z0_theta_exPV = m_mcOffPhys->mu_muid_cov_z0_theta_exPV;
		mu_muid_cov_z0_qoverp_exPV = m_mcOffPhys->mu_muid_cov_z0_qoverp_exPV;
		mu_muid_cov_phi_theta_exPV = m_mcOffPhys->mu_muid_cov_phi_theta_exPV;
		mu_muid_cov_phi_qoverp_exPV = m_mcOffPhys->mu_muid_cov_phi_qoverp_exPV;
		mu_muid_cov_theta_qoverp_exPV = m_mcOffPhys->mu_muid_cov_theta_qoverp_exPV;
		mu_muid_ms_d0 = m_mcOffPhys->mu_muid_ms_d0;
		mu_muid_ms_z0 = m_mcOffPhys->mu_muid_ms_z0;
		mu_muid_ms_phi = m_mcOffPhys->mu_muid_ms_phi;
		mu_muid_ms_theta = m_mcOffPhys->mu_muid_ms_theta;
		mu_muid_ms_qoverp = m_mcOffPhys->mu_muid_ms_qoverp;
		mu_muid_id_d0 = m_mcOffPhys->mu_muid_id_d0;
		mu_muid_id_z0 = m_mcOffPhys->mu_muid_id_z0;
		mu_muid_id_phi = m_mcOffPhys->mu_muid_id_phi;
		mu_muid_me_d0 = m_mcOffPhys->mu_muid_me_d0;
		mu_muid_me_z0 = m_mcOffPhys->mu_muid_me_z0;
		mu_muid_me_phi = m_mcOffPhys->mu_muid_me_phi;
		mu_muid_ie_d0 = m_mcOffPhys->mu_muid_ie_d0;
		mu_muid_ie_z0 = m_mcOffPhys->mu_muid_ie_z0;
		mu_muid_ie_phi = m_mcOffPhys->mu_muid_ie_phi;
		mu_muid_ie_theta = m_mcOffPhys->mu_muid_ie_theta;
		mu_muid_ie_qoverp = m_mcOffPhys->mu_muid_ie_qoverp;
		mu_muid_nBLHits = m_mcOffPhys->mu_muid_nBLHits;
		mu_muid_nTRTHighTHits = m_mcOffPhys->mu_muid_nTRTHighTHits;
		mu_muid_nBLSharedHits = m_mcOffPhys->mu_muid_nBLSharedHits;
		mu_muid_nPixSharedHits = m_mcOffPhys->mu_muid_nPixSharedHits;
		mu_muid_nPixHoles = m_mcOffPhys->mu_muid_nPixHoles;
		mu_muid_nSCTSharedHits = m_mcOffPhys->mu_muid_nSCTSharedHits;
		mu_muid_nSCTHoles = m_mcOffPhys->mu_muid_nSCTHoles;
		mu_muid_nTRTOutliers = m_mcOffPhys->mu_muid_nTRTOutliers;
		mu_muid_nTRTHighTOutliers = m_mcOffPhys->mu_muid_nTRTHighTOutliers;
		mu_muid_nMDTHits = m_mcOffPhys->mu_muid_nMDTHits;
		mu_muid_nMDTHoles = m_mcOffPhys->mu_muid_nMDTHoles;
		mu_muid_nCSCEtaHits = m_mcOffPhys->mu_muid_nCSCEtaHits;
		mu_muid_nCSCEtaHoles = m_mcOffPhys->mu_muid_nCSCEtaHoles;
		mu_muid_nCSCPhiHits = m_mcOffPhys->mu_muid_nCSCPhiHits;
		mu_muid_nCSCPhiHoles = m_mcOffPhys->mu_muid_nCSCPhiHoles;
		mu_muid_nRPCEtaHits = m_mcOffPhys->mu_muid_nRPCEtaHits;
		mu_muid_nRPCEtaHoles = m_mcOffPhys->mu_muid_nRPCEtaHoles;
		mu_muid_nRPCPhiHits = m_mcOffPhys->mu_muid_nRPCPhiHits;
		mu_muid_nRPCPhiHoles = m_mcOffPhys->mu_muid_nRPCPhiHoles;
		mu_muid_nTGCEtaHits = m_mcOffPhys->mu_muid_nTGCEtaHits;
		mu_muid_nTGCEtaHoles = m_mcOffPhys->mu_muid_nTGCEtaHoles;
		mu_muid_nTGCPhiHits = m_mcOffPhys->mu_muid_nTGCPhiHits;
		mu_muid_nTGCPhiHoles = m_mcOffPhys->mu_muid_nTGCPhiHoles;
		mu_muid_nGangedPixels = m_mcOffPhys->mu_muid_nGangedPixels;
		mu_muid_nOutliersOnTrack = m_mcOffPhys->mu_muid_nOutliersOnTrack;
		mu_muid_barrelSectors = m_mcOffPhys->mu_muid_barrelSectors;
		mu_muid_endcapSectors = m_mcOffPhys->mu_muid_endcapSectors;
		mu_muid_trackd0 = m_mcOffPhys->mu_muid_trackd0;
		mu_muid_trackz0 = m_mcOffPhys->mu_muid_trackz0;
		mu_muid_trackphi = m_mcOffPhys->mu_muid_trackphi;
		mu_muid_tracktheta = m_mcOffPhys->mu_muid_tracktheta;
		mu_muid_trackqoverp = m_mcOffPhys->mu_muid_trackqoverp;
		mu_muid_trackcov_d0 = m_mcOffPhys->mu_muid_trackcov_d0;
		mu_muid_trackcov_z0 = m_mcOffPhys->mu_muid_trackcov_z0;
		mu_muid_trackcov_phi = m_mcOffPhys->mu_muid_trackcov_phi;
		mu_muid_trackcov_theta = m_mcOffPhys->mu_muid_trackcov_theta;
		mu_muid_trackcov_qoverp = m_mcOffPhys->mu_muid_trackcov_qoverp;
		mu_muid_trackcov_d0_z0 = m_mcOffPhys->mu_muid_trackcov_d0_z0;
		mu_muid_trackcov_d0_phi = m_mcOffPhys->mu_muid_trackcov_d0_phi;
		mu_muid_trackcov_d0_theta = m_mcOffPhys->mu_muid_trackcov_d0_theta;
		mu_muid_trackcov_d0_qoverp = m_mcOffPhys->mu_muid_trackcov_d0_qoverp;
		mu_muid_trackcov_z0_phi = m_mcOffPhys->mu_muid_trackcov_z0_phi;
		mu_muid_trackcov_z0_theta = m_mcOffPhys->mu_muid_trackcov_z0_theta;
		mu_muid_trackcov_z0_qoverp = m_mcOffPhys->mu_muid_trackcov_z0_qoverp;
		mu_muid_trackcov_phi_theta = m_mcOffPhys->mu_muid_trackcov_phi_theta;
		mu_muid_trackcov_phi_qoverp = m_mcOffPhys->mu_muid_trackcov_phi_qoverp;
		mu_muid_trackcov_theta_qoverp = m_mcOffPhys->mu_muid_trackcov_theta_qoverp;
		mu_muid_trackfitchi2 = m_mcOffPhys->mu_muid_trackfitchi2;
		mu_muid_trackfitndof = m_mcOffPhys->mu_muid_trackfitndof;
		mu_muid_hastrack = m_mcOffPhys->mu_muid_hastrack;
		mu_muid_EF_dr = m_mcOffPhys->mu_muid_EF_dr;
		mu_muid_EF_cb_eta = m_mcOffPhys->mu_muid_EF_cb_eta;
		mu_muid_EF_cb_phi = m_mcOffPhys->mu_muid_EF_cb_phi;
		mu_muid_EF_cb_pt = m_mcOffPhys->mu_muid_EF_cb_pt;
		mu_muid_EF_ms_eta = m_mcOffPhys->mu_muid_EF_ms_eta;
		mu_muid_EF_ms_phi = m_mcOffPhys->mu_muid_EF_ms_phi;
		mu_muid_EF_ms_pt = m_mcOffPhys->mu_muid_EF_ms_pt;
		mu_muid_EF_me_eta = m_mcOffPhys->mu_muid_EF_me_eta;
		mu_muid_EF_me_phi = m_mcOffPhys->mu_muid_EF_me_phi;
		mu_muid_EF_me_pt = m_mcOffPhys->mu_muid_EF_me_pt;
		mu_muid_EF_matched = m_mcOffPhys->mu_muid_EF_matched;
		mu_muid_L2CB_dr = m_mcOffPhys->mu_muid_L2CB_dr;
		mu_muid_L2CB_pt = m_mcOffPhys->mu_muid_L2CB_pt;
		mu_muid_L2CB_eta = m_mcOffPhys->mu_muid_L2CB_eta;
		mu_muid_L2CB_phi = m_mcOffPhys->mu_muid_L2CB_phi;
		mu_muid_L2CB_id_pt = m_mcOffPhys->mu_muid_L2CB_id_pt;
		mu_muid_L2CB_ms_pt = m_mcOffPhys->mu_muid_L2CB_ms_pt;
		mu_muid_L2CB_nPixHits = m_mcOffPhys->mu_muid_L2CB_nPixHits;
		mu_muid_L2CB_nSCTHits = m_mcOffPhys->mu_muid_L2CB_nSCTHits;
		mu_muid_L2CB_nTRTHits = m_mcOffPhys->mu_muid_L2CB_nTRTHits;
		mu_muid_L2CB_nTRTHighTHits = m_mcOffPhys->mu_muid_L2CB_nTRTHighTHits;
		mu_muid_L2CB_matched = m_mcOffPhys->mu_muid_L2CB_matched;
		mu_muid_L1_dr = m_mcOffPhys->mu_muid_L1_dr;
		mu_muid_L1_pt = m_mcOffPhys->mu_muid_L1_pt;
		mu_muid_L1_eta = m_mcOffPhys->mu_muid_L1_eta;
		mu_muid_L1_phi = m_mcOffPhys->mu_muid_L1_phi;
		mu_muid_L1_thrNumber = m_mcOffPhys->mu_muid_L1_thrNumber;
		mu_muid_L1_RoINumber = m_mcOffPhys->mu_muid_L1_RoINumber;
		mu_muid_L1_sectorAddress = m_mcOffPhys->mu_muid_L1_sectorAddress;
		mu_muid_L1_firstCandidate = m_mcOffPhys->mu_muid_L1_firstCandidate;
		mu_muid_L1_moreCandInRoI = m_mcOffPhys->mu_muid_L1_moreCandInRoI;
		mu_muid_L1_moreCandInSector = m_mcOffPhys->mu_muid_L1_moreCandInSector;
		mu_muid_L1_source = m_mcOffPhys->mu_muid_L1_source;
		mu_muid_L1_hemisphere = m_mcOffPhys->mu_muid_L1_hemisphere;
		mu_muid_L1_matched = m_mcOffPhys->mu_muid_L1_matched;
		
		// vertex
		vxp_n       = m_mcOffPhys->vxp_n;
		vxp_nTracks = m_mcOffPhys->vxp_nTracks;
		vxp_type    = m_mcOffPhys->vxp_type;
		vxp_z       = m_mcOffPhys->vxp_z;
		vxp_z_err   = m_mcOffPhys->vxp_z_err;
	}
	
	///////////////////////////////
	m_tree->Fill(); ///////////////
	///////////////////////////////
}

void digestTree::reset()
{
	// external
	triggers = NULL;

	// run
	RunNumber   = -999;
	lbn         = -999;
	EventNumber = -999;
	
	// staco
	mu_staco_px        = NULL;
	mu_staco_py        = NULL;
	mu_staco_pz        = NULL;
	mu_staco_E         = NULL;
	mu_staco_m         = NULL;
	mu_staco_charge    = NULL;
	mu_staco_pt        = NULL;
	mu_staco_ptcone20  = NULL;
	mu_staco_ptcone30  = NULL;
	mu_staco_ptcone40  = NULL;
	mu_staco_eta       = NULL;
	mu_staco_phi       = NULL;
	mu_staco_d0_exPV   = NULL;
	mu_staco_z0_exPV   = NULL;
	mu_staco_allauthor = NULL;
	mu_staco_author    = NULL;
	mu_staco_matchchi2 = NULL;
	mu_staco_matchndof = NULL;
	mu_staco_me_qoverp = NULL;
	mu_staco_id_qoverp = NULL;
	mu_staco_me_theta  = NULL;
	mu_staco_id_theta  = NULL;
	mu_staco_isCombinedMuon  = NULL;
	mu_staco_nSCTHits  = NULL;
	mu_staco_nPixHits  = NULL;
	mu_staco_nMDTBIHits = NULL;
	mu_staco_nMDTBMHits = NULL;
	mu_staco_nMDTBOHits = NULL;
	mu_staco_nMDTBEEHits = NULL;
	mu_staco_nMDTBIS78Hits = NULL;
	mu_staco_nMDTEIHits = NULL;
	mu_staco_nMDTEMHits = NULL;
	mu_staco_nMDTEOHits = NULL;
	mu_staco_nMDTEEHits = NULL;
	mu_staco_nRPCLayer1EtaHits = NULL;
	mu_staco_nRPCLayer2EtaHits = NULL;
	mu_staco_nRPCLayer3EtaHits = NULL;
	mu_staco_nRPCLayer1PhiHits = NULL;
	mu_staco_nRPCLayer2PhiHits = NULL;
	mu_staco_nRPCLayer3PhiHits = NULL;
	mu_staco_nTGCLayer1EtaHits = NULL;
	mu_staco_nTGCLayer2EtaHits = NULL;
	mu_staco_nTGCLayer3EtaHits = NULL;
	mu_staco_nTGCLayer4EtaHits = NULL;
	mu_staco_nTGCLayer1PhiHits = NULL;
	mu_staco_nTGCLayer2PhiHits = NULL;
	mu_staco_nTGCLayer3PhiHits = NULL;
	mu_staco_nTGCLayer4PhiHits = NULL;
	
	mu_staco_etcone20 = NULL;
	mu_staco_etcone30 = NULL;
	mu_staco_etcone40 = NULL;
	mu_staco_nucone20 = NULL;
	mu_staco_nucone30 = NULL;
	mu_staco_nucone40 = NULL;
	mu_staco_energyLossPar = NULL;
	mu_staco_energyLossErr = NULL;
	mu_staco_bestMatch = NULL;
	mu_staco_isStandAloneMuon = NULL;
	mu_staco_isLowPtReconstructedMuon = NULL;
	mu_staco_loose = NULL;
	mu_staco_medium = NULL;
	mu_staco_tight = NULL;
	mu_staco_phi_exPV = NULL;
	mu_staco_theta_exPV = NULL;
	mu_staco_qoverp_exPV = NULL;
	mu_staco_cov_d0_exPV = NULL;
	mu_staco_cov_z0_exPV = NULL;
	mu_staco_cov_phi_exPV = NULL;
	mu_staco_cov_theta_exPV = NULL;
	mu_staco_cov_qoverp_exPV = NULL;
	mu_staco_cov_d0_z0_exPV = NULL;
	mu_staco_cov_d0_phi_exPV = NULL;
	mu_staco_cov_d0_theta_exPV = NULL;
	mu_staco_cov_d0_qoverp_exPV = NULL;
	mu_staco_cov_z0_phi_exPV = NULL;
	mu_staco_cov_z0_theta_exPV = NULL;
	mu_staco_cov_z0_qoverp_exPV = NULL;
	mu_staco_cov_phi_theta_exPV = NULL;
	mu_staco_cov_phi_qoverp_exPV = NULL;
	mu_staco_cov_theta_qoverp_exPV = NULL;
	mu_staco_ms_d0 = NULL;
	mu_staco_ms_z0 = NULL;
	mu_staco_ms_phi = NULL;
	mu_staco_ms_theta = NULL;
	mu_staco_ms_qoverp = NULL;
	mu_staco_id_d0 = NULL;
	mu_staco_id_z0 = NULL;
	mu_staco_id_phi = NULL;
	mu_staco_me_d0 = NULL;
	mu_staco_me_z0 = NULL;
	mu_staco_me_phi = NULL;
	mu_staco_ie_d0 = NULL;
	mu_staco_ie_z0 = NULL;
	mu_staco_ie_phi = NULL;
	mu_staco_ie_theta = NULL;
	mu_staco_ie_qoverp = NULL;
	mu_staco_nBLHits = NULL;
	mu_staco_nTRTHighTHits = NULL;
	mu_staco_nBLSharedHits = NULL;
	mu_staco_nPixSharedHits = NULL;
	mu_staco_nPixHoles = NULL;
	mu_staco_nSCTSharedHits = NULL;
	mu_staco_nSCTHoles = NULL;
	mu_staco_nTRTOutliers = NULL;
	mu_staco_nTRTHighTOutliers = NULL;
	mu_staco_nMDTHits = NULL;
	mu_staco_nMDTHoles = NULL;
	mu_staco_nCSCEtaHits = NULL;
	mu_staco_nCSCEtaHoles = NULL;
	mu_staco_nCSCPhiHits = NULL;
	mu_staco_nCSCPhiHoles = NULL;
	mu_staco_nRPCEtaHits = NULL;
	mu_staco_nRPCEtaHoles = NULL;
	mu_staco_nRPCPhiHits = NULL;
	mu_staco_nRPCPhiHoles = NULL;
	mu_staco_nTGCEtaHits = NULL;
	mu_staco_nTGCEtaHoles = NULL;
	mu_staco_nTGCPhiHits = NULL;
	mu_staco_nTGCPhiHoles = NULL;
	mu_staco_nGangedPixels = NULL;
	mu_staco_nOutliersOnTrack = NULL;
	mu_staco_barrelSectors = NULL;
	mu_staco_endcapSectors = NULL;
	mu_staco_trackd0 = NULL;
	mu_staco_trackz0 = NULL;
	mu_staco_trackphi = NULL;
	mu_staco_tracktheta = NULL;
	mu_staco_trackqoverp = NULL;
	mu_staco_trackcov_d0 = NULL;
	mu_staco_trackcov_z0 = NULL;
	mu_staco_trackcov_phi = NULL;
	mu_staco_trackcov_theta = NULL;
	mu_staco_trackcov_qoverp = NULL;
	mu_staco_trackcov_d0_z0 = NULL;
	mu_staco_trackcov_d0_phi = NULL;
	mu_staco_trackcov_d0_theta = NULL;
	mu_staco_trackcov_d0_qoverp = NULL;
	mu_staco_trackcov_z0_phi = NULL;
	mu_staco_trackcov_z0_theta = NULL;
	mu_staco_trackcov_z0_qoverp = NULL;
	mu_staco_trackcov_phi_theta = NULL;
	mu_staco_trackcov_phi_qoverp = NULL;
	mu_staco_trackcov_theta_qoverp = NULL;
	mu_staco_trackfitchi2 = NULL;
	mu_staco_trackfitndof = NULL;
	mu_staco_hastrack = NULL;
	mu_staco_EF_dr = NULL;
	mu_staco_EF_cb_eta = NULL;
	mu_staco_EF_cb_phi = NULL;
	mu_staco_EF_cb_pt = NULL;
	mu_staco_EF_ms_eta = NULL;
	mu_staco_EF_ms_phi = NULL;
	mu_staco_EF_ms_pt = NULL;
	mu_staco_EF_me_eta = NULL;
	mu_staco_EF_me_phi = NULL;
	mu_staco_EF_me_pt = NULL;
	mu_staco_EF_matched = NULL;
	mu_staco_L2CB_dr = NULL;
	mu_staco_L2CB_pt = NULL;
	mu_staco_L2CB_eta = NULL;
	mu_staco_L2CB_phi = NULL;
	mu_staco_L2CB_id_pt = NULL;
	mu_staco_L2CB_ms_pt = NULL;
	mu_staco_L2CB_nPixHits = NULL;
	mu_staco_L2CB_nSCTHits = NULL;
	mu_staco_L2CB_nTRTHits = NULL;
	mu_staco_L2CB_nTRTHighTHits = NULL;
	mu_staco_L2CB_matched = NULL;
	mu_staco_L1_dr = NULL;
	mu_staco_L1_pt = NULL;
	mu_staco_L1_eta = NULL;
	mu_staco_L1_phi = NULL;
	mu_staco_L1_thrNumber = NULL;
	mu_staco_L1_RoINumber = NULL;
	mu_staco_L1_sectorAddress = NULL;
	mu_staco_L1_firstCandidate = NULL;
	mu_staco_L1_moreCandInRoI = NULL;
	mu_staco_L1_moreCandInSector = NULL;
	mu_staco_L1_source = NULL;
	mu_staco_L1_hemisphere = NULL;
	mu_staco_L1_matched = NULL;
	
	// muid
	mu_muid_m         = NULL;
	mu_muid_px        = NULL;
	mu_muid_py        = NULL;
	mu_muid_pz        = NULL;
	mu_muid_E         = NULL;
	mu_muid_charge    = NULL;
	mu_muid_pt        = NULL;
	mu_muid_ptcone20  = NULL;
	mu_muid_ptcone30  = NULL;
	mu_muid_ptcone40  = NULL;
	mu_muid_eta       = NULL;
	mu_muid_phi       = NULL;
	mu_muid_d0_exPV   = NULL;
	mu_muid_z0_exPV   = NULL;
	mu_muid_allauthor = NULL;
	mu_muid_author    = NULL;
	mu_muid_matchchi2 = NULL;
	mu_muid_matchndof = NULL;
	mu_muid_me_qoverp = NULL;
	mu_muid_id_qoverp = NULL;
	mu_muid_me_theta  = NULL;
	mu_muid_id_theta  = NULL;
	mu_muid_isCombinedMuon  = NULL;
	mu_muid_nSCTHits  = NULL;
	mu_muid_nPixHits  = NULL;
	mu_muid_nMDTBIHits = NULL;
	mu_muid_nMDTBMHits = NULL;
	mu_muid_nMDTBOHits = NULL;
	mu_muid_nMDTBEEHits = NULL;
	mu_muid_nMDTBIS78Hits = NULL;
	mu_muid_nMDTEIHits = NULL;
	mu_muid_nMDTEMHits = NULL;
	mu_muid_nMDTEOHits = NULL;
	mu_muid_nMDTEEHits = NULL;
	mu_muid_nRPCLayer1EtaHits = NULL;
	mu_muid_nRPCLayer2EtaHits = NULL;
	mu_muid_nRPCLayer3EtaHits = NULL;
	mu_muid_nRPCLayer1PhiHits = NULL;
	mu_muid_nRPCLayer2PhiHits = NULL;
	mu_muid_nRPCLayer3PhiHits = NULL;
	mu_muid_nTGCLayer1EtaHits = NULL;
	mu_muid_nTGCLayer2EtaHits = NULL;
	mu_muid_nTGCLayer3EtaHits = NULL;
	mu_muid_nTGCLayer4EtaHits = NULL;
	mu_muid_nTGCLayer1PhiHits = NULL;
	mu_muid_nTGCLayer2PhiHits = NULL;
	mu_muid_nTGCLayer3PhiHits = NULL;
	mu_muid_nTGCLayer4PhiHits = NULL;
	
	mu_muid_etcone20 = NULL;
	mu_muid_etcone30 = NULL;
	mu_muid_etcone40 = NULL;
	mu_muid_nucone20 = NULL;
	mu_muid_nucone30 = NULL;
	mu_muid_nucone40 = NULL;
	mu_muid_energyLossPar = NULL;
	mu_muid_energyLossErr = NULL;
	mu_muid_bestMatch = NULL;
	mu_muid_isStandAloneMuon = NULL;
	mu_muid_isLowPtReconstructedMuon = NULL;
	mu_muid_loose = NULL;
	mu_muid_medium = NULL;
	mu_muid_tight = NULL;
	mu_muid_phi_exPV = NULL;
	mu_muid_theta_exPV = NULL;
	mu_muid_qoverp_exPV = NULL;
	mu_muid_cov_d0_exPV = NULL;
	mu_muid_cov_z0_exPV = NULL;
	mu_muid_cov_phi_exPV = NULL;
	mu_muid_cov_theta_exPV = NULL;
	mu_muid_cov_qoverp_exPV = NULL;
	mu_muid_cov_d0_z0_exPV = NULL;
	mu_muid_cov_d0_phi_exPV = NULL;
	mu_muid_cov_d0_theta_exPV = NULL;
	mu_muid_cov_d0_qoverp_exPV = NULL;
	mu_muid_cov_z0_phi_exPV = NULL;
	mu_muid_cov_z0_theta_exPV = NULL;
	mu_muid_cov_z0_qoverp_exPV = NULL;
	mu_muid_cov_phi_theta_exPV = NULL;
	mu_muid_cov_phi_qoverp_exPV = NULL;
	mu_muid_cov_theta_qoverp_exPV = NULL;
	mu_muid_ms_d0 = NULL;
	mu_muid_ms_z0 = NULL;
	mu_muid_ms_phi = NULL;
	mu_muid_ms_theta = NULL;
	mu_muid_ms_qoverp = NULL;
	mu_muid_id_d0 = NULL;
	mu_muid_id_z0 = NULL;
	mu_muid_id_phi = NULL;
	mu_muid_me_d0 = NULL;
	mu_muid_me_z0 = NULL;
	mu_muid_me_phi = NULL;
	mu_muid_ie_d0 = NULL;
	mu_muid_ie_z0 = NULL;
	mu_muid_ie_phi = NULL;
	mu_muid_ie_theta = NULL;
	mu_muid_ie_qoverp = NULL;
	mu_muid_nBLHits = NULL;
	mu_muid_nTRTHighTHits = NULL;
	mu_muid_nBLSharedHits = NULL;
	mu_muid_nPixSharedHits = NULL;
	mu_muid_nPixHoles = NULL;
	mu_muid_nSCTSharedHits = NULL;
	mu_muid_nSCTHoles = NULL;
	mu_muid_nTRTOutliers = NULL;
	mu_muid_nTRTHighTOutliers = NULL;
	mu_muid_nMDTHits = NULL;
	mu_muid_nMDTHoles = NULL;
	mu_muid_nCSCEtaHits = NULL;
	mu_muid_nCSCEtaHoles = NULL;
	mu_muid_nCSCPhiHits = NULL;
	mu_muid_nCSCPhiHoles = NULL;
	mu_muid_nRPCEtaHits = NULL;
	mu_muid_nRPCEtaHoles = NULL;
	mu_muid_nRPCPhiHits = NULL;
	mu_muid_nRPCPhiHoles = NULL;
	mu_muid_nTGCEtaHits = NULL;
	mu_muid_nTGCEtaHoles = NULL;
	mu_muid_nTGCPhiHits = NULL;
	mu_muid_nTGCPhiHoles = NULL;
	mu_muid_nGangedPixels = NULL;
	mu_muid_nOutliersOnTrack = NULL;
	mu_muid_barrelSectors = NULL;
	mu_muid_endcapSectors = NULL;
	mu_muid_trackd0 = NULL;
	mu_muid_trackz0 = NULL;
	mu_muid_trackphi = NULL;
	mu_muid_tracktheta = NULL;
	mu_muid_trackqoverp = NULL;
	mu_muid_trackcov_d0 = NULL;
	mu_muid_trackcov_z0 = NULL;
	mu_muid_trackcov_phi = NULL;
	mu_muid_trackcov_theta = NULL;
	mu_muid_trackcov_qoverp = NULL;
	mu_muid_trackcov_d0_z0 = NULL;
	mu_muid_trackcov_d0_phi = NULL;
	mu_muid_trackcov_d0_theta = NULL;
	mu_muid_trackcov_d0_qoverp = NULL;
	mu_muid_trackcov_z0_phi = NULL;
	mu_muid_trackcov_z0_theta = NULL;
	mu_muid_trackcov_z0_qoverp = NULL;
	mu_muid_trackcov_phi_theta = NULL;
	mu_muid_trackcov_phi_qoverp = NULL;
	mu_muid_trackcov_theta_qoverp = NULL;
	mu_muid_trackfitchi2 = NULL;
	mu_muid_trackfitndof = NULL;
	mu_muid_hastrack = NULL;
	mu_muid_EF_dr = NULL;
	mu_muid_EF_cb_eta = NULL;
	mu_muid_EF_cb_phi = NULL;
	mu_muid_EF_cb_pt = NULL;
	mu_muid_EF_ms_eta = NULL;
	mu_muid_EF_ms_phi = NULL;
	mu_muid_EF_ms_pt = NULL;
	mu_muid_EF_me_eta = NULL;
	mu_muid_EF_me_phi = NULL;
	mu_muid_EF_me_pt = NULL;
	mu_muid_EF_matched = NULL;
	mu_muid_L2CB_dr = NULL;
	mu_muid_L2CB_pt = NULL;
	mu_muid_L2CB_eta = NULL;
	mu_muid_L2CB_phi = NULL;
	mu_muid_L2CB_id_pt = NULL;
	mu_muid_L2CB_ms_pt = NULL;
	mu_muid_L2CB_nPixHits = NULL;
	mu_muid_L2CB_nSCTHits = NULL;
	mu_muid_L2CB_nTRTHits = NULL;
	mu_muid_L2CB_nTRTHighTHits = NULL;
	mu_muid_L2CB_matched = NULL;
	mu_muid_L1_dr = NULL;
	mu_muid_L1_pt = NULL;
	mu_muid_L1_eta = NULL;
	mu_muid_L1_phi = NULL;
	mu_muid_L1_thrNumber = NULL;
	mu_muid_L1_RoINumber = NULL;
	mu_muid_L1_sectorAddress = NULL;
	mu_muid_L1_firstCandidate = NULL;
	mu_muid_L1_moreCandInRoI = NULL;
	mu_muid_L1_moreCandInSector = NULL;
	mu_muid_L1_source = NULL;
	mu_muid_L1_hemisphere = NULL;
	mu_muid_L1_matched = NULL;
	
	
	// vertex variables
	vxp_z       = NULL;
	vxp_z_err   = NULL;
	vxp_nTracks = NULL;
	vxp_type    = NULL;
}

void digestTree::write()
{
	m_treeFile->cd();
	m_tree->Write();
}


