/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXTENDEDEXPONENT
#define ROOEXTENDEDEXPONENT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExtendedExponent : public RooAbsPdf {
public:
  RooExtendedExponent() {} ; 
  RooExtendedExponent(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a,
	      RooAbsReal& _b);
  RooExtendedExponent(const RooExtendedExponent& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExtendedExponent(*this,newname); }
  inline virtual ~RooExtendedExponent() { }

protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExtendedExponent,1) // Your description goes here...
};
 
#endif
