 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 
 #include "TROOT.h"
 #include "TMath.h"
 #include "RooCollinsSoper.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 

 ClassImp(RooCollinsSoper) 

 RooCollinsSoper::RooCollinsSoper(const char *name, const char *title, 
                        RooAbsReal& _costheta,
                        RooAbsReal& _A0,
                        RooAbsReal& _A4) :
   RooAbsPdf(name,title), 
   costheta("costheta","costheta",this,_costheta),
   A0("A0","A0",this,_A0),
   A4("A4","A4",this,_A4)
 { 
 } 


 RooCollinsSoper::RooCollinsSoper(const RooCollinsSoper& other, const char* name) :  
   RooAbsPdf(other,name), 
   costheta("costheta",this,other.costheta),
   A0("A0",this,other.A0),
   A4("A4",this,other.A4)
 { 
 } 



 Double_t RooCollinsSoper::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE
   Double_t dflt = 1.e-30;
   Double_t pdf = (3./8.)*(1. + A0/2. + A4*costheta + (1.-(3./2.)*A0)*costheta*costheta);
   return (pdf>0.) ? pdf : dflt;
 } 



