 /***************************************************************************** 
  * Project: RooFit                                                           * 
  *                                                                           * 
  * This code was autogenerated by RooClassFactory                            * 
  *****************************************************************************/ 

 // Your description goes here... 

 #include "Riostream.h" 
 #include "TROOT.h"
 #include "TMath.h"
 #include "RooExtendedExponent.h" 
 #include "RooAbsReal.h" 
 #include "RooAbsCategory.h" 

 ClassImp(RooExtendedExponent) 

 RooExtendedExponent::RooExtendedExponent(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _a,
                        RooAbsReal& _b) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   a("a","a",this,_a),
   b("b","b",this,_b)
 { 
 } 


 RooExtendedExponent::RooExtendedExponent(const RooExtendedExponent& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   a("a",this,other.a),
   b("b",this,other.b)
 { 
 } 



 Double_t RooExtendedExponent::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   if((a*x+b)<0.  &&  a<0.) return TMath::Exp(a*x + b);
   return 1.;
 } 



