/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOANGULAR
#define ROOANGULAR

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAngular : public RooAbsPdf {
public:
  RooAngular() {} ; 
  RooAngular(const char *name, const char *title,
	RooAbsReal& _costheta,
	RooAbsReal& _A,
	RooAbsReal& _B);
  RooAngular(const RooAngular& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAngular(*this,newname); }
  inline virtual ~RooAngular() { }

protected:

  RooRealProxy costheta ;
  RooRealProxy A ;
  RooRealProxy B ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooAngular,1) // Your description goes here...
};
 
#endif
